### ISSUE TITLE
Control Raspberry GPIO

### ISSUE THREAD

**Issue by skuppens** [csuermann/node-red-contrib-virtual-smart-home#10]
Hi,

I'm getting a NAN output from my Raspberry Pi Node.
So It's not switching the GPIO to HIGH...

It requires a 1 or 0...

Any idea's how to resolve this?

**Comment by csuermann** [comment]
It's hard to help here with so little information at hand. I might be able to provide some guidance if you shared your flow.

**Comment by skuppens** [comment]
This is an export from my FLow as it is now.
Alexa detects it, but when I Ask her to turn it on she Says: "OK"... but nothing happens.
In the debug messages I can read: "Invalid Input: NaN"

Actually this comes from the GPIO node. Not the vsh.. 
Thank you for your time and help.
`[
    {
        "id": "78394e8.36cad3",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "39926dcc.f57cd2",
        "type": "rpi-gpio out",
        "z": "78394e8.36cad3",
        "name": "Waterpump",
        "pin": "33",
        "set": true,
        "level": "0",
        "freq": "",
        "out": "out",
        "x": 700,
        "y": 260,
        "wires": []
    },
    {
        "id": "c5c76f4d.8faaa",
        "type": "ui_switch",
        "z": "78394e8.36cad3",
        "name": "Switch",
        "label": "switch",
        "tooltip": "",
        "group": "b6730416.15d12",
        "order": 0,
        "width": 0,
        "height": 0,
        "passthru": true,
        "decouple": "false",
        "topic": "",
        "style": "",
        "onvalue": "1",
        "onvalueType": "num",
        "onicon": "",
        "oncolor": "",
        "offvalue": "0",
        "offvalueType": "num",
        "officon": "",
        "offcolor": "",
        "x": 280,
        "y": 120,
        "wires": [
            [
                "39926dcc.f57cd2"
            ]
        ]
    },
    {
        "id": "bf3a983a.416a28",
        "type": "vsh-virtual-device",
        "z": "78394e8.36cad3",
        "name": "Waterpump",
        "connection": "1ea54575.823bc3",
        "template": "SWITCH",
        "passthrough": false,
        "x": 300,
        "y": 360,
        "wires": [
            [
                "39926dcc.f57cd2"
            ]
        ]
    },
    {
        "id": "b6730416.15d12",
        "type": "ui_group",
        "name": "Default",
        "tab": "2a374143.54757e",
        "order": 1,
        "disp": true,
        "width": "6",
        "collapse": false
    },
    {
        "id": "1ea54575.823bc3",
        "type": "vsh-connection",
        "name": "Waterpump",
        "port": "8883",
        "accessTokenExpiry": "1605614263455"
    },
    {
        "id": "2a374143.54757e",
        "type": "ui_tab",
        "name": "Home",
        "icon": "dashboard",
        "disabled": false,
        "hidden": false
    }
]`

**Comment by skuppens** [comment]
Hi,
If I import your example, you can see that the payload is set to "ON".
I Think this should be set to 0 or 1 just to be able to switch the digital out pin of the Raspberry pi.
I'm trying to alter your example, but havan't had much success to far...

**Comment by csuermann** [comment]
Your problem is indeed not related to vsh at all.

You need to convert the output of the vsh node into the value you need for your GPIO node. This can for instance be done with a change node:

![image](https://user-images.githubusercontent.com/10939809/99420459-86e62a00-28fd-11eb-9d15-9af3ce69812d.png)

**Comment by skuppens** [comment]
Thank you! It works now.
