### ISSUE TITLE
[FEATURE REQUEST] Add Device that Triggered a Directive to the Payload

### ISSUE THREAD

**Issue by jtrahan** [csuermann/node-red-contrib-virtual-smart-home#100]
Currently the payload does not include the device that initiated a directive. It would be nice, if possible, to include the device into the payload to trigger other rules. 

Currently as a workaround I have to use node-red-contrib-alexa-remote2-applestrudel and monitor the alexa events to determine this but it would be more convenient if the device was included with the payload

**Comment by csuermann** [comment]
Hi @jtrahan,
This request has been raised many times before, but since VSH is build on the foundation of Alexa's smart home API, which doesn't expose any information about the originating device, there is not much I can do here.

**Comment by jtrahan** [comment]
Understood. Thanks for replying though. I'll just continue to use this workaround.
