### ISSUE TITLE
New install, says I need to upgrade my version, I'm already running 2.12.1

### ISSUE THREAD

**Issue by UnbridledGames** [csuermann/node-red-contrib-virtual-smart-home#102]
Brand new install, node.js 12, node-red 2.0.6.

Enabled the virtual-smart-home skill in Alexa.

In node-red, I clicked the menu bars in the upper right, hit Manage Palette, clicked the install tab, and installed node-red-contrib-virtual-smart-home.

It shows version 2.12.1 installed.

I added a virtual device, clicked to configure it, linked my account. Connected it to a debug node. Deployed.

It says "Initializing..."  under the node.

Looked in /var/log/syslog and I see this:

Sep 21 07:34:46 plex Node-RED[1280]: 21 Sep 07:34:46 - [info] Server now running at http://127.0.0.1:1880/
Sep 21 07:34:46 plex Node-RED[1280]: 21 Sep 07:34:46 - [warn]
Sep 21 07:34:46 plex Node-RED[1280]: ---------------------------------------------------------------------
Sep 21 07:34:46 plex Node-RED[1280]: Your flow credentials file is encrypted using a system-generated key.
Sep 21 07:34:46 plex Node-RED[1280]: If the system-generated key is lost for any reason, your credentials
Sep 21 07:34:46 plex Node-RED[1280]: file will not be recoverable, you will have to delete it and re-enter
Sep 21 07:34:46 plex Node-RED[1280]: your credentials.
Sep 21 07:34:46 plex Node-RED[1280]: You should set your own key using the 'credentialSecret' option in
Sep 21 07:34:46 plex Node-RED[1280]: your settings file. Node-RED will then re-encrypt your credentials
Sep 21 07:34:46 plex Node-RED[1280]: file using your chosen key the next time you deploy a change.
Sep 21 07:34:46 plex Node-RED[1280]: ---------------------------------------------------------------------
Sep 21 07:34:46 plex Node-RED[1280]: 21 Sep 07:34:46 - [info] Starting flows
Sep 21 07:34:47 plex Node-RED[1280]: 21 Sep 07:34:47 - [info] Started flows
Sep 21 07:34:47 plex Node-RED[1280]: 21 Sep 07:34:47 - [warn] [vsh-connection:myEmail@myAmazonEmail.com] A newer version of VSH is available! Your system might no longer work as expected
Sep 21 07:34:47 plex Node-RED[1280]: 21 Sep 07:34:47 - [error] [vsh-connection:myEmail@myAmazonEmail.com] connection to backend refused: Please update to the latest version of VSH!

I'm using the latest version, everything appears connected correctly. Can't find any answers by googling and this seemed to be the best place to ask.

**Comment by csuermann** [comment]
Hi @UnbridledGames,

Sorry to hear you're running into problems here. Could you kindly inspect the network tab of the developer tools while attempting to provision a new VSH connection and report back on the details of the query highlighted below?

![image](https://user-images.githubusercontent.com/10939809/134170284-cecd1846-dad6-4b8a-a7aa-2d5010ddd525.png)

Thanks!

**Comment by UnbridledGames** [comment]
Ok, so here's what I've done since I posted my bug on github:

I looked through the issues and saw someone had installed
virtual-smart-home via a npm command. So I removed all of VSH, restarted
NR, verified it was gone. Shut down NR, and installed it via: sudo npm
install node-red-contrib-virtual-smart-home

Started NR.

Then I saw your email.

Opened up NR, added a new virtual device node, and when I clicked the
pencil to add the connection, that check_version line reported:
{
  "isAllowedVersion": true,
  "isLatestVersion": true,
  "updateHint": "",
  "allowedDeviceCount": 100
}

I went through with adding it, deployed, and it appears to be working now.
Maybe there is a bug when VSH is installed through Manage Palettes? The npm
install seemed to work.

**Comment by UnbridledGames** [comment]
Except now that it says the node is Online, Alexa does not see the device.
Is there possibly a step I missed?

VSH is enabled in my Alexa.

I have a published node with a vsh-connection to the same amazon account.
From reading the docs I shouldn't need more than that correct?

**Comment by csuermann** [comment]
Hi @UnbridledGames,

Glad to hear the issue resolved itself. It's difficult to speculate what could have caused the glitch. Thanks for reporting back!
