### ISSUE TITLE
Triggers for routines not available or working?

### ISSUE THREAD

**Issue by UnbridledGames** [csuermann/node-red-contrib-virtual-smart-home#103]
I'm currently using node-red to monitor the power usage of my washing machine, and after it enters the spin cycle (an extended period of constant high energy use), once the power drops again, I'm trying to trigger some "The laundry is done" notifications.

Trying to use VSH to create an Alexa routine that will speak "The laundry is done" or something similar.

Problem is, none of the virtual devices seem to be able to trigger anything in Alexa. The doorbell event, when I trigger it, WILL cause Alexa to 'ding-dong' and announce someone is at the "VSH Name" if the announcements are enabled. However, if I try and create a routine for when the button is pushed - nothing happens at all, it's never triggered.

If I try and use a Contact Sensor or Motion Sensor, when creating a routine, the app says This Device is not currently supported.

Some of the others that should have supported triggers for routines don't seem to..?

It's not the end of the world, I can "hack" some other workaround, but it would be nice if my Alexa could respond/give me an alert from something happening in node-red. Am I bugged or maybe misconfiguring something?

Version 2.12.1

**Comment by UnbridledGames** [comment]
Well my thought was that an Alexa compatible device, which was a sensor or trigger would be able to fire off an Alexa routine. If the other package is better suited I’ll give it a look. Thanks for the recommendation. 

That being said, it’s still worth noting that this is still a “bug” of sorts. There’s little point to emulating a contact or motion sensor if Alexa cannot react to changes in those sensors. (Unless some other software can react to it?)

**Comment by csuermann** [comment]
You should be able to accomplish what you want to do with VSH! I just tried it out with a fake motion sensor and it worked like a charm:

![image](https://user-images.githubusercontent.com/10939809/134460560-b41d5f8f-6a01-4c5a-ad4a-816464305702.png)

```
[{"id":"efc896d1.7001a8","type":"vsh-virtual-device","z":"3156dd60.366d12","name":"washing machine","topic":"","connection":"","template":"MOTION_SENSOR","passthrough":false,"diff":false,"filter":false,"x":1470,"y":580,"wires":[[]]},{"id":"c9e0153d.a8fd58","type":"inject","z":"3156dd60.366d12","name":"motion","props":[{"p":"payload.detectionState","v":"DETECTED","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":1210,"y":580,"wires":[["efc896d1.7001a8"]]},{"id":"51f1a442.3442ac","type":"inject","z":"3156dd60.366d12","name":"no motion","props":[{"p":"payload.detectionState","v":"NOT_DETECTED","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":1220,"y":620,"wires":[["efc896d1.7001a8"]]}]
```

![image](https://user-images.githubusercontent.com/10939809/134460666-c573f475-68b1-468a-9422-11e50eef7bb5.png)

**Comment by UnbridledGames** [comment]
This is so weird. My installation must be haunted. I got up this morning, read your reply, and the contact sensor I had in my flow that was absolutely not working yesterday, suddenly worked. 

I’m going to stop reporting any “bugs” I find from now on, and will just wait for them to fix themselves and magically start working on their own in a little bit. 

I legit worked on this for hours yesterday. You reply that it works fine, and I check again and it does. 

Thanks for your help and patience. Really appreciate it. I’ll hit up that donation button shortly. :)
