### ISSUE TITLE
[FEATURE REQUEST] Thermostat name

### ISSUE THREAD

**Issue by bwims** [csuermann/node-red-contrib-virtual-smart-home#104]
**Is your feature request related to a problem? Please describe.**

Whatever the name of the thermostat, the response from Alexa when setting or enquiring, is "The heat is set to xx"

**Describe the solution you'd like**
When I ask "What is the temperature set to upstairs, Alexa should reply "The upstairs temperature is xx" [where upstairs is the name of the device]

**Describe alternatives you've considered**
I do not have a branded Alexa-enabled thermostat, but I use Sonoff switch with temperature sensor.  Up until now, I have been using the deprecated skill "Node-RED Alexa Home Skill Bridge" which worked that way for a few years until Amazon decided to change the code.

**Additional context**
I guess the skill is deprecated due to some massive API rewrite, which might explain why after setting the temperature, Alexa says "I'm not sure what went wrong"  I intend to migrate to your skill, which contains much more functionality!

Thanks!

**Comment by csuermann** [comment]
I'm afraid there's nothing I can do here, as this behaviour is not something controlled by VSH but rather by Amazon.
