### ISSUE TITLE
[BUG] No msg output from voice command for temperature sensor

### ISSUE THREAD

**Issue by bwims** [csuermann/node-red-contrib-virtual-smart-home#105]
**Describe the bug**
A device is supposed to emit a message block when accessed via Alexa voice or app.
Temperature sensors only seem to emit a message block when receiving one as input.

**To Reproduce**
1. ...Create a temperature sensor and a debug node. 
2. ...Ask Alexa its temperature.
3. ...No msg block is emitted
4. Set initial temperature via input payload, and a msg block is emitted
5. Ask Alexa its temperature.
6. No msg block is emitted

**Expected behavior**
As per description:
"The node gets invoked through Amazon Alexa (either via a voice command or via the Alexa app) and outputs a msg object containing the updated device state as payload. "

**Screenshots**

**Environment (please complete the following information):**
 - virtual-smart-home version: 2.12.1
 - Node-RED version: 1.1.3

**Additional context**

**Comment by csuermann** [comment]
Hi @bwims,

A 'Sensor' is not a device that can be controlled by Alexa. Instead it can be used to send its state (e.g. temperature) to Alexa so that it can be displayed in the Alexa app and used in routines etc.

Virtual devices in VSH typically fall into one of these two categories (sometimes even both):

1. **Actors**, such as light bulbs, switches, fans etc.
    - You can control them via Alexa
    - They emit their state as outbound message objects
    - You use these outbound messages to do something useful, e.g. controlling _real_ / physical devices that do not support Alexa natively
2. **Sensors**, such as temperature or contact sensor
    - You _cannot_ control them via Alexa, but you can retrieve their state (e.g. "Alexa, what's the temperature in the kitchen?")
    - You feed them _inbound_ message objects to update their state (e.g. measured by _real_ / physical sensors), which will be forwarded to Alexa, too
    - If you enabled the 'Emit state on inbound message' option, the new state will also result in an outbound msg

**Comment by csuermann** [comment]
Hi Brian,

Thanks for your feedback!

The wording in the readme was probably put together before sensors were added to VSH. I guess it could be tweaked further, but it's already hinting toward commands / directives (as opposed to inquiries) by mentioning "_updated_ device state".

> "The node gets invoked through Amazon Alexa (either via a voice **command** or via the Alexa app) and outputs a msg object containing the **updated** device state as payload."

I tested the behavior of the virtual thermostat just now and cannot confirm that it outputs a msg object when I ask Alexa for its current temperature. It only does so when I instruct Alexa to _change_ the target temperature, which does not affect the temperature sensor, but rather the thermostat itself.

In v1.x state inquiries didn't even reach your local device but were responded to in the cloud from cached values. In v2.x this isn't the case anymore and _theoretically_ / technically "ReportState" directives could result in outbound messages, but this would be a breaking change. Could you elaborate why you think this behavior would make sense?

Thanks!

Cornelius

**Comment by bwims** [comment]
Many thanks!

B.
