### ISSUE TITLE
Alexa only discovers 24 devices Part 2

### ISSUE THREAD

**Issue by CoolRiderThe1st** [csuermann/node-red-contrib-virtual-smart-home#107]
Hello.
A copple of months ago, I wrote an issue: https://githubmemory.com/@CoolRiderThe1st

I was on a longer business trip, so I couldn't do tests and researches on my system. I think I found out what the problem was.
At that time, I had also installed node-red-contrib-amazon-echo and node-red-contrib-alexa-home.
Now that I removed these both nodes, VHS finds 200 devices. I know that it's possible to put my account up to 300 devices. Can you do that for me, so I can see and test that everything is working?
Thanks in advance.

**Comment by csuermann** [comment]
Hi @CoolRiderThe1st,

If I remember correctly I bumped your account to 300 devices [back then](#92)?!
