### ISSUE TITLE
[BUG] Utterances have been limited for Thermostats

### ISSUE THREAD

**Issue by bwims** [csuermann/node-red-contrib-virtual-smart-home#110]
**Describe the bug**

The previous version of the Alexa software allowed the utterance of "What is xx set to" where xx is a thermostat name.
This used to initiate the GetTargetTemperatureRequest .  
Now Alexa responds with "It doesn't look like your device supports that yet"

I now have to use the unwieldy form "What is the xx target temperature" -  a bit of a mouthful.

Possibly this is because of the new "Modes" that you can set also?

I just wondered if there was a bit of code when that utterance is matched that can default to temperature?  (Not clever enough to work through the Alex developers stuff...)

I've looked for the current utterances model for the thermostatcontroller, but haven't yet located it.

**To Reproduce**

as above

Thanks!

**Comment by csuermann** [comment]
VSH is based on Alexa's smart-home-skill, which comes with predefined utterances I have no control over. You might want to report this bug to Amazon instead.
