### ISSUE TITLE
Alexa all devices detected more than once

### ISSUE THREAD

**Issue by MosesHill** [csuermann/node-red-contrib-virtual-smart-home#114]
**Describe the bug**
I have used Virtual Smart Home on a PI 3 in a node-red installation without docker. I had these problem and decided to upgrade anyway so:
I just installed node-red in docker on a new PI 4.
Created some Virtual Smart Home nodes and found out, that alexa device discovery found the same node 2 - sometimes 3 or 4 times!
Even when I created a Virtual Smart Home node without any real device hardware behind it that maybe could be seen by alexa ... I get this node registered 2-3 times in the alexa device list.

**To Reproduce**
- Clean install PI 4
- Install Docker, IOTstack with Node-red (up-to-date today)
- Add the Virtual Smart Home skill to Alexa
- Register the skill
- Put a Virtual Smart Home node in Node-red
- Start Alexa registering
Now you get 2-3 registrations of the same device

**Expected behavior**
Any Virtual Smart Home node should only show up once in the Alexa device list

**Environment (please complete the following information):**
 - virtual-smart-home version: 2.13.1
 - Node-RED version: 2.1.3

**Additional context**

**Comment by csuermann** [comment]
Hi @MosesHill,

please refer to [FAQ 4 and 5](https://github.com/csuermann/node-red-contrib-virtual-smart-home#faq).
