### ISSUE TITLE
Using the Thermostat code 

### ISSUE THREAD

**Issue by DaveTiff** [csuermann/node-red-contrib-virtual-smart-home#117]
**Describe the bug**

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - virtual-smart-home version: [e.g. 1.22.4]
 - Node-RED version: [e.g. 1.2.6]

**Additional context**

**Comment by DaveTiff** [comment]
When ever I ask Alexa to set the thermostat to a temperature she replies "its Off", the correct temperature is received in the Node Red payload. If I ask Alexa to "Turn Bedroom On or Off" I get the conformation sound. But if I ask to Turn Bedroom Thermostat on and the ask to set temperature she will always reply "Its Off"

Regards  Dave

**Comment by csuermann** [comment]
Do you see the same behaviour when using the Alexa app instead of your voice?

(This seems to be related to #82)

**Comment by DaveTiff** [comment]
Have just reinstalled Node Red, started from Scratch, created a Virtual Thermostat called Lounge.
 used this in a function node to pass Temp Value to HA
`var targetTemperature = msg.payload.targetTemperature;
msg.temp = targetTemperature;
return msg;
`
If I go to the Alexa App, I see this but no control. If I speak into the App the Temperature changes but still replies "its Off"
![Screenshot_2021-11-26-11-45-21](https://user-images.githubusercontent.com/25724769/143576776-f0614df1-8439-4a83-b246-d77951c85d92.png)

If a click on the Lounge Icon, I get this page
![Screenshot_2021-11-26-11-45-45](https://user-images.githubusercontent.com/25724769/143576977-a5bdd6ba-4515-4542-a473-81dbf658d6be.png)

Not sure how Alexa know the state of the thermostat, do I need to pass data back?

Regards Dave

**Comment by pshellguruwannabe** [comment]
I see the same behavior in my setup.  Thermostat receives correct temp setting, but Alexa replies "it's off"

**Comment by csuermann** [comment]
Thermostat `mode` and `target temperature` are two distinct settings. When you change the target temperature the mode stays unchanged and vice versa. However, if the mode is set to "OFF" (= VSH default value) and you set a new target temperature, Alexa will hint at that by saying "it is off", which is a rather confusing response IMO. You can fix this by explicitly setting the mode to "heat" or "cool" once and for all (e.g. "Alexa, set office thermostat mode to heat").

**Comment by DaveTiff** [comment]
That worked ok, is there a way for Alexa to get the room temperature and the target temperature if its been changed manually.

Regards Dave

**Comment by csuermann** [comment]
You should be able to ask Alexa for the current temperature (e.g. "Alexa, what's the temperature in the office"), but as far as I know Amazon doesn't support querying the target temperature yet.

**Comment by smcgann99** [comment]
it is supported I use it with node-red-contrib-alexa-home-skill

`if (msg.command === "GetTargetTemperatureRequest") {
        x =global.get('nest1_target_temperature');
        y =global.get('heating_current_mode');
        msg.extra = {
        "targetTemperature": {"value": x},
        "applianceResponseTimestamp": new Date().toISOString(),
        "temperatureMode": {"value": y} };
        msg.payload = true;
        return msg 
    }`

**Comment by DaveTiff** [comment]
Interesting

I think I have looked at that once before, do you not have to re-authenticate every time you deploy and every 3 days? 

Could I see your node red flow, which output device do you use to feed back info to Alexa

Regards Dave

**Comment by smcgann99** [comment]
https://alexa-node-red.bm.hardill.me.uk/docs

**Comment by DaveTiff** [comment]
That one longer works, spent hours on it today, ended up contacted the author here is the reply.

_"Something appears to have changed on Amazon's end because the test devices I have fail as well with the message "I'm not quite sure what went wrong", which is a totally useless error message from a debugging point of view.
This service is no longer being actively being developed and Amazon have even removed all access to the doc for the version of the API it was written against. I don't have the time (or the inclination as I have moved whole sale over to using Google Home f) to rewrite the whole service to use the newer version of the Home Skill API. So it looks like thermostat devices will have to stay broken unless Amazon revert what ever change they made that broke them."_

**Comment by smcgann99** [comment]
Odd- where are you based? Its still working OK for me as per code example I posted.

**Comment by DaveTiff** [comment]
In the UK

**Comment by smcgann99** [comment]
Also in uk - if you just copy my code, set fixed values for testing and feed thermostat message via that in to response node it should report the mode eg heat cool auto and set point.

**Comment by DaveTiff** [comment]
Would love to try that, where can I get your code?

**Comment by smcgann99** [comment]
as above with fiexed values -
if (msg.command === "GetTargetTemperatureRequest") { x =20; y ="AUTO"; msg.extra = { "targetTemperature": {"value": x}, "applianceResponseTimestamp": new Date().toISOString(), "temperatureMode": {"value": y} }; msg.payload = true; return msg }

**Comment by DaveTiff** [comment]
With the above code in a function module I get no output to the debug node

![image](https://user-images.githubusercontent.com/25724769/143940218-4171cbe8-6d74-48d3-a319-bfcf8394bed8.png)

![image](https://user-images.githubusercontent.com/25724769/143940342-bc71f687-1d7e-431e-b962-6c342a4bfc0d.png)

**Comment by smcgann99** [comment]
![image](https://user-images.githubusercontent.com/52132596/143965297-427ff697-64a5-4761-9900-58b327ff8723.png)

**Comment by smcgann99** [comment]
have you set it up as above ? If so then you can ask "what is the lounge temperature **set to**" for the target temp

**Comment by DaveTiff** [comment]
Ok, now working, my stat was set up correctly on the Node-RED Alexa Home Skill Bridge wedsite.

I just copied and pasted you code. Set Temp Works, Get Temp Works, Inc, Dec, On & Off all dont work but at least I have made progress. Many thanks for you help and patients, agreed that any further posting will be on the Node Red Forum

Once again Thank you
