### ISSUE TITLE
Can't enable Virtual Smart Home in Amazon

### ISSUE THREAD

**Issue by jeroenst** [csuermann/node-red-contrib-virtual-smart-home#118]
I want to use Virtual Smart Home in the Netherlands but I get the following error on Amazon when I want to enable it:

You are not eligible to enable this skill due to geographical restrictions.

So i am unable to use this module, can this be fixed?

**Comment by csuermann** [comment]
I'm afraid the skill isn't localized for Dutch yet.

**Comment by jeroenst** [comment]
Well it doesn't have to support Dutch, English is perfect for me but I want to use this in the Netherlands, why is enabling this module prohibited?

**Comment by csuermann** [comment]
I have no clue why you cannot use it from the Netherlands. The skill is published to all countries that Alexa supports.

**Comment by DrDeadGuy67** [comment]
Same problem in Denmark: You are not eligible to enable this skill due to geographical restrictions...
