### ISSUE TITLE
[BUG] Darkmode not readable

### ISSUE THREAD

**Issue by nicedevil007** [csuermann/node-red-contrib-virtual-smart-home#119]
**Describe the bug**
I installed a darkmode in Node-RED. If you have 2 different accounts on VSH activated (I'm right on removing the old one, switched to new host) it is impossible to read the ones from the old account.

**Screenshots**
![image](https://user-images.githubusercontent.com/17103076/145721804-e028bb9a-cc48-4161-a343-ef4e5771444d.png)

**Environment (please complete the following information):**
 - virtual-smart-home version: 2.13.1
 - Node-RED version: 2.1.4

**Comment by csuermann** [comment]
Thanks for reporting! Which theme do you use exactly?

**Comment by nicedevil007** [comment]
I use "dracula-scrolling"
