### ISSUE TITLE
[help wanted] Dateneingang für Virutal Smart Home Geräte

### ISSUE THREAD

**Issue by Domi920** [csuermann/node-red-contrib-virtual-smart-home#120]
Hallo,
Auf meinen Raspberry Pi 4 habe ich ein IOBroker System mit einer NodeRed Instanz am Laufen.

Habe nun schon erfolgreich meine Heizungsregler Alexa-fähig gemacht.
Dazu musste ich nur ein VSH Gerät anlegen und mit einer Funktion den Wert an das IOBroker System übergeben.

Nun wäre es noch interessant, wie ich den aktuellen Temperaturwert vom Raum, sprich die Ist-Temperatur mit auf das VSH Gerät bringe.

Es gibt dazu einen Baustein in NodeRed, der mir den Zahlenwert ausgibt.
Bleibt noch die Frage, wie ich diesen Wert in das VSH Gerät bringe?

Hab ein paar Versuche mit den Funktionen probiert, nur leider ohne Erfolg.

Sorry, für die wahrscheinlich doofe Frage.

Vielen Dank für die Hilfe!

Gruß Dominik

**Comment by csuermann** [comment]
Hi @Domi920,

schau Dir mal das Thermostat-Beispiel an, dass Du über Node-RED importieren kannst:

![image](https://user-images.githubusercontent.com/10939809/147340646-c4147cce-a4cf-4767-b802-4f5ad7aa4c54.png)

**Comment by Domi920** [comment]
Hi @csuermann die Beispiele hab ich mir angesehen.
Leider weiß ich nicht wie ich den Wert in das Alexa Gerät bekomme. Da fehlt noch eine Funktion oder etwas.
Nur hier bleibe ich stecken mit meinen Wissen.

So sieht es in NodeRed aus:
![Import Daten (Temperatur) IOBroker zu Alexa Gerät 1](https://user-images.githubusercontent.com/68474558/147474044-926cf9bb-f09d-4eab-b791-3fb192af0f82.jpg)

Nun muss ich den von IOBroker übermittelten Wert in das VSH Alexa Gerät bringen.
Wenn ich das richtig sehe muss der Wert in "payload.temperature" geschrieben werden.
Wie mache ich das?
Im Beispiel wird noch etwas gesetzt:
"payload.scale" auf "CELSIUS".
Wenn das zusätzlich notwendig ist, wie mache ich das?


Vielen Dank für die Hilfe!


Gruß Dominik

**Comment by csuermann** [comment]
Hi @Domi920,

das Umwandeln der Daten für VSH lässt sich z.B. mit einer simplen Funktion realisieren:

![image](https://user-images.githubusercontent.com/10939809/147559913-2cfbd7f2-c078-4fdb-b3a6-142d0f104520.png)

Die Zeichenkette "22.56" wird in eine "Number" mit nur einer Nachkommastelle umgewandelt. Außerdem wird `msg.payload` mit einem Objekt befüllt, das dem erwarteten Input von VSH entspricht.

![image](https://user-images.githubusercontent.com/10939809/147560432-7cb2d253-60ee-446e-a92d-643088f545d0.png)

So sieht das Ergebnis dann im Debug-Node aus:
![image](https://user-images.githubusercontent.com/10939809/147560333-16ad39cf-fff3-4032-b871-ae8ca2af21ec.png)

Hier das obige Beispiel zum Importieren in Node-RED:

```json
[{"id":"0b7b3365455043db","type":"inject","z":"aa8748444995b57a","name":"22.56","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"22.56","payloadType":"str","x":800,"y":1340,"wires":[["4b20690601215e65"]]},{"id":"4b20690601215e65","type":"function","z":"aa8748444995b57a","name":"","func":"msg.payload = {\n        temperature: Number(Number(msg.payload).toFixed(1)),\n        scale: 'CELSIUS'\n    }\n\nreturn msg\n\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":970,"y":1340,"wires":[["77fb40262fc398e5"]]},{"id":"77fb40262fc398e5","type":"debug","z":"aa8748444995b57a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1140,"y":1340,"wires":[]}]
```

**Comment by Domi920** [comment]
@csuermann Vielen Dank für die schnelle Hilfe!
Klappt wunderbar!


Gruß Dominik
