### ISSUE TITLE
Can't install Alexa Skill

### ISSUE THREAD

**Issue by mkcologne** [csuermann/node-red-contrib-virtual-smart-home#121]
"You are not eligible to enable this skill due to geographical restrictions"

I'm in Germany. Is there a trick for that?

Thanks - M.

**Comment by csuermann** [comment]
Hi @mkcologne,

That's strange! Are you sure your Alexa account is set to Germany?

**Comment by mkcologne** [comment]
It becomes stranger:
From the AlexaApp@iPhone I can't install any skill.
(same reason)

If I try via alexa.amazon.com, I can install skills, but if I click on VSH nothing happens and I can only see the Listing:

https://user-images.githubusercontent.com/25418164/147241575-35239819-3247-45fc-af32-2f98a3b0d011.mov

Amazon-Related?

**Comment by csuermann** [comment]
Since I haven't changed anything with regards to the skill listing recently, I tend to believe this must be an Amazon issue.

**Comment by mkcologne** [comment]
Get a closer look there. Happy Holidays!
