### ISSUE TITLE
[BUG] Color Changing Lightbulb not working

### ISSUE THREAD

**Issue by ThetaGamma** [csuermann/node-red-contrib-virtual-smart-home#122]
**Describe the bug**
The color changing lightbulb is not working and throws error "Cannot read property 'hue' of undefined". dimmable lightbulb and switch are working as expected

**To Reproduce**
1. create new vsh device "banane", type switch
2. check connection -> working
3. change type to dimmable
4. give Alexa order to turn on -> {"powerState":"ON","source":"alexa","directive":"TurnOn","brightness":100,"name":"banane","type":"DIMMABLE_LIGHT_BULB","rawDirective"
5. change type to "Color Changing Lightbulb"
6. give Alexa order to turn on -> error message in debug node "Cannot read property 'hue' of undefined", Alexa says "Gerät antwortet nicht"/Device not answering

**Expected behavior**
create some "on"-kind of message

**Environment (please complete the following information):**
 - virtual-smart-home version: 2.13.1
 - Node-RED version: 1.3.7

**Comment by csuermann** [comment]
Hi @ThetaGamma,

I tried to follow your instructions but did not manage to reproduce the problem. Does the issue persist or is it now working on your end, too?

**Comment by ThetaGamma** [comment]
Hi @csuermann ,
yes, it still persists. I tried some other types as "Fan", "dimmable switch" etc - all are working, only the color changing lightbulb is throwing that error. I even created once more a new virtual device to doublecheck: same result there

**Comment by ThetaGamma** [comment]
Well, whatever caused this error - waiting helped. Did not touch the whole system and now it's working. Let's see if the fix is persistent. As my bug couldn't be reproduced, I close this issue.

**Comment by csuermann** [comment]
Hmm, anyways, thanks for reporting back!
