### ISSUE TITLE
ThermostatMode Controller

### ISSUE THREAD

**Issue by filippoadessi** [csuermann/node-red-contrib-virtual-smart-home#124]
Hi, I'm going to develop my own flow to manage my HVACs spread all around my house. I've found impossible using alexa to change the thermostate mode that is displayed in alexa app as a fixed string.

Am I wrong or there are no way to change this param?

All the best
Filippo

**Comment by csuermann** [comment]
Hi @filippoadessi,

You should be able to change the mode to one of these values via voice command or `payload.thermostatMode`:

- AUTO
- HEAT
- COOL
- ECO
- OFF

**Comment by filippoadessi** [comment]
Hi Cornelius,
This is the screenshot from Alexa app. Unfortunately the thermostat param can not be changed and Alexa, even with a vocal command, says “There is no chance do do that “.

I know that I can change it by payload but I need to change it using Alexa interface (because my LG multi V interface is based on Adobe Flash and it’s no longer supported).

You have done a really amazing work! Thank you.

Filippo
Il 23 gen 2022, 10:46 +0100, Cornelius Suermann ***@***.***>, ha scritto:

**Comment by csuermann** [comment]
Hi @filippoadessi,

Github doesn't include file attachments when you reply by email. Hence I cannot see your screenshot.

I just tried the voice commands and they seem to be working fine (at least in German).

**Comment by filippoadessi** [comment]
Here's the screen! Probably I have to do some tuning to let it works.

Best
Filippo

![IMG_4291](https://user-images.githubusercontent.com/31067675/150825122-85d8feca-34b7-453d-a08d-c18c1cc872b9.jpg)

**Comment by csuermann** [comment]
Hi @filippoadessi,
Looks like this is a limitation of the Amazon app 🤷‍♂️
