### ISSUE TITLE
[] device limit reaced! Maximale Geräteanzahl erreicht

### ISSUE THREAD

**Issue by Domi920** [csuermann/node-red-contrib-virtual-smart-home#125]
Hallo,
habe in der letzten Zeit sämtliche Smart Home Geräte & Sensoren Alexa-fähig gemacht.
Jetzt gerade fällt mir auf, dass ein Gerät nicht funktioniert & Alexa meldet dass das Gerät nicht reagiert.
In NodeRed konnte ich bei einigen Alexa-Geräten "device limit reached!" anstatt "online" lesen.

Allerdings würde ich noch ein paar Alexa Geräte benötigen.
Könntest du bitte etwas für mich machen?

1000 Dank im Voraus!

Gruß Dominik

**Comment by csuermann** [comment]
Hi Dominik,

das Geräte-Limit passe ich derzeit nur für [GitHub Sponsoren](https://github.com/sponsors/csuermann) an, die mich beim Betrieb von VSH finanziell unterstützen. Falls Du Sponsor werden möchtest, nenne mir im Anschluss einfach die ersten 10 Zeichen Deiner "Thing-ID".

**Comment by Domi920** [comment]
Hallo,
danke für die zügige Antwort!
Natürlich werde ich gerne Sponsor.
Habe allerdings 2 verschiedene Konten, da bei uns das Obergeschoss & Erdgeschoss "getrennt" sind.
Habe deshalb den Sponsorbetrag erhöht.
Es wäre supernett wenn du beide Konten erhöhen könntest.

Dies wär meine 1. "Thing-ID":
vsht-cce26974-a8

Das die 2.:
vsht-ec800704-d1

Der Nachname in den E-Mail Konten ist der gleiche.

Danke im Voraus!

Gruß Dominik

**Comment by csuermann** [comment]
Hi Dominik,

vielen Dank für Deine Unterstützung! Ich habe das Limit für beide Accounts verdoppelt.

Viele Grüße
Corneliu

**Comment by Domi920** [comment]
Danke auch!
Natürlich helfe ich gerne mit.

Wie viele Geräte können maximal erstellt werden?
Und könnte man - sollte die Anzahl doch nicht ausreichen - die Anzahl weiterer erhöhen?

**Comment by csuermann** [comment]
Amazon gibt ein [Limit](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-discovery.html) von 300 Geräten vor. Melde Dich gerne, wenn Du mit den aktuell konfigurierten 200 nicht auskommst.

**Comment by Domi920** [comment]
Vielen Dank für die Infos.

Wenn der Fall eintritt, wie kann ich dich am besten kontaktieren damit ich keinen neuen Fall öffnen muss?

Gruß Dominik
