### ISSUE TITLE
[FEATURE REQUEST]  Guidelines to avoid MsgRateLimiter problems

### ISSUE THREAD

**Issue by bwims** [csuermann/node-red-contrib-virtual-smart-home#126]
**Is your feature request related to a problem? Please describe.**

I'm updating a temperature sensor every 10 mins.  From about 2100 to when I reboot daily at 0200, I get a handful of rate message limit messages.

**Describe the solution you'd like**
To know the parameters of the limits of continuous updates/interrogation:  E.g. how many times an hour,  whether the limits are pooled between devices, etc.   

It looks like a reboot clears everything, but it's just a guess. After the reboot, which is well after midnight, the count seems to be reset. Confirmation would be good.

It's still a great tool though!

**Comment by csuermann** [comment]
Hi @bwims,

I needed to introduce rate limiting as some users do crazy things with VSH and bombard the backend with requests, which increases my infrastructure bill. The rate limiting mechanism is a bit complex and subject to change. But updating a device's state every 15 minutes at most should be possible.

**Comment by Domi920** [comment]
Now I have to ask one more question.
I have almost all sensors in my home equipped with VSH and the number will increase a little.
However, there are also door sensors & window sensors in it.
Does that mean that the status of the sensor can be wrong if e.g. B. the door is opened and closed more than once in a few minutes?

My temperature sensors send a current temperature value every 2-4 minutes when heating up a room with the help of a fan heater.
Can it also happen that the temperature query does not work or is even wrong?


How would you describe that?

Would it also be possible to make exceptions for sponsors?


Greetings Dominik

**Comment by Domi920** [comment]
@csuermann hättest du schon eine Antwort für das Problem bereit?

Gruß Dominik
