### ISSUE TITLE
[FEATURE REQUEST] Update Temperature Sensor/Thermostat on Demand

### ISSUE THREAD

**Issue by CanyonCasa** [csuermann/node-red-contrib-virtual-smart-home#127]
**Is your feature request related to a problem? Please describe.**
I have an issue similar to issue #126. I have a control loop updating every minute, which introduces a high rate of updating the sensor temperature. (This will expand to more sensors in the future, compounding the problem.) However, I only need to know the current temperature on request.

**Describe the solution you'd like**
Would it be possible to prompt the virtual device to actually read (get, query) the current temperature on demand, i.e. query the device vs just getting the current value from the saved state. Presently, no message gets sent to the sensor when requesting temperature, The query could update the saved temperature state, then make the voice reply. This would eliminate the need to push data constantly when not needed. Perhaps use a parameter to choose between the present push mode or read on request more.

**Describe alternatives you've considered**
Presently using an alternate node-red node type that has other issues. I prefer the node-red-contrib-virtual-smart-home node.

**Additional context**
It would be nice if the temperature sensor and thermostat both supported this capability.

**Comment by csuermann** [comment]
Hi @CanyonCasa,

Just to make sure I understood you correctly: You want to inject msg-objects with updated temperature values into your VSH Sensor/Thermostat _without_ that value being forwarded to Alexa?

I guess that would technically be possible but go against the principal of proactively informing Alexa of local state changes. Hence routines within Alexa (e.g. switch on the light if the temperature drops below 10 °C (I don't know if that's really supported) would no longer work.

**Comment by CanyonCasa** [comment]
Not exactly. I'm not clear on all the mechanics, but all the examples I've seen for interacting between Alexa and node-red seem to only turn things on-off or constantly push data, which can run into rate limits. It seems intuitive to actually read certain sensor data only when asked in cases that have high update rates such as control loops. Maybe its a limitation on the part of the smart home skill or Alexa utterance handling but I have seen other skills that fetch data from a remote source, such as a database lookup.

So I envision a VSH sensor device that receives a message for node-red to process the same way it now receives an on-off msg. Node-red would then react to that message and send the updated/current sensor value, which Alexa would in turn speak back in its answer. This would reduce traffic to simply updating on request rather than constantly pushing data. You could perhaps use some parameter to differentiate the mode of operation between present behavior and this behavior as both modes have utility.

BTW, nice work. I have tried several Alexa node-red nodes and the VSH has the others beat. Thanks for the nice work.

**Comment by csuermann** [comment]
Makes sense. Thanks for the suggestion. I'll look into it as time permits.
