### ISSUE TITLE
Copy / Move vsh connection to another device

### ISSUE THREAD

**Issue by steff75** [csuermann/node-red-contrib-virtual-smart-home#129]
Hallo, ich hoffe es ist ok, wenn ich meine Frage auf die Schnelle in deutsch stelle.

Ich möchte meine in VSH konfigurierte Verbindung mitsamt den virtuellen Geräten von einer Node-RED Docker Instanz (Diskstation) zu Home Assistant mit NodeRED Addon (Einplatinenrechner) kopieren/verschieben.

Wie gehe ich da vor, ohne eine neue Verbindung anzulegen. Im Node-RED Verzeichnis finde ich keine Konfigurationsdatei, die ich z.B. einfach rüberkopieren könnte.

Vielen Dank!

**Comment by csuermann** [comment]
Hallo @steff75,

Theoretisch sollte es möglich sein, Deine VSH Flows zu einem neuen System mitzunehmen. Dazu müsstest Du allerdings auch `flows_cred.json `übertragen und außerdem den Wert von `credentialSecret` aus der `settings.js` Datei. Beachte auch, dass die NodeIDs der VSH Nodes unverändert bleiben müssen, da sie sonst als _neue_ Alexa-Geräte erkannt werden. Ich habe aktuell leider keine Zeit, den ganzen Prozess zu testen, insofern würde ich Dir empfehlen, Dich vorab selbst noch im Node-RED Forum etc. zu informieren.

Viele Grüße
Cornelius

**Comment by steff75** [comment]
@csuermann Danke für die Info. 👍

Ich glaube, ich verschiebe die Migration zum HA Addon noch etwas, da sich der Container auf der Diskstation auch leichter anpassen lässt.

Gruß, Stefan.

**Comment by steff75** [comment]
Ich habe es jetzt einfach mal ausprobiert, da ich dann doch neugierig war.

Also wie du meintest, habe ich den Inhalt der `flows_cred.json` und das `credentialSecret` auf das andere System kopiert.
Dann habe ich einen meiner VSH-Nodes markiert und über das Menü in die Zwischenablage exportiert, damit die ID erhalten bleibt.
Auf dem Zielsystem habe ich den Node dann mittels Import der Zwischenablage importiert und deployed.
Da zu dem Zeitpunkt noch beide Node-REDs aktiv waren, haben sich diese um den VSH-Node gestritten. Also alle paar Sekunden hatte sich der Status zwischen online und offline geändert und umgekehrt auf dem anderen System. Als ich dann mein Ursprungs-NodeRED beendet habe, lief der VSH-Node stabil online auf dem neuen Sytem, ohne in Alexa ein neues Gerät anzulegen.

Somit kann ich bestätigen, dass es auf diesem Weg funktionieren würde :)

**Comment by csuermann** [comment]
Fantastisch. Vielen Dank für's Ausprobieren und Bestätigen :-)
