### ISSUE TITLE
Feature request: generic sensor for data reporting

### ISSUE THREAD

**Issue by averri** [csuermann/node-red-contrib-virtual-smart-home#13]
This is an awesome project because it's very useful and easy to configure.

I would like to suggest another important feature, a **generic sensor** for data reporting. 

Example: in the screenshot below I would like to select a new type called **generic sensor**, which can report data via voice commands.

![image](https://user-images.githubusercontent.com/1898447/102715208-b5c03900-42cb-11eb-9077-acef24300192.png)

In the example above, I could retrieve information from the generic sensor via voice commands:

- `Alexa, get the temperature from the kitchen sensor`
- `Alexa, read the humidity from the kitchen sensor`
- `Alexa, what's the pressure from the kitchen sensor?`
- `Alexa, report the status of the kitchen sensor` (Alexa will read all the values)

The **generic sensor** node have an input that receives a `msg.payload` with an object. This object contains the data to be read:

```json
{
  "temperature": {
     "value": 20.8, 
     "unit": "Celcius"
  },

  "humidity": {
     "value": 66.3, 
     "unit": "percent"
  },

  "pressure": {
    "value": 1.02,
    "unit": "atm"
  }
}
```

It's up to the flow to update the **generic sensor**, it can be done periodically like once per minute, the **generic sensor** will store the last `msg.payload` received and it will report the requested values via voice commands.
  
Alexa should report the measures like:

- `The temperature is 20.8 Celcius`
- `The humidity is 66.3 percent`
- `The pressure is 1.02 atm`

**Comment by csuermann** [comment]
Thank you for your suggestion! I'll consider adding something like that.

**Comment by csuermann** [comment]
Hi @averri,

I wanted to let you know that I've just released v1.14.1 that includes support for virtual "Temperature Sensor" devices.

As the virtual smart home skill is based on Amazon's [smart-home skillset](https://developer.amazon.com/en-US/docs/alexa/smarthome/understand-the-smart-home-skill-api.html), I'm somewhat limited in what's possible. Fortunately, there is an [Alexa.TemperatureSensor interface](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-temperaturesensor.html), which I made use of.

You can set the temperature with an inbound `msg` object like so:
```json
{ "payload": { "temperature": 37.5, "scale": "CELSIUS" } }
```

Alexa will tell you the last value when you ask her `"Alexa, what's the temperature of <device-name>"`

The sensor is not as generic as you suggested, I still hope it'll be useful for you.

Merry Xmas 🎄

**Comment by averri** [comment]
Hi @csuermann, that is amazing, thank you so much!
Yes, it's very useful. I would like to know how to add other measurements like humidity, etc.

**Comment by csuermann** [comment]
Hi @averri,
Unfortunately Alexa does not have any device types that support humidity at the moment, so this is not possible using the Smart Home Skills.
