### ISSUE TITLE
Blinds - setting multiple (5) blinds confuses (?) alexa - asking to operate blind in one room - actually controls blinds in different room.

### ISSUE THREAD

**Issue by bednim** [csuermann/node-red-contrib-virtual-smart-home#131]
**Describe the bug**
Hi, thanks for your work!

I have set up 5 different blinds in node red. All is working fine, opens and closes but when i assign each blind to their respective room (group) in alexa app and I ask alexa to close blinds in that room where I and alexa are at this moment - alexa picks blinds in different room for no reason.

I have renamed 'room blinds' to just 'blinds' for every room - this is same as with the lights, speakers etc etc - as its in the room - it should action that particular device.

Has anyone else got similar problem with alexa? 

I believe this isn't plugins error but simply alexa weird behaviour.

Thanks!

**Comment by csuermann** [comment]
Have you found out more about this problem?

**Comment by bednim** [comment]
@csuermann no, I just call blinds by their name ie bedroom blinds, kids blinds etc etc. Wish I didn't have to but no idea what to do in order to rectify this.
