### ISSUE TITLE
[BUG] Doorbell seems to have stopped responding in Alexa

### ISSUE THREAD

**Issue by bwims** [csuermann/node-red-contrib-virtual-smart-home#132]
**Describe the bug**
Alexa no longer sounds or announces, even if I delete and recreate the device.

**To Reproduce**
1. ... Configure doorbell device
2. ... Discover it in Alexa
3. ... trigger VSH device with appropriate payload
4.  Alexa does nothing.

**Expected behavior**

Alexa should ding the bell, announce someone is at the door

**Screenshots**

**Environment (please complete the following information):**
 - virtual-smart-home version: [e.g. 1.22.4] 2.13.1
 - Node-RED version: [e.g. 1.2.6] 2.2.2

**Additional context**

Not sure how to go about debugging this problem.  Any pointers would be much appreciated!

**Comment by bwims** [comment]
Update:  I worried that there may have been a problem with my specific node, so I created another doorbell, that alexa discovered and configured, and it too fails to respond to a state change of "DETECTED".

**Comment by sysadmin0815** [comment]
same here.
I tested with the example doorbell source event from the repo. also not working.

**Comment by bwims** [comment]
I must say, Alexa developer support must be non-existent unless, I suppose,
you are a huge company who makes smart devices for sale through Amazon.

No time for altruistic Github developers, unless it's something they can
steal (like linux) and incorporate into their expensive gizmos.

The ugly face of capitalism....

**Comment by JulianHi** [comment]
@bwims  since this bug is closed... 
Is there any known workaround? I also have the same problem 😞

**Comment by bwims** [comment]
Yes, but it is complex.

My guess is that Amazon have made considerable changes to their codebase which has stopped VSH from working properly.

If you are willing to subscribe to Nabu Casa for a nominal sum, you should be able to use it to create a virtual doorbell that works.

I am running Home Assistant now.

Because I don't like clouds and subscriptions,   I use a Github project called haaska which enables you to connect to Alexa directly from HA - but there are downsides.

It means opening up your firewall to Alexa endpoints, but there is a good package (which is available on docker) called swag that uses "letsencrypt" and "duckdns" to provide you with an SSL certificate for free, along with an nginx reverse proxy.

There is a fair amount of propeller head work involved, but at the end of it you can use HA to define a device that appears to be a doorbell, which works in the correct way.

My guess is that the project maintainer isn't getting enough donations to make it worth his while to put in the considerable effort required to keep up with the Amazon loonies.

If you are a major geek, I can send you links to a writeup on haaska.  The easy way is to subscribe to Nabu Casa.

B.
