### ISSUE TITLE
New Device quick start guide

### ISSUE THREAD

**Issue by Bagarre** [csuermann/node-red-contrib-virtual-smart-home#135]
I'd like to make a new device for a battery management system (BMS) where I can ask Alexa for the battery's State of Charge, current draw, voltage, charge ready... yada yada

Is there a document to help someone write a new device like this or are the commands/requests driven by Amazon?

This is in support of Victron Venus OS that uses Node-Red for extension.

**Comment by csuermann** [comment]
This seems to go beyond the scope of what virtual-smart-home was made for. Please refer to the [Alexa skill development docs](https://developer.amazon.com/en-US/docs/alexa/device-apis/smart-home-general-apis.html).
