### ISSUE TITLE
Will lose devices after some time - how to debug?

### ISSUE THREAD

**Issue by jayjupdhig** [csuermann/node-red-contrib-virtual-smart-home#136]
Hi there

Configuration:

Node.JS version: v16.14.0
NodeRED version: v1.3.5
OS Version: Raspbian 11 (on Raspi 4 'armhf' platform)

Problem description: After some time (a few hours to a few days, difficult to say) it seems that there are not Virtual Smart Home devices available anymore; after a re-deployment of the NodeRED-flow, it works again - after the Amazon Alexa device said again: "I've found x devices ... "

(In the alexa Web GUI i don't need to do something - neither a device search nor a smart home device history cache clean nor something else...)

So: How to debug that issue? Is it possible to use logs? Do i need to increase the log level? (e.g. from "info" to "debug" or maybe "trace"?)

Thank you very very much for your feedbacks. :-) 

With best regards from Switzerland,
Jan

**Comment by csuermann** [comment]
Hi @jayjupdhig,
Your issue might be related to #93, do you think it's possible that your Raspi got rebooted somehow?
Reg. debugging, you could try to activate the Debug option in the vsh-connection node and observe the console.

**Comment by kosuodhmwa** [comment]
Thank you very much for that very fast feedback!! :-) 

Theoretically it's possible to re-boot the raspi - but not practically.

As a workround, now we have a button called "Reinitialize Alexa" in our smart home software. (So i.m.o. there is NOT reboot necessary - just a NodeRED flow re-publish/re-deploy)

**Now we are able to repair it via that button. But that's no solution for our customers.** And to run that process, e.g. every hour as a cronjob, is also not an adequate solution:

- The alexa device will say 1 time in a hour / every hour: "I've found x devices ... " 
- If the repair cronjob will run on minute 0 (of the hour) but Virtualsmarthome/NodeRED will give up on minute 1 - then you also have to wait for 59 minutes...

**Comment by kosuodhmwa** [comment]
-> https://github.com/csuermann/node-red-contrib-virtual-smart-home/issues/93#issuecomment-1114760232

**Comment by jayjupdhig** [comment]
CITE: **_'When I then move one element, and redeploy they all say 1st initializing and then green icon: online and works like charm'_**

We use the same method... ;-)

**Comment by jayjupdhig** [comment]
So issue can be closed - i.m.o the same as described on https://github.com/csuermann/node-red-contrib-virtual-smart-home/issues/93 ...

**Comment by jayjupdhig** [comment]
('kosuodhmwa' was my other account - i'm sry.)
