### ISSUE TITLE
[BUG] General problem that virtual device sensors cannot trigger routines.

### ISSUE THREAD

**Issue by bwims** [csuermann/node-red-contrib-virtual-smart-home#138]
Virtual devices, doorbell, contact sensors, no longer trigger Amazon Alexa Routines.

**To Reproduce**
Create a virtual sensor
Update it to show its state has changed
Try to use it to start an Alexa routine

**Expected behavior**

The routine should trigger.

**Screenshots**

**Environment (please complete the following information):**
 - virtual-smart-home version: [e.g. 22.13.1]
 - Node-RED version: [e.g. 2.2.2]

**Additional context**

I wonder if the problem / solution described [here](https://amazon.developer.forums.answerhub.com/questions/203317/contact-sensor-doesnt-trigger-alexa-routine.html) on the amazon developer forums could help?

Apparently, the state change as shown on the app does not necessarily represent a ChangeReport, it could be a StateReport.

Possibly amazon have changed the behaviour and are more tightly checking the skill behaviour?

**Comment by csuermann** [comment]
Unfortunately I have no idea why this is no longer working. VSH is sending ChangeReports to Alexa and the skill hasn't been touched in a while.

**Comment by csuermann** [comment]
should be finally fixed now.
