### ISSUE TITLE
Garage Door Interaction question

### ISSUE THREAD

**Issue by turbo2ltr** [csuermann/node-red-contrib-virtual-smart-home#139]
Using the Garage Door virtual device, I can use a sensor to update the node's `msg.payload.mode` to `Position.Up` or `Position.Down`.  When I ask alexa if the garage door is open, she will answer correctly based on the last .`mode `message that was sent to the VSH node.

But if I ask Alexa to close the garage, she says "Closing, hang on".. then a second later says "The garage door is closed".  But it seems she announces it's closed regardless of the actual status.  I would assume she would wait to actually get the `Position.Down` message before announcing it is closed.  Is this a bug or does amazon assume if it got a reply from the (virtual) device that the device will make sure it's closed so it just announces it's closed anyway?

**Comment by csuermann** [comment]
The command to close the garage is already triggering the state change without waiting for the garage to finish closing. As part of the voice interaction I believe Alexa just waits for an ACK from the virtual device. Have you tried to inspect the communication between your Node-RED VSH and the cloud backend?

**Comment by turbo2ltr** [comment]
I've never really dived into the MQTT messages but this would make it appear that the node is replying with a `position down` message right away.

```
27 Jun 05:51:56 - [info] [vsh-connection:XXX] MQTT message received on topic vsh/vsht-XXXX/directive: 
{"directive":
	{"header":
		{	"namespace":"Alexa.ModeController",
			"name":"SetMode",
			"instance":"GarageDoor.Position",
			"correlationToken":"AAAAAAA"
		},
		"endpoint": {"endpointId":"vshd-5XXXXX"},
		"payload":
		{
			"mode":"Position.Down"
		}
	}
}                                                                                                                        

27 Jun 05:51:56 - [info] [vsh-connection:XXXX] MQTT publish to topic vsh/vsht-XXXXXX/changeReport: 
{	"template":"GARAGE_DOOR_OPENER",
	"endpointId":"vshd-XXXXXX",
	"properties":
		[{
			"namespace":"Alexa.ModeController",
			"name":"mode",
			"value":"Position.Down",
			"instance":"GarageDoor.Position",
			"changed":false
		}],
	"correlationToken":"AAAAAAAAA",
	"causeType":"VOICE_INTERACTION",
	"vshVersion":"2.12.0",
	"userIdToken":"amzn1.account.XXXXX"
}
```

The only difference I see is the `"changed":false` turns to `"changed":true` is the previous state of `mode` was `Position.Up`.  In the example above, I asked alexa to close the door but the contact was already closed so the `mode` was already set to `Position.Down`.  But the behavior of her immediately returning that the garage door is closed is the same regardless of the previous `mode` state.
