### ISSUE TITLE
[BUG] Alexa doesn't seem to understand 'medium' for a fan setting.

### ISSUE THREAD

**Issue by flyize** [csuermann/node-red-contrib-virtual-smart-home#141]
**Describe the bug**
I can use this to set a virtual fan to low or high without issue. However, if I say 'medium', she replies that she doesn't know how to set the device to that setting.

**To Reproduce**
1. Alexa, set the fan to medium.

**Expected behavior**
I would expect that she would just continue on as normal, just like she does for low and high.

**Screenshots**

**Environment (please complete the following information):**
 - virtual-smart-home version: 2.13.1
 - Node-RED version: 13.2

**Additional context**

**Comment by csuermann** [comment]
Hi @flyize, 'medium' doesn't seem to be a valid value that Alexa understands for fans. The VSH fan implements the [RangeController interface](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-rangecontroller.html), which supports commands like:

- Alexa, set the bedroom fan speed to 7.
- Alexa, set the fan speed on the bedroom fan to maximum.
- Alexa, turn up the bedroom fan speed.
- Alexa, decrease the fan speed on the bedroom fan by 3.
- Alexa, what's the bedroom fan speed?

Hope that helps!

**Comment by flyize** [comment]
Weird. Until Home Assistant made a change to strictly percentages, the word 'medium' worked. Any ideas why high and low work, but not medium?

**Comment by flyize** [comment]
@csuermann Just circling back on this. Any ideas why high and low work, but not medium?

**Comment by fkhr79** [comment]
Hey @flyize,

can't find the mentioning of "medium" on the linked page. Strange.
Until csuerman didn't implement any [semantics](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-rangecontroller.html#semantics) (and I don't believe he did) the "medium"-command will not work.

**Comment by flyize** [comment]
It's under presets. Just do a CTRL + F for 'medium'.

**Comment by fkhr79** [comment]
Yes, You're right... but - as far as I understand - the presets field is optional and a "medium"-setting not necessarily supported.

**Comment by flyize** [comment]
The docs seem to indicate that if 3 presets were added, it would be mapped to low, medium, and high. And more broadly, Alexa absolutely does understand low, medium, and high implementations for fans. It just doesn't work with VSH right now.

**Comment by cmille34** [comment]
@csuermann Can this be looked at again/more?  Seems like it should work based on these comments.
