### ISSUE TITLE
[FEATURE REQUEST] Output IP Address of the Echo Device being used

### ISSUE THREAD

**Issue by neil1111** [csuermann/node-red-contrib-virtual-smart-home#143]
**Is your feature request related to a problem? Please describe.**
In our home, like many, we have multiple echo devices.  The VSH node does not output the IP address (or other unique identifier) of the echo device being used to initiate the request. This will enable room specific actions based on a generic request without having to configure separate rooms or groups in the Alexa app.  For example, "Alexa, open shades" can include a SWITCH node that determines the room of the echo device and then opens the shades for that specific room. Same for lights, etc.

**Describe the solution you'd like**
Please add an output of the node to include the IP address (or other unique identifier) of the echo device making the request. I have defined static IP addresses for each echo device based on their respective MAC address.

**Describe alternatives you've considered**
The node-red-contrib-amazon-echo includes the IP address as:

> meta.insert.details.ipstring
> Alexa master device IP address.
> Only if meta.insert.by=alexa

**Additional context**
Thank you!

**Comment by csuermann** [comment]
Hi @neil1111,

Unfortunately the AWS Smart Home Skill API doesn't expose such information, as already answered in #58, #70, #115, ...

**Comment by neil1111** [comment]
Hi. Thanks very much for getting back to me, and apologies for not seeing
those other posts.

Do you know how the node-red-contrib-amazon-echo
<https://flows.nodered.org/node/node-red-contrib-amazon-echo>one is able to
access the IP address? Perhaps that can be leveraged here? I realize you
may be approaching this differently, but perhaps a merging of the solutions
can make 1+1=3?

Best,
Neil
