### ISSUE TITLE
[BUG] Not registering devices

### ISSUE THREAD

**Issue by knoopx** [csuermann/node-red-contrib-virtual-smart-home#144]
**Describe the bug**

Can't get any device to register. I'm out of ideas, am I missing something?

**To Reproduce**

1. add skill
2. add virtual device node
3. link account
4. deploy

**Observed behavior**

* alexa does not recognize device (neither by "alexa, discover devices")
* toggling debug makes no difference, no output is generated at all
* going back to the node and opening connection details shows zero devices
* tried re-activating skill with no success
* tried re-linking account with no success

**Screenshots**

![image](https://user-images.githubusercontent.com/100993/185258964-984928d5-7901-4442-a9ee-62434bed6a83.png)
![image](https://user-images.githubusercontent.com/100993/185259049-c7c0422a-7066-4d32-af27-9bc890065de9.png)
![image](https://user-images.githubusercontent.com/100993/185259070-42103930-e1eb-4cc3-a557-303c1cd48a58.png)

**Environment (please complete the following information):**
 - virtual-smart-home version: 2.13.1
 - Node-RED version: 3.0.2

**Additional context**
 
running under hassio

**Comment by csuermann** [comment]
Hi @knoopx!
With debug enabled you should be able to see in the Node-RED terminal (not the browser) what MQTT messages are sent and received. Besides that, did you complete the account linking process in the Alexa app, using the same Amazon account?

**Comment by knoopx** [comment]
@csuermann I think it has something to do with amazon country/region, I have two accounts on both amazon.com and amazon.es but my echo dot is linked to the .es account. Is that a supported scenario? Tried to link via amazon.es/code but doesn't seem to work either. Now checking if I can link my dot to the us account...

**Comment by knoopx** [comment]
I did a factory reset, started over again and after several tries and auth errors on the (browser) console, it succeeded... I have no idea what's going on.

**Comment by csuermann** [comment]
Glad to hear you managed to resolve the issue!
