### ISSUE TITLE
Doorbell Press Anouncements

### ISSUE THREAD

**Issue by ianburton20** [csuermann/node-red-contrib-virtual-smart-home#145]
Node Red v1.3.4. 4th Gen Echo Dot. Virtual device node set to type Doorbell. Alex App set to enable Doorbell Announcements. No announcements sound from Alexa.

**Comment by csuermann** [comment]
Hi @ianburton20,
AWS must have changed the Alexa API which caused the doorbell events not to get processed. Should be fixed now.

**Comment by ianburton20** [comment]
Hi

 

Many thanks for fixing doorbell events.

 

Great if you could incorporate a TTS function – so I could have Alexa speak a short phrase eash time the doorbell is pressed.

 

Thanks again for fixing the events.

 

Ian

**Comment by csuermann** [comment]
That is not a feature Alexa's smart home API supports. But you should be able to achieve something like that by configuring a routine in the Alexa app.
