### ISSUE TITLE
[QUESTION] How to fix "fetching a fresh Access Token failed"

### ISSUE THREAD

**Issue by thohoj** [csuermann/node-red-contrib-virtual-smart-home#149]
When I edit the connection node, I am getting this error:

```
ERROR
fetching a fresh Access Token failed
````

I created a breakpoint in `fetchFreshAccessToken` and inspected the local data:

```json
{
    "refreshToken": "MANYCHARACTERSHERE...",
    "url": "https://api.amazon.com/auth/o2/token",
    "data": {
        "grant_type": "refresh_token",
        "refresh_token": "MANYCHARACTERSHERE...",
        "client_id": "amzn1.application-oa2-client.SOMEHEXCHARACTERSHERE"
    },
    "resp": {
        "error_description": "The request is missing a required parameter : client_secret",
        "error": "invalid_request"
    }
}
```
(I replaced some data because I don't know if these characters stand for sensitive credential data)

How can I fix this? 

For some time I used your backend in parallel with my own. Now I am only using my backend. But I think the problem already existed for a longer time.

**Comment by csuermann** [comment]
Hi @thohoj,

I believe the following steps can lead to this annoying state:

1. Open the VSH connection UI when the saved `accessToken` is already expired
2. The UI obtains a fresh pair of `accessToken` and `refreshToken` using the saved `refreshToken`
3. Close the VSH connection UI _without_ clicking the `Update` button
4. The renewed sets of tokens are **not** saved. The old `accessToken` is still expired but now the `refreshToken` is also invalid.

The only workaround is to create a new VSH connection, going through the account linking process again and then changing all your VSH devices to use the new VSH connection. But this sadly messes up your device configuration for Alexa, e.g. room associations, routines etc.

The good news is that I will soon release a new version of VSH which will eliminate this problem at least for newly created VSH connections by issuing a JWT token that just never expires.
