### ISSUE TITLE
Add Scene in Type

### ISSUE THREAD

**Issue by andreanilorenzo** [csuermann/node-red-contrib-virtual-smart-home#15]
It is possible to add "Scenes" to the Type select ?

**Comment by csuermann** [comment]
Hi @andreanilorenzo, could you please elaborate what you'd like to accomplish with that?

In my home I have configured some routines in the Alexa app that simply switch on certain vsh switches. For example when I say "Alexa, I'm leaving", a "leaving trigger" switch is turned on which triggers a flow in my Node-RED to switch off all lights, arm the alarm system and lock the door once I close it behind me.

**Comment by niklasfink** [comment]
I'd also vote for Scenes as an additional type to be available. Using a switch to trigger actions is more of a workaround than Scenes would be.
Using Scenes as action proxies would also add an additional category for a better overview and wouldn't have a wrong status attached.

**Comment by csuermann** [comment]
Ok, I did some research and believe I could add scene support based on these [docs](https://developer.amazon.com/en-US/docs/alexa/smarthome/provide-scenes-in-a-smart-home-skill.html). I'll look into it shortly.
