### ISSUE TITLE
Can't install new 3.0.x version on Raspbian 10 / NodeJS v16.17.0 / Node-RED v1.3.5

### ISSUE THREAD

**Issue by jayjupdhig** [csuermann/node-red-contrib-virtual-smart-home#150]
Hi 

Can't install new 3.0.x version on Raspbian 10 / NodeJS v16.17.0

1.) After trying update palette (plugin) in Node, i get the message that the update was successful from 2.x.y to 3.0.x

2.) After a browser refresh (http://IP_ADDRESS:1880) i see that it was NOT updated - but it was UNINSTALLED... (??)

3.) Then when i will search to install it again (on currently not installed palettes section), the installation fails:

![1](https://user-images.githubusercontent.com/42765391/191248478-09a4502c-fd3b-4f91-b078-39350caa3a4a.jpg)

![image](https://user-images.githubusercontent.com/42765391/191248516-305dcf01-77ff-4725-bdd1-72edc23627de.png)

4.) When i click on "Show Node Info", i will get redirected to that page: https://www.npmjs.com/package/node-red-contrib-virtual-smart-home

![image](https://user-images.githubusercontent.com/42765391/191248618-91086f42-579f-4303-8077-ca5d4d18c80f.png)

5.) Protocol:

![3](https://user-images.githubusercontent.com/42765391/191248741-06a50112-2f9a-4c8b-adb9-fc0f99cfd257.jpg)

![4](https://user-images.githubusercontent.com/42765391/191248752-135c1c55-ac22-4604-a8d4-260b10b02fc7.jpg)

-> And i also added "production = true" to file ~/.npmrc , then execute "npm config ls -l | grep production" i get that message

`
root@xyz:~/.node-red# npm config ls -l | grep production
npm WARN config production Use `--omit=dev` instead.
; production = null ; overridden by user
production = true
`

(I heard that that parameter "production = true" may solve the problem, but it will not...)

Thanks in advance for your feedback(s)... :-) 

Best regards, Jan

**Comment by jayjupdhig** [comment]
Maybe the problem is the Node RED version i use, v.1.3.5 ?

And another (off-topic) question: It it possible to update Node RED palettes / plugins automatically. (At least if they work...;-))


Best regards, Jan

**Comment by csuermann** [comment]
Hi @jayjupdhig,

You are running a [_really old version_](https://nodered.org/about/releases/) of Node-RED. I recommend you update to Node-RED 3.x before trying anything else.

As far as I'm aware, updating packages automatically has not been built as a feature yet.

**Comment by jayjupdhig** [comment]
Another question regarding the new 3.x version: So i saw, there are now 7 free devices.

Question: What exactly is now commercial - your Node RED plugin or the Amazon Skill (virtualsmarthome.xyz) - so i know, you are not related to virtualsmarthome.xyz - they are both separete...(?)

**Comment by csuermann** [comment]
The limitation of virtual devices for the "Free" plan is not a feature of version 3 but a rather a change that I implemented on the backend. You need v3 if you want to upgrade to the "Pro" plan, though.

This project has nothing to do with virtualsmarthome.xyz.

**Comment by jayjupdhig** [comment]
Now i saw that you are also the developer of the Amazon Skill... ;-)

QUESTION: How and where to order a commercial licence? I can't any "Buy commercial licence" button (or similar) on my Android Alexa App...

**Comment by csuermann** [comment]
You can upgrade to the "Pro" plan from the Node-RED VSH plugin (as of VSH v3.0.0). You'll find the option on the edit dialog of the vsh-connection node:

![image](https://user-images.githubusercontent.com/10939809/191272900-fbabfe50-7437-4c62-afa5-ef95dba24507.png)

**Comment by jayjupdhig** [comment]
Thank you very very much for your fast feedbacks. VSH will also work again (still in free version)

So now i will close the issue :-) 

Best regards, Jan

**Comment by jayjupdhig** [comment]
Now we've bougth a commercial subscription (CEO said "yes" :-)) - seems to work very well! ;-)

Question: How can we get a receipt for the order? We did not received one on the order mail address i*t*o*a*e*a@gmail.com until now. Do we need to wait for a few hours or a few days?
