### ISSUE TITLE
Can't install VSH 3.0.1 on RedMatic 7.2.1 

### ISSUE THREAD

**Issue by EarthSTD** [csuermann/node-red-contrib-virtual-smart-home#152]
I used the previous version of VSH but with the new version it won’t work. Therefore, I did an update to 3.0.1 but the new version wasn’t installed. I did several steps e.g. update RedMatic to 7.2.1, restart HomeMatic, restart RedMatic, reconnected to Amazon but when I install virtual-smart-home I got an error

![220921 VSH install err 1](https://user-images.githubusercontent.com/75027415/191567449-7ac44033-c627-460a-bd06-a1f2892efa70.jpg)
![220921 VSH install err 2](https://user-images.githubusercontent.com/75027415/191567547-84f1ec16-fdf1-42e5-a0f3-d53bfcab4b46.jpg)

**Comment by csuermann** [comment]
Hi @EarthSTD,

I'm sorry to hear you're running into issues! Since the installation seems to be working just fine for Node-RED 2.x and 3.x, I assume this must somehow be related to RedMatic, which I unfortunately have zero experience with.

Which version of Node.js are you running?

**Comment by EarthSTD** [comment]
Thank you very much for reply. Attached some information of the system. I hope you can see what are the reason for the err.


   "redmatic": "7.2.1",
   "nodejs": "14.16.0",
   "@node-red-contrib-themes/midnight-red": "1.4.7",
   "ain2": "3.0.0",
   "node-red": "1.2.9",
   "npm": "7.6.3",
   "node-red-contrib-alexa-home-skill": "0.1.19",
   "node-red-contrib-alexa-remote2": "3.10.4",
   "node-red-contrib-boolean-logic-ultimate": "1.0.57",
   "node-red-contrib-ccu": "3.4.2",
   "node-red-contrib-combine": "1.8.1",
   "node-red-contrib-german-holidays": "1.0.1",
   "node-red-contrib-huemagic": "4.2.2",
   "node-red-contrib-netatmo": "0.3.0",
   "node-red-contrib-netatmo-dashboard": "0.5.2",
   "node-red-contrib-sun-position": "1.2.4",
   "node-red-contrib-virtual-smart-home": "3.0.1",
   "node-red-dashboard": "2.28.1",
   "node-red-node-email": "1.8.3",
   "node-red-node-pushbullet": "0.0.19",
   "node-red-node-rbe": "0.4.0",
   "node-red-node-tail": "0.3.2",
   "redmatic-led": "1.1.0",
   "redmatic-webapp": "0.3.1"

**Comment by csuermann** [comment]
"node-red": "1.2.9" is very old. Is there a way for you to update that? This might be the root cause.

**Comment by EarthSTD** [comment]
Yes, that’s right. RedMatic is an old version. There is a new version available (3.0.2). Therefore I will look how I can update the version. I also read several comments that the support for RedMatic isn’t as good as support for other systems e.g. Home Assistant. Several users moved to that system. What is your recommendation? What system do you prefer? Should I change the system?

**Comment by csuermann** [comment]
I don't have any experience with RedMatic. Personally I run Home Assistant for connecting my Z-Wave sensor, Node-RED for automations, and of course VSH for voice controlling my devices.

**Comment by EarthSTD** [comment]
OK. That’s also my goal for the next few days to migrate to Home Assistant. I have to order memory for my Sinology to run Home Assistant in a virtual Machine. Nevertheless, I will also update the old system. I keep you informed whether the update solve the problem.

**Comment by EarthSTD** [comment]
Meanwhile I did an update via SSH (command line) for my HomeMatic CCU3 to NodeRed 3.0.2 and it solves the problem (Have a look at https://github.com/rdmtc/RedMatic/issues/550#issuecomment-1228423177). After the update virtual-smart-home was installed and I’m also able to implement the virtual-smart-home components in my RedMatic flows. Nevertheless, I’ll move the next few days to Home Assistant.
Thank you very much for your supporting me.

**Comment by csuermann** [comment]
Thanks for reporting back, @EarthSTD! Great that you managed to update Node-RED. And good luck with your planned migration to Home Assistant!
