### ISSUE TITLE
Temperature Sensor partially working

### ISSUE THREAD

**Issue by macadamer** [csuermann/node-red-contrib-virtual-smart-home#154]
On asking Alexa "What is the outside temperature", the response is "I'm not quite sure what went wrong". The IOS app shows the temperature correctly. The example pizza oven temperature flow has the same problem.

This used to work properly until near the end of the previous vsh version, and continues to be not completely functioning with 3.0.1.

I have un- and re-linked my vsh account with no change, unsurprising I suppose since a test switch still functions, as does a very brief Thermostat test, at least Alexa reported that it had been set to Auto as requested.

**Comment by csuermann** [comment]
Are you on the "Pro" plan yet?

**Comment by csuermann** [comment]
Nice! Next question: Have you enabled the "retrievable" option for your device?

**Comment by macadamer** [comment]
The missing step here is that Node-RED must be restarted after going through the Edit connection stage. I should have thought of that... All working now, and thanks for the nudge, and the rapid response.

I'll close this issue, and perhaps it will help others.
