### ISSUE TITLE
Version 3.01 Suddenly my VSH system is offline.  I need to Upgrade to PRO!!!  Pretty angry.

### ISSUE THREAD

**Issue by Purclewan** [csuermann/node-red-contrib-virtual-smart-home#155]
Cornelius, very very naughty.  Suddenly pulling the plug without prior warning on long term users who have bought you coffee and left great reviews.   

Don't get me wrong, I really appreciate your hard work and will probably upgrade once I know how much it costs (No information has been given how to do this) but to wake up to a cold house because all my thermostats have gone off line and only find out what has happened after a hour of investigating my node red code is really poor and not in the spirit of Open Source.

I understood this was a Open Source and free Node and was happy to commit using it within my own code.   Had I known you were going to suddenly and without warning decide to just switch off users and start charging I might have used something different.  As it is, I have spent hours building a complex Heating and Home Automation system around the VSH Node and now suddely it no longer works unless I go PRO.  It would not be quite so bad but I can't find any details of what PRO costs or how to upgrade to it.  

I repeat, I am happy to support hard working programers and prepared to contribute to costs but just switching off is really not the right way to get support.

Purclewan

**Comment by csuermann** [comment]
Hi @Purclewan,

I'm really sorry to hear the recent update of VSH was causing trouble on your end!

I did inform about the upcoming changes [here on GitHub](https://github.com/csuermann/node-red-contrib-virtual-smart-home/issues/148) and tried to explain my reasons for introducing a paid plan. The alternative would have been to shut down VSH entirely, which you probably wouldn't have liked either.

I also did send out an announcement to all GitHub sponsors and to the kind people who donated via PayPal in the last year, granting them a 100% discount for at least 6 months of the "Pro" plan. Please let me know if I accidentally skipped you here!

Once you update to VSH version 3, you'll find the option to subscribe to "Pro" quite prominent in your VSH nodes. Pricing is 12 EUR per year for up to 200 virtual devices.

Best,
Cornelius

**Comment by Purclewan** [comment]
Thanks Cornelius,

I have now paid for a pro subscription. 
Just to be clear, I have no problem with you charging subscribers for such a great piece of work especially if you have to pay for the Amazon service and the price is very reasonable.   

The VSH node has been an enormous help to me and I was a very early adopter.   I did donate via Paypal but was a very early subscriber so I guess you missed me in your announcement and I dont check github that regularly.  It was a bit of a shock when my entire systen suddenly stopped working just as I was leaving for a holiday.  Anyway, it is working again on my PC allthough I'm still struggling to update my headless PI cluster and backups to the latest Version 3.01.  For some reason (probably a Node_Red issue) they will not update.  I will keep at it.

Many thanks.

**Comment by csuermann** [comment]
Thank you so much!

**Comment by Purclewan** [comment]
Cornelius,

Hope you can help, I am still struggling to get my raspberry Pi cluster 
to update.

As way of explanation, I do most of my day to day programming including 
Node-Red on a Win10 PC.  I have the latest LTS version NR running on the 
PC and I keep backups of all my NR flows including from my Pi cluster 
which is on the same network on the PCs backup drive.

Today I managed to get the VSH node running again on the PC and it 
accepted my subscription without an issueand updated my flows.

I then tried to update my Pi Cluster, 3 Pi's which run on my network as 
the main system, a development system and a backup system.

None of the three Pi's would allow me to upgrade to the latest VSH 3.01. 
   After updating Node.JS,  NPM and updating to the very latest version 
of NR (2.2) I managed to get one of the Pi's to upgrade to VSH 3.01.

When I go to the connection TAB it asks me to add (link) this computer 
to my Amazon account which I do and it accepts and displays my 
subscription as active with Current Plan PRO and lists my Registered 
Devices.   However,  when I then click update to return to Edit virtual 
device node the Plan is listed as UNKNOWN and I cannot get any further.

So, my backup flow on my PC seems to work but my Pi flow doesn't.

Any ideas.

Kind regards

Michael.

**Comment by csuermann** [comment]
Hi Michael,

"UNKNOWN" is listed as your current plan on the _vsh-device_ page when no MQTT connection is established to the VSH backend yet. However, the plan info on the _vsh-connection_ page is fetched via HTTP and as long as it shows "Pro" there, everything has been set up correctly.

Does restarting your Node-RED flows fix this display issue? Or do you even experience degraded functionality on your Pi? Perhaps you could elaborate a bit more what you mean by "I cannot get any further".

Best,
Cornelius

**Comment by csuermann** [comment]
Hi Michael,

I suspect Alexa not recognising your devices comes from the device duplicates with identical names. Any idea where they come from? Could it be that you have multiple vsh-connection nodes configured? If so, please delete the stale ones so that you end up with only one connection and all your vsh-devices connected to it. Then also delete the ones with shaded background as this indicates they're connected through a different vsh-connection. The duplicates might also originate from your backup system if it ever came online and uses different node IDs since they are part of the vsh identifiers.

Hope that helps!

Best,
Cornelius

**Comment by Purclewan** [comment]
Hi Cornelius,

Again, just after an update my entire system has gone offline.  I can no 
longer log into my account and all instances of VSH now report as 
invalid.  I cannot re-establish connection.  I am on the latest update 
and I have rebooted the RPI.
Confess I am getting frustrated by the constant problems.  This software 
just worked perfectly before the recent upgrades now it seems very flaky.




I do get a message telling me to update to the latest version of VSH but 
I am already at the latest version.

**Comment by csuermann** [comment]
Hi Michael,

I'm really sorry to hear back from you with such negative news!

Please help me understand what's going on on your end!

- Which VSH version do you currently run?
- What do you mean by "I can no longer log into my account"? Where do you try to log in? What does not work? A screenshot might be helpful.

Let me assure you that I'm working hard to make VSH even more stable and reliable. Thanks for your help!

**Comment by Purclewan** [comment]
Cornelius,  I'm not sure I got the reply email address correct so I'm 
resending this email.  Sorry if I have sent it twice.


-------- Forwarded Message --------
Subject: 	System down again. Now almost back up again.
Date: 	Sun, 9 Oct 2022 23:20:29 +0100
From: 	Michael ***@***.***>
Reply-To: 	***@***.***
To: 	Cornelius Suermann ***@***.***>



Cornelius,

Huge thanks for the prompt reply.

The version of VSH I am running is 3.0.4.  Running on Raspberry Pi4 with 
OS Buster.  This Pi has another Pi on the same network which acts as a 
daily backup but with all flows disabled. My Node Red is at version v3.0.2

I am running a large home automation system on the PI which is split 
into several flows(projects) involving Tasmota, Zigbee and OpenHasp 
display devices.  These in turn share Global Variables many of which are 
taken from and used by VSH Devices particularly Thermostats, Temperature 
sensors and Switches.

What happened earlier today was that I was updating a flow that had 
several VSH thermostats in it.  I was not updating a VSH node but 
modifying some global variables in a different part of the flow.

When I pressed "Deploy" all my VSH devices suddenly dropped offline and 
the red triangle appeared above the VSH nodes and I got the Deploy 
message "The workspace contains some nodes that are not properly 
configured:".

Checking, I found that some of my VSH nodes within this and several 
other flows had lost their Thing ID and their Amazon Connection 
details.  The Connection Box showed "Add New Connection".  This is what 
I meant by logging in to my account. My previous connection details had 
disappeared as had my thing ID.  I tried re-entering my previous 
connection name but it did not help.

Since sending my last email, I have deleted the complete flow and 
reloaded a recently saved backup.   This asked me to log into Amazon to 
re link my account which I did and then by going through each VSH node 
in turn, pressing "Update" on the "Edit connection node" page then 
"Done" on the "Edit virtual device node" page it brought the VSH nodes 
one at a time back to life.

Unfortunately is also duplicated all my Devices in the Registered Device 
box with the duplicates shaded.  I have since gone through and deleted 
all the duplicates and the system now seems to be almost back to where 
it was before.

I say almost, two new things, in some flows, my VSH devices are shown as 
Plan "Pro" and in others Plan "UNKNOWN" although apparently visible and 
working fine.  I also noticed the  flows showing Plan "PRO" have a 
different Thing ID to those showing Plan "UNKNOWN".  This may have 
happened as a result of me reloading my backup flow.

So, situation at present is:  My flows are working once again but 
showing two different Thing IDs.  If you can help to resolve this it 
would be a great help.  Also, I'm still not sure why the original flow 
suddenly failed without warning when I tried to deploy an updated flow.

Incidently, you asked for screen shots in your email.  I did attach 
inline screen shots but they may have been filtered out by the github 
mail system.  I will resend them as attachments.

I really appreciate the work you are doing and do believe you want to 
make it stable and reliable.  Its just frustrating that up until the 
recent changes the VSH node was super reliable and that had given me the 
faith to merge it fairly comprehensively into my flows and in particular 
into the heating automation section I have built to control my eight 
zone underfloor heating and Heat Pump system.  As you can imagine, I 
need this to run reliably during the winter.  I can fallback to my 
original system but without the additional OpenHASP display features and 
the Alexa Control VSH gives me.


Kind regards

Michael.

**Comment by Purclewan** [comment]
Cornelius,

Today as I was working through my flows is suddenly occurred to me that 
I might be missing something obvious so I rechecked

It might just be coincidence but it seems that the problem of Plan PRO 
showing in some VSH devices whilst showing Plan UNKNOWN in others could 
be down to me having my project split into multiple flows within a 
single Node Red instance.

When I checked,  in just one flow the Plan was listed as PRO on all VSH 
devices but in all my other flows on the same Node Red instance VSH 
devices were showing Plan UNKNOWN.

Could it be that when introducing the PRO version of VSH there is 
something that prevents multiple flows from registering VSH in more than 
one flow?

Michael.

**Comment by Purclewan** [comment]
Thanks for the prompt reply Cornelius, I was one of the early adopters and did donate but I'm not too worried about paying 12 euros for a year.  I was just a bit angry as my system went offline just as I was leaving for a short holiday and caused me some serious head scratching when I least needed it.  I had upgraded to 3.01 but can't see any option to go Pro. Not sure what I am doing wrong but I will check again tomorrow as I am just back from my holiday. Vielen Dank. Sent from my phone-------- Original message --------From: Cornelius Suermann ***@***.***>Date: Fri, 23 Sep 2022, 22:30To: csuermann/node-red-contrib-virtual-smart-home ***@***.***>Cc: Purclewan ***@***.***>, Mention ***@***.***>Subject: Re: [csuermann/node-red-contrib-virtual-smart-home] Version 3.01 Suddenly my VSH system is offline.  I need to Upgrade to PRO!!!  Pretty angry. (Issue #155)
Hi @Purclewan,
I'm really sorry to hear the recent update of VSH was causing trouble on your end!
I did inform about the upcoming changes here on GitHub and tried to explain my reasons for introducing a paid plan. The alternative would have been to shut down VSH entirely, which you probably wouldn't have liked either.
I also did send out an announcement to all GitHub sponsors and to the kind people who donated via PayPal in the last year, granting them a 100% discount for at least 6 months of the "Pro" plan. Please let me know if I accidentally skipped you here!
Once you update to VSH version 3, you'll find the option to subscribe to "Pro" quite prominent in your VSH nodes. Pricing is 12 EUR per year for up to 200 virtual devices.
Best,
Cornelius

**Comment by csuermann** [comment]
Hi Michael,

Thanks a lot for taking the time to explain what happened on your end!

Your vsh-connection node suddenly disappearing and leading to the red triangles on your vsh-virtual-device nodes was _most certainly not_ caused by VSH itself. Perhaps the Node-RED logs include a hint at the problem?!

As inconvenient as it was, all the troubles you had to go through since then (creating a new vsh-connection, re-connecting it to all your VSH devices, clearing up duplicates etc.) were all a consequence of the vsh-connection getting lost and not related to any recent update of VSH. That doesn't make it less annoying for you but at least I feel a bit less bad about it ;-)

"UNKNOWN" is shown as the plan on the device page if the device is currently not connected to the VSH backend, e.g. if the corresponding vsh-connection is not configured or the flow is not deployed yet. But since you mentioned different ThingIDs showing up, which essentially uniquely identify a vsh-connection, it seems that you somehow did end up with _multiple_ vsh-connections. That would be contrary to your earlier statement "_The Connection Box showed 'Add New Connection'_", which suggests that at that time you had zero vsh-connections.

Not sure how to interpret this but you seemed to have a somewhat inconsistent state in your Node-RED instance.

By the way, I believe GitHub strips any attachments when you reply via Email. But inserting screenshots via the GitHub UI should work.
