### ISSUE TITLE
[FEATURE REQUEST] lifetime option

### ISSUE THREAD

**Issue by terafin** [csuermann/node-red-contrib-virtual-smart-home#156]
Pro Plan - Lifetime

**Describe the solution you'd like**
Rather than a subscription per year [which I'm not a fan of subscriptions], could we have some lifetime option? Would be happy to pay $100-200+ for it.

Thanks for an awesome product!

**Comment by csuermann** [comment]
Hi @terafin,

Your offer is quite flattering, but at this point I don't feel comfortable offering a lifetime option as this would require a long-term commitment from me which I realistically cannot give. (I don't have any plans to abandon VSH anytime soon, especially with the new "Pro" plan revenue now hopefully paying the AWS bills. But I would feel really bad if something happened that leads to the discontinuation of VSH and then people having to claim back their money or feeling betrayed.
