### ISSUE TITLE
Got 7 devices - still prompts 'device limit reached'

### ISSUE THREAD

**Issue by bednim** [csuermann/node-red-contrib-virtual-smart-home#157]
Hi,

I have just found out regarding subscription option but I have counted that I only got 7 devices therefore will not be signing up to PRO plan yet, but still I am getting error - device limit reached.

Is there any chance this could be looked at?

Thanks!

**Comment by csuermann** [comment]
Hi @bednim,

Could it be that you have multiple vsh-connections configured? Perhaps there are some stale devices counting against the free quota. You should be able to see all your registered devices on the "connection" page, with devices belonging to a different vsh-connection showing up with gray background.

**Comment by bednim** [comment]
Thank for quick response @csuermann,

It shown only 7 devices on connection page but I indeed had one extra 'stale' node deploying which was taking space. 

This now works fine.

Thank you

**Comment by csuermann** [comment]
Great to hear you got it all working!
