### ISSUE TITLE
device limit reached

### ISSUE THREAD

**Issue by atifan** [csuermann/node-red-contrib-virtual-smart-home#158]
Hi. I use this palette in node-red since a few months without any problems. But since today it does not work, my SmartHome is not working now :(. I have devices which are connected but I have a lot of devices where it says "device limit reached!".
Is this a bug or why that happens now? And how can I fix it?
Thank you very much.

![image](https://user-images.githubusercontent.com/58658412/192137187-1b20c4c8-8b49-4714-88a3-3d371d92ffe7.png)

**Comment by csuermann** [comment]
Hi @atifan,

Looks like you're running into the limitation of the "Free" plan which got introduced early this week. You can upgrade to the "Pro" plan after updating to the latest version of VSH.

**Comment by atifan** [comment]
Hi tanks for fast answer. I updatet my palette in nodered to latest version 3.1. But how and where can i make a subscription? I only can find my Alexa Skill "virtual smart home". But there is no option for any subscription.

**Comment by csuermann** [comment]
You will find the subscription options on the vsh-connection page.

**Comment by dumdiedum** [comment]
@csuermann I can't find the subscription option in my connection dialog.

**Comment by csuermann** [comment]
Have you updated to VSH 3.0.1?

**Comment by dumdiedum** [comment]
yes

**Comment by csuermann** [comment]
Hmm, that's strange then!

Could you kindly provide screenshots of the edit screens for one of your virtual devices (vsh-virtual-device) as well as for the Connection node (vsh-connection).

Also, what output do you see when you open http://{YOUR_NODE_RED_BASE_URL}/icons/node-red-contrib-virtual-smart-home/version.txt in your browser? (Replace {YOUR_NODE_RED_BASE_URL} with whatever you see in your Node-RED URL before "/#flow", e.g. "http://127.0.0.1:1880/icons/node-red-contrib-virtual-smart-home/version.txt")

**Comment by dumdiedum** [comment]
Nevermind, browser cached old version of htmls. Thank you for your help!

**Comment by softwarecrash** [comment]
hey there, i have the same problem, after upgrading, i would subcribe, but i have no credit card, no other option to pay avaible?

**Comment by csuermann** [comment]
If you happen to have Google Pay or Apple Pay you can use those by opening the link to the checkout (Stripe) on your mobile phone. That seemed to have worked for some other users.

**Comment by softwarecrash** [comment]
> If you happen to have Google Pay or Apple Pay you can use those by opening the link to the checkout (Stripe) on your mobile phone. That seemed to have worked for some other users.

unfortunately i dont have one of them, only a idea, add a paypal method?
a question, why 7 devices? 
i only have 10 devices, i think it would be not much more, so a smaler plan was interessting, or a lifetime license?

**Comment by bigverm23** [comment]
just switched to a paid subscription just like that, huh?

**Comment by csuermann** [comment]
@softwarecrash, unfortunately Stripe doesn't have a PayPal payment option. Could you please send an email to vsh@csuermann.de and state the email address you're using for VSH as well as your "Thing-ID"? I'll see what I can do.

@bigverm23, I had to make a decision whether to shut down this project or to introduce a paid "Pro" plan. Announced here (#148) and shared with all recent sponsors.

**Comment by softwarecrash** [comment]
> @softwarecrash, unfortunately Stripe doesn't have a PayPal payment option. Could you please send an email to [vsh@csuermann.de](mailto:vsh@csuermann.de) and state the email address you're using for VSH as well as your "Thing-ID"? I'll see what I can do.

thanks, i have send yopu a mail.
just a idea, everyone that use VSH uses amazon, so a amazon pay option is a usable way?

**Comment by bifbaf** [comment]
Sorry but I am little bit lost here I can't find any introduction to update node red to the pro version.
I am using node red in Home Assistant OS. Can someone tell me where I have to enter payment method and that kind of stuff
Thank

**Comment by csuermann** [comment]
Hi @bifbaf, I'm not sure how Home Assistant OS works, but assuming it has a full Node-RED instance embedded, you should be able to update node-red-contrib-virtual-smart-home to version 3.0.1 from the Node-RED palette manager. You'll find the option to update to the "Pro" plan on the edit screen of your vsh-connection node.

**Comment by bifbaf** [comment]
Thanks man, just updating the palette has done the trick.

**Comment by peterfido** [comment]
It is a bit cheeky. I have sponsored csuermann and now he demands money, if you have more than seven devices to control.

**Comment by csuermann** [comment]
Hi @peterfido, I have [explained why this was necessary](https://github.com/csuermann/node-red-contrib-virtual-smart-home/issues/148) and have given sponsors free access to the Pro plan for at least 6 months. Please let me know if I accidentally skipped you.

**Comment by peterfido** [comment]
I will change to the echo nodes. My "sponsoring" was at 27.11.2021.
My comment was "Prima Projekt" or so.

**Comment by csuermann** [comment]
Thanks for your quick reply, @peterfido. I indeed received a donation on that date from the email address jo*********way@gmx.de. Is that you? I did sent a promotion code to that email on September 19 2022 with 100% discount for 12 months.

**Comment by peterfido** [comment]
Yes, it´s me. There is unfortunately no E-Mail in inbox or Spam-Folder.

**Comment by csuermann** [comment]
That's strange. Let me resend it from my personal email address.
