### ISSUE TITLE
Virtual Device == inititializing

### ISSUE THREAD

**Issue by MrThiemann** [csuermann/node-red-contrib-virtual-smart-home#161]
hey,
I have purchased your Pro Subscription.
I really like what you've done so far.
Surely there is a way to control your smart home with ALexa, but I'm always happy to support something like that!!
Unfortunately I haven't had access since then.

All my nodes show: initializing

What also surprises me is the "plan": UNKNOWN

can you help with this?

<img width="508" alt="Bildschirmfoto 2022-10-07 um 20 36 12" src="https://user-images.githubusercontent.com/54147030/194626762-9032ba42-e0b3-445e-8786-2a443b7886c9.png">

<img width="523" alt="Bildschirmfoto 2022-10-07 um 20 37 22" src="https://user-images.githubusercontent.com/54147030/194626787-b3e19f5d-a7a7-4024-b828-a9de06e744bf.png">

**Comment by csuermann** [comment]
Hi @MrThiemann,

Sorry to hear you're experiencing issues with VSH!

Do you by any chance have more than 1 vsh-connection configured?

Could you please activate the debug option, restart Node-RED and share the output of the Node-RED CLI?

**Comment by MrThiemann** [comment]
hy, no i only have this one account.
debug log sounds good. I will do that.

**Comment by csuermann** [comment]
I checked the backend database and you seem to have only one connection indeed. That's good. But what is strange is that there seem to be 0 devices associated with your account although from your screenshot it looks like there should be 33.

When did VSH last work for you? My suspicion is that your system was offline for some time and your server-side certificates got garbage-collected. If that's the case you should be able to fix everything by deleting your current vsh-connection, creating a new one (go through account linking again), and associating your 33 vsh-virtual-device nodes with the new vsh-connection.

**Comment by MrThiemann** [comment]
It's been a few days since everything worked properly here.
I will then create a new vsh connection.

**Comment by MrThiemann** [comment]
Perfect! Dissolving the connection did the trick!
Now I can also see my PRO plan directly.
Thank you for your support!

**Comment by csuermann** [comment]
Glad to hear it's working fine now. Thanks for reporting back!
