### ISSUE TITLE
[FEATURE REQUEST] shutter node type

### ISSUE THREAD

**Issue by brunialti** [csuermann/node-red-contrib-virtual-smart-home#162]
I cannot find any shutter type in the node type

**Comment by csuermann** [comment]
Does the "Blinds" device type not work for you?

**Comment by brunialti** [comment]
Shutters accept open/close/stop commands. Blind does not accept "stop" command, that is Alexa prompts back "unavailable functionnforvX device".

**Comment by csuermann** [comment]
Ah, I see. As far as I can tell, Alexa doesn't seem to support "stop" commands as part of the smart-home API. Do you know any Alexa skill that supports it?

**Comment by brunialti** [comment]
No I do not.
