### ISSUE TITLE
[BUG] Cant register new devices in Pro-mode

### ISSUE THREAD

**Issue by Heurigl** [csuermann/node-red-contrib-virtual-smart-home#163]
Dear Cornelius,

first of all thanks for your brilliant work!!!

**Describe the bug**
I use Node-RED within HomeAssistant, updated VSH to Version 3.0.4 and registered to Pro.
When creating new virtual devices they show up with a green "online" in NodeRed, but don't get listet as "Registered Devices" within the Connections (and also not in the Alexa-App).
I use ~120 devices, so that device-limit should not be the problem.

Could you please help?
Thank you very much!

**Environment (please complete the following information):**
 - virtual-smart-home version: 3.0.4
 - Node-RED version: 3.0.2 (Within HomeAssistant 2022.10.3)

**Comment by csuermann** [comment]
Hi @Heurigl,

Thanks for your kind words!

Could you please enable the "Debug" option for your vsh-connection, restart Node-RED and share the output of the Node-RED CLI with me? Feel free to send it to vsh@csuermann.de as it might include sensitive data.

Your existing 121 devices work fine, though?

Best,
Cornelius

**Comment by Heurigl** [comment]
Thanks for your quick reply!

I did send the log to the given E-Mail address.

There are actually 4 VSH-Devices, that don't work (all of them added recently):
- Rollladen Küche
- Display Rolllden Küche
- Alle Rollläden Stopp
- Rollladen Küche Stopp

All the others work like charm! :-)

Kind regards:
Rainer

**Comment by csuermann** [comment]
Hi @Heurigl,

Thanks for sending over the debug logs!

Something strange seems to be going on: When you restarted Node-RED, all your vsh-virtual-device nodes for some reason got new node IDs. When VSH starts up, it fetches a list of registered devices from the server and compares that with your local list of devices to figure out which devices got deleted (and should get removed from Alexa) or added/changed (and should be pushed to Alexa for discovery).

When you restart your Node-RED flows (or Node-RED altogether), do you regularly receive a push notification about new devices discovered on your Alexa app?

Is there anything special in your setup that would explain why your nodes get new IDs when you restart Node-RED?

**Comment by Heurigl** [comment]
Hi @csuermann ,

not sure for me how to read the logs, but I restarted Node-RED serveral times, Text-compared the debug output and can't find any differences (except of the timestamp).
I did send three logs as eyamples go the given eMail-address - in hope that things might become clearer... :-/

No: When restarting Node-RED I don't get any Alexa-Notifications regarding newly discovered devices - they all stay pretty the same in Alexa-App. Also linked vsh-Entities in Alexa-Routines keep untouched.

My Setup is a usual/official "HomeAssistant-OS" on a Raspberry Pi 4 (4GB), where NodeRed comes as an AddOn within HomeAssistant. In my eyes there's no Special-Configuration in NodeRed, just straight "out of the box".
Other installed AddOns are:
- AdGuard Home
- Let's Encrypt
- Mosquitto Broker
- Samba-Share
- Visual Studio Code Server
- Tailsale VPN
- Terminal & SSH

Also problems just came up with device-limit reached in Free Version. Even with Updating VSH (first 3.0.4, now 3.0.6) problems stayed the same.

What makes me wonder:
I was thankfully upgraded to 200 devices in "old" vsh. VSH3 accepts 200 devices (regarding to the ChangeLog). In my case (under the "registered Devices" in Node-RED) it now says "The PRO plan allows up to 300 devices". 
Could there be a problem in this direction?

Do you have any Ideas for me what else to try?
Could a complete clearing off all Node-RED flows (after exporting), and then importing them again be worh giving a try?

Greets:
Rainer

**Comment by csuermann** [comment]
Update: After exchanging more emails with @Heurigl I have the suspicion that the problem might stem from an exceeded AWS IoT Shadow DB quota due to a large number of VSH devices. Hence I just requested a quota increase. In the meantime connecting some vsh-virtual-device nodes via a second vsh-connection could be a cure.

**Comment by csuermann** [comment]
Great! Thanks for reporting back!
