### ISSUE TITLE
Follow up on previous conversations.

### ISSUE THREAD

**Issue by Purclewan** [csuermann/node-red-contrib-virtual-smart-home#166]
Cornelius,  my last email on the 12th Oct seems to have gone unanswered.  Perhaps you did not recieve it?

In it I detailed the problems I was having with PRO PLAN and Plan unknown messages.

To keep things simple, I have copied below the last couple of paragraphs from that email with the two questions I asked

Questions are:-

Is there any way of getting rid of the duplicated thing ID and getting back to one ID across all my flows? 

Does the Pro plan allow me to work on multiple machines with one Thing ID especially bearing in mind that I clone my RP to a backup RP regularly and that I also have a windows 10 machine on which I keep multiple revision versions of work I am doing?

Additionally and relating to that last question, could you confirm what I suspect, that the ProPlan only allows VSH devices in one single flow and one instance of Node Red on one machine and that a seperate PRO PLAN would be needed if I wanted  to back up my flow to a second instance of Node RED on a different machine.

Thank you.

Michael.

**Comment by csuermann** [comment]
Hi Michael,

I'm sorry if I missed a message from you. The last conversation I'm aware of is [this one](https://github.com/csuermann/node-red-contrib-virtual-smart-home/issues/155#issuecomment-1274986510), dated October 11. Was there anything after that? If so, where did you send it to?

Let me try to answer the questions you copied today:

> Is there any way of getting rid of the duplicated thing ID and getting back to one ID across all my flows?

Yes, you should be able to delete all but one vsh-connection nodes using the "Delete" button in the Node-RED UI.
![image](https://user-images.githubusercontent.com/10939809/199321360-0dab9677-88b8-4b9d-9634-07c1147dd67a.png)

> Does the Pro plan allow me to work on multiple machines with one Thing ID especially bearing in mind that I clone my RP to a backup RP regularly and that I also have a windows 10 machine on which I keep multiple revision versions of work I am doing?

As long as you can ensure that only one of your Node-RED instances is active at any time, this could work. So you could create a full backup of your Node-RED flows from machine A, switch A off, import it on machine B and activate it there. As far as VSH is concerned, the backend wouldn't know the difference. However, if A and B were active simultaneously, their connection would get disconnected and re-connected every few seconds and the whole system would not work reliably any more. Also, if your VSH nodes would not have exactly the same (Node-RED) node IDs, they would be discovered as new Alexa devices, creating an unmanageable mess. Mind you, these limitations were always there and are unrelated to the PRO plan.

> Additionally and relating to that last question, could you confirm what I suspect, that the ProPlan only allows VSH devices in one single flow and one instance of Node Red on one machine and that a seperate PRO PLAN would be needed if I wanted to back up my flow to a second instance of Node RED on a different machine.

Your PRO plan is tied to the email-address / Amazon account you used during account linking. You can use the same account on more than one machine and they would all get the PRO features. However, the total number of virtual devices across all your machines remains limited to 200.

Best,
Cornelius

**Comment by Purclewan** [comment]
Thanks Cornelius,

My problem was that I had three flows in one Node Red instance.  

In one flow everything worked as it should with PRO PLAN shown. In the second two flows the VSH node were all showing PLAN UNKNOWN and had a different Thing ID despite all flows being tied to the exact same email address.  Weirdly, if I cut a working node showing PLAN PRO from the first flow and pasted into either of the second flows it immediately changed to PLAN UNKNOWN.

However, today I updated VSH to the most recent version 3.0.6  and when I powered back up all my flows were showing PLAN PRO.   No idea what happened but I can see that I do still appear to have two different Thing ID's.   Despite this it seems to be working fine.  

On a different note, I am now getting a debug message for my Thermostats as follows:-

 "MsgRateLimiter: dropping THERMOSTAT:vshd-53690219b0ca6853:PHYSICAL_INTERACTION  

I'm assuming it has something to do with the rate at which the msg.payload.temperature is updating my VSH thermostats (every 2 min) to read and display the actual room temperature although I can't see how that would need to interact with Alexa other than when (if) I ask Alexa the current room Temperature. 

As always, thanks for your help.

**Comment by Purclewan** [comment]
Quick update on my last message.  I deleted all the VSH nodes in my first flow then rebuilt them identical to before.  This time when I deployed the flow the new VSH nodes picked up the same Thing ID as the two other flows so all is now as it should be with only one Thing ID across all my flows.  Seems to be working perfectly now. 

Now I just need an answer to the "MsgRateLimiter: dropping THERMOSTAT:vshd-53690219b0ca6853:PHYSICAL_INTERACTION" message.

**Comment by csuermann** [comment]
Hi Michael,

Glad to hear you got it working again!

Regarding the rate limit: The current implementation of VSH forwards local device state changes to the Alexa servers which can be problematic if there are too many changes.

I plan to change that behaviour like you suggested. Until then you could ensure to inject less messages, e.g. by polling your thermostat sensors only ever 15 minutes or so. Or you could only inject a new value when the temperature has changed significantly enough.

**Comment by Purclewan** [comment]
Thanks for the update Cornelius, It was quite a job but I have rewritten and replaced the code updating all my thermostats both target and actual temperatures.  They are now only updated on change.  The reason it was complicated is that I have several ways of updating and reading my various Room Thermostats.  
1) Using Alexa control via VSH.  (allows control when away from home).
2) Using a Web Based control Panel set up within Node Red.
3) By using Open HASP on Lambon displays around the house.

Each of these has to share all updates with the Lambon displays which display real time information and have a control slider to adjust (set) room temperatures.

Seems to be working now.  Fingers crossed.
