### ISSUE TITLE
[BUG] VSH offline/unavailable after 2-3 hour power outage.

### ISSUE THREAD

**Issue by markbajaj** [csuermann/node-red-contrib-virtual-smart-home#167]
Hi

This has been working fine for me up until a power outage the other day. Now none of my nodes work.

The VSH connection in node red is showing as PRO (correct), but each node is UNKNOWN. I have tried deleting the connection in node red and then adding a new (going through the pairing process) and then adding that connection to the nodes but still no luck. 

I have also disabled and relinked the skill in my Alexa account.

Is there any way I can reset the connection totally as I am sure some stale connection is cached somewhere.

Thanks

Mark

**Comment by csuermann** [comment]
Hi @markbajaj,

To debug this issue, could you please switch on the "Debug" option for your vsh-connection and send the output of the Node-RED CLI after restarting Node-RED to vsh@csuermann.de? I'm happy to take a look.

**Comment by markbajaj** [comment]
Hi Cornelius,

Thanks for getting back to me - I think i have resolved this - it wasn't VSH, it seems that my docker host was having sporadic DNS issues (probably part of the outage and the complicated way i do name resolution). I basically unlinked the Alexa skill again, deleted the connection in NR, recreated the connection in NR then relinked in Alexa and they all came online :)

Thanks for your prompt response and sorry for disturbing you on a Saturday :)

Have a great weekend

**Comment by markbajaj** [comment]
fixed - thanks

**Comment by csuermann** [comment]
Thanks for reporting back! Have a nice weekend, too!
