### ISSUE TITLE
Temperature Sensor reporting '0' all the time

### ISSUE THREAD

**Issue by markbajaj** [csuermann/node-red-contrib-virtual-smart-home#168]
**Describe the bug**
Hi Cornelius,

I am now having difficulty with a temperature sensor. I have looked through past issues and cannot see the solution.

I am on the Pro Plan with the latest version of VSH on Node Red v 3.0.2 (running in Docker)

I have an input of a Temperature sensor from Home Assistant -> VSH Node but the temperature is always zero:

<img width="571" alt="Screenshot 2022-11-05 at 15 52 46" src="https://user-images.githubusercontent.com/22906610/200128670-85b5b002-8321-4c55-b8db-a86ce9358618.png">
<img width="476" alt="Screenshot 2022-11-05 at 15 53 02" src="https://user-images.githubusercontent.com/22906610/200128688-b4267195-773a-495d-be99-56217feb4bf5.png">
<img width="495" alt="Screenshot 2022-11-05 at 15 53 47" src="https://user-images.githubusercontent.com/22906610/200128706-1ad27c84-ae29-48a8-81d3-d561b609bd28.png">
<img width="369" alt="Screenshot 2022-11-05 at 15 54 13" src="https://user-images.githubusercontent.com/22906610/200128714-5cb8be38-6dbf-4d5b-ae79-9e70b619529d.png">

Am I missing something as I have tried all combinations and it still reads zero. If I inject msg.payload.temperature from an inject node to a random value it will take that and then not clear it

Thanks again,

Mark

**Comment by csuermann** [comment]
Hi @markbajaj,

You are probably not feeding the right payload into the VSH node.

Here is an example:
```json
[{"id":"f74375bf3684bec7","type":"vsh-virtual-device","z":"3156dd60.366d12","name":"pizza oven","topic":"pizza/temp","connection":"","template":"TEMPERATURE_SENSOR","passthrough":false,"x":1530,"y":460,"wires":[[]]},{"id":"c43559ab94f203ff","type":"inject","z":"3156dd60.366d12","name":"measured temp = 220.5 °C","props":[{"p":"payload.temperature","v":"220.5","vt":"num"},{"p":"payload.scale","v":"CELSIUS","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":1270,"y":460,"wires":[["f74375bf3684bec7"]]}]
```

Hope that helps!

**Comment by markbajaj** [comment]
Cracked it! Thanks Cornelius!

I went away for a short while and then used a change node to move the msg.payload to msg.payload.temperature and all good in the hood!

<img width="651" alt="Screenshot 2022-11-05 at 19 25 16" src="https://user-images.githubusercontent.com/22906610/200137548-613c46de-3872-4ea3-aef1-ddb9922a2fea.png">

<img width="475" alt="Screenshot 2022-11-05 at 19 24 01" src="https://user-images.githubusercontent.com/22906610/200137555-af90ce54-0733-445d-a6db-55525164e48b.png">

<img width="302" alt="Screenshot 2022-11-05 at 19 25 46" src="https://user-images.githubusercontent.com/22906610/200137558-d8c2963f-fc80-4fc7-9cad-0c95ecec144a.png">

Thanks for your help. And thanks for the node - I am slowly moving away from Nabu Casa as this runs so much faster and i have more control over it.

Mark

**Comment by csuermann** [comment]
Glad you managed to get it working! Thanks for reporting back.
