### ISSUE TITLE
detailed source-device-info (payload.source)

### ISSUE THREAD

**Issue by fkhr79** [csuermann/node-red-contrib-virtual-smart-home#169]
Hey Cornelius!
Thanks for this great interface! Pro-Plan works well and very stable! :)

I'd like to realise a reporting for some smart-home-stats (e.g. temperature, solar-production, ...) by alexa command.
Means, I'd like to say "Alexa, report on xyz" and the Alexa-Device, which received the command, answers.
To do this, I thought about using a virtual smarthome device (type scene) which is speech-activated.
Unfortunatly the output (payload.source) contains "device" or "alexa" only.
Perhaps it's possible to deliver the device-ID or device-Name too?

Thx!

**Comment by karlzmir** [comment]
Actually I, too, am in favor of this kind of improvement :)
Here I'd like to show another example of practical case :
Unless i'm mistaken, alexa is able to adapt to a generic command, taking into account the room in which an equipment is located, but only for lights.
"Turn off the lights" will affect only the lights in the same room of the listening alexa device.
But saying "close the blinds" and expecting blinds of the actual room to close is not a thing. You'll get "different devices ar called blinds, which one do you want ?"
But with "source.ip" or similar info, it would be possible to set a generic "blind" device on the NodeRed canevas, and set a different node path regarding which alexa device got the request.
This is just an example.

In any case, great work with VSH, Pro-Plan works great, happy to support !

**Comment by csuermann** [comment]
Unfortunately Alexa's smart home API doesn't provide any hint about the device that received a voice command. Hence it is currently technically impossible to add this feature to VSH.

Grouping echo devices and VSH devices is the best one can do to somewhat solve this problem. Opening the right blinds this way should actually work, but you probably need to rename your blinds to something that doesn't confuse Alexa, @karlzmir.
