### ISSUE TITLE
Feature Request HEX color with a leading "#"

### ISSUE THREAD

**Issue by nicedevil007** [csuermann/node-red-contrib-virtual-smart-home#17]
Hey @csuermann,

would it be possible to add the leading "#" for the color_hex key.

Node-Red could then show the color directly in the debug log and we don't have to add this charackter infront with a following seperate node.

Thank you very much for your awesome support so far!!!!!

Example for ZigBee2MQTT:
![image](https://user-images.githubusercontent.com/17103076/103831423-578da700-507c-11eb-9dcc-cd57628843c6.png)

**Comment by csuermann** [comment]
Thanks for the suggestion, @nicedevil007!

Makes sense to me. But it would be a breaking change. Anyone voting 👍 or 👎 this request? Any ideas to make the change less disrupting for users who learned to live without the #?

**Comment by csuermann** [comment]
After thinking about this I came to the conclusion to treat this as a bugfix, not as a new feature.

The "color_hex" attribute of "color changing light bulbs" is now always prefixed with a '#'-sign.

This change might break the setup of a few users but should be easy to fix.
