### ISSUE TITLE
[Bug? / Feature request] No interactive adjustment of light color from within the Alexa app.

### ISSUE THREAD

**Issue by Sylvan86** [csuermann/node-red-contrib-virtual-smart-home#170]
### description:
I have several virtual devices of the "_Color Changing Light Bulb_" type. I can turn them on/off, dim them, set the color and color temperature via Alexa voice command.
However, in the device tab in the Alexa app, I only have the option to turn the device on and off and set the brightness in fixed 20% steps. A color selection is not possible although the device features "_color_" and "_color temperature_" are displayed in the device properties. With color light devices, which are created with the adapter [alexa-home](https://github.com/mabunixda/node-red-contrib-alexa-home) instead, i have a color selection, a temperature selection and a slider for the brightness within the Alexa app.

I am now undecided whether these options come from the Alexa app itself or through the respective service provider. 
Depending on that, the inclusion of a color, a color temperature selection and a brightness slider would either be a bug or a feature request.

### Environment:
- Node-Red v3.0.2
- node-red-contrib-virtual-smart-home v3.0.6
- Alexa-App: iOS and Android
- plan: "Pro" (In the device settings, "Free" is still displayed as the plan. In the configuration node, however, "Pro" is displayed and i can also operate more than 7 devices. - maybe this is another bug)

**Comment by csuermann** [comment]
Hi @Sylvan86,

Thanks for reaching out!

I could reproduce the issue and it looks like the Alexa app only displays color and color temperature controls if the device has been configured with the "Retrievable" option enabled. Now, to enable this, you need to be on the "Pro" plan, which you already are, but we need to sort out why "FREE" is still being displayed on the device page.

- Do you have more than one vsh-connection configured by any chance?
- Does the correct plan get displayed after restarting your flows or Node-RED?

**Comment by Sylvan86** [comment]
> * Do you have more than one vsh-connection configured by any chance?

No

> * Does the correct plan get displayed after restarting your flows or Node-RED?

Embarrassingly, I actually did not perform this.
After the Node-Red restart, "Pro" is displayed and I can also select the retrievable option.
Now the color selection also appears correctly.

The riddle is solved!

**Comment by csuermann** [comment]
Thanks for reporting back!
