### ISSUE TITLE
[BUG] Error provisioning failed

### ISSUE THREAD

**Issue by nicolas971PB** [csuermann/node-red-contrib-virtual-smart-home#172]
Hi

I try to link my account to Amazon, but i've always the same error : "Error provisioning failed"
I try many times but no luck.
Thanks for your help.

**Comment by csuermann** [comment]
Hi @nicolas971PB,

Sorry to hear you're running into issues!

In order to help you, I'd need more information.

- What is the exact error message you're getting?
- What are the steps leading to it?
- Which version of Node-RED and VSH are you using?

Best
Cornelius

**Comment by nicolas971PB** [comment]
> Hi @nicolas971PB,
> 
> Sorry to hear you're running into issues!
> 
> In order to help you, I'd need more information.
> 
>     * What is the exact error message you're getting?
> 
>     * What are the steps leading to it?
> 
>     * Which version of Node-RED and VSH are you using?
> 
> 
> Best Cornelius

Hi Cornelius,
There is no bug at all.
I didn't not read the full manual, and did not enable the Amazon's skill.
Sorry.
Nicolas

**Comment by csuermann** [comment]
Ah, that explains it! Thanks for reporting back!
