### ISSUE TITLE
Blinds: what to say for raising the blinds in german

### ISSUE THREAD

**Issue by gnome4711** [csuermann/node-red-contrib-virtual-smart-home#173]
I wonder how to raise the blinds in german!
Lowering works fine. The german words would be "hinunter" (not common) "runter", "herunter", "herab". Those words work fine.
Bit it seems there is no way to raise. "hoch" doesn't work at all "ich weis nicht wie ich diese Einstellung mit [device name] durchführen soll".
"hinauf" works like runter, "herunter, "herab" (lowering).

any ideas

**Comment by csuermann** [comment]
"Alexa, öffne/schließe Rolladen" works for me.

**Comment by gnome4711** [comment]
ok I see. In my case I use shutters. shutters are raised or lowered. is it possible to add shutters to the  device list to be raised and lowered? No one would say öffne/schließe Rollladen.  This would go to jalousien!

**Comment by csuermann** [comment]
Alexa doesn't seem to have specialized support for [shutters vs blinds](https://developer.amazon.com/en-US/docs/alexa/smarthome/get-started-with-device-templates.html#blinds). But I just tried "Alexa, fahre Rolladen hoch" and "Alexa, fahre Rolladen runter" and it worked as it should.

**Comment by tt2g89** [comment]
I do and it works fine for a long time. Also you can work with percentage to let them drive to a specified value, i.e. 80%.
