### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EarthSTD** [csuermann/node-red-contrib-virtual-smart-home#174]
[201202 Alexa VSH Probleme.pdf](https://github.com/csuermann/node-red-contrib-virtual-smart-home/files/10141519/201202.Alexa.VSH.Probleme.pdf)

**Describe the bug**
Unfortunately I can’t connect a temperature sensor or thermostat device to Alexa. I still see only waiting for virtual smart home (see also attached file).

**To Reproduce**
1. Drag a node to the working space and put all the settings to the node
2. Deploy the changes
3. ...

**Expected behavior**
Normally I can see the controls in the Alexa App. Unfortunately the app is waiting for virtual smart home.

**Screenshots**
File with screenshots is attached .

**Environment (please complete the following information):**
 - virtual-smart-home version: 3.0.6
 - Node-RED version: 3.0.2

**Additional context**
I have more than 40 devices connected and this problem happens the first time. A reboot of Node Red doesn’t solve the problem. Also deleting and reapplying the devices wasn’t a solution. Can you tell me, how I can solve this problem?

**Comment by csuermann** [comment]
Hi @EarthSTD,

Thanks for reaching out. Did you enable the "retrievable" option on your thermostat VSH node?

**Comment by EarthSTD** [comment]
Great. That solves the problem. It works as expected. Thank you very much for the quick support.

**Comment by csuermann** [comment]
Thanks for reporting back!
