### ISSUE TITLE
Power state not working properly on alexa

### ISSUE THREAD

**Issue by ugariello** [csuermann/node-red-contrib-virtual-smart-home#175]
Good day,
i have a strange fault on Amazon Alexa app.
When i select a device from the list i change the status from OFF to ON but the status of the icon during approx. 4 seconds. After do this, the light is on and if i wanna switch off the light i have to press 2 times i can see the status in off but is not showed.
Thank you for your support

https://user-images.githubusercontent.com/34243943/207584179-6d926c31-93a6-4dd0-98b3-8d3f420c4dad.mp4

**Comment by csuermann** [comment]
Hi @ugariello,

Thanks for reaching out! Have you enabled the "retrievable" setting for your VSH light in Node-RED?

**Comment by ugariello** [comment]
dear csuermann,
thank you so much for your reply.
Unfortunally, the "retrievable" setting and to unlock need to pay. My question is: why was working 'till 1 week ago? Is there any options to restore for free?
Thanks for your support
Best regards
Ugo

**Comment by csuermann** [comment]
If your device was connected for a long time, it might not yet have picked up the changes that came with the introduction of the Pro plan.

**Comment by Jhonyboy72** [comment]
I have a similar issue, my icons also lost the state after a few seconds when i use the App. I have ProPlan and enabled the "retrievable" option.

Iam sending eg. the State from my PLC Boolean TRUE to {"powerState":"ON"} to the VSH-Device. But nothing happens.


                "t": "change",
                "p": "payload",
                "pt": "msg",
                "from": "true",
                "fromt": "bool",
                "to": "{\"powerState\":\"ON\"}",
                "tot": "json"

Is something wrong with this?

**Comment by csuermann** [comment]
@Jhonyboy72:

Could you please capture the inbound msg that your vsh-device receives with a _Debug_ node and share the output here?

Also, you might find the examples that ship with VSH helpful. They can be imported via

`Node-RED -> Import -> Examples -> node-red-contrib-virtual-smart-honme`

**Comment by Jhonyboy72** [comment]
No No Dont get me wrong. All the VSH-Nodes are working fine but the State in the App is Always "not true" or "not false". 
Its not possible to see if a light is ON or OFF.

**Comment by camphamp** [comment]
First, let me say "thanks!" for your great work and letting us try for free. I want to keep status in sync for several UI's: node-red dashboard, Apple HomeKit and Alexa. I am testing your node for the Alexa piece.

I have the same issue using a SWITCH object as ugariello reported wit his BULB (also with plug and bulbs for me, too).

The device appears in Alexa perfectly as the correct device type. However:

1) When I hit "ON" in the app, it signals through to Node-Red and the status of the "ON" button is illuminated, but for only 4 secs (like initial video in this thread).

2) When I inject a payload with { "powerState" : "ON"} to the virtual node the Alexa App switch buttons remain off.

My pi4 and NR installation is 2 months old, so using the latest versions. I use all the node's default settings (i.e. no boxes are checked). I can test more if you let me know what you would like.

Here is the info you requested previously from the Jhonyboy72:

![vitual-device](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/25261819/32f24026-6635-416d-a7db-4b58abc04d7a)

**Comment by csuermann** [comment]
Hi @camphamp,

Thanks for reaching out!

In order for Alexa to be able to retrieve the state of your vsh devices, you need to be on the PRO plan and switch on the "retrievable" option of your vsh device.

**Comment by thermseekr** [comment]
Hi there!

Thank you @csuermann, I had the same question, and hadn't noticed the
retrievable option in the vsh devices. Problem solved.

Em dom., 2 de jul. de 2023 às 05:43, Cornelius Suermann <
***@***.***> escreveu:

**Comment by scobby** [comment]
@csuermann @camphamp 
i have the same problem. I am on pro and have the retrievable option activated.
When i click "on" in the alexa app, its "on", after 4 seconds without interaction the state in the alexa app changes to nothing selected.
How does alexa retrieve the state from node red?
