### ISSUE TITLE
[BUG] Devices aren't answering anymore / License status unknown

### ISSUE THREAD

**Issue by tt2g89** [csuermann/node-red-contrib-virtual-smart-home#176]
**Describe the bug**
Since this morning the devices aren't working anymore. They're still listed in the Alexa App, but the answer is for all the devices: "XY antwortet nicht, bitte überprüfe die Netzwerkverbindung und Stromversorgung des Geräts."
When I try to control it via the App, it says the server does not respond.
Restart of NR-container and afterwards of the whole Raspberry has been performed.
My Pro-Status is only visible in the account settings, when I have a device node opened, it says Plan: UNKNOWN
Pro-Feature is disabled, too at the moment, so I guess, it has to do with the unclear licensing status.
Debugging is enabled at the moment, so you can have a look at it - Thing ID ends with: e6edd89809da

**To Reproduce**
1. not clear to be honest.

Screenshots:
![image](https://user-images.githubusercontent.com/42508561/208443219-054185a1-d09b-44d9-9033-0d011ed35810.png)
![image](https://user-images.githubusercontent.com/42508561/208443407-584ba958-c73f-408d-a3a6-8e3961c81876.png)

**Expected behavior**
Devices work as expected.

**Environment (please complete the following information):**
 - virtual-smart-home version: 3.0.6
 - Node-RED version: 3.0.2

Thanks a lot in advance for your support.

**Comment by csuermann** [comment]
Hi Thomas,

Thanks for reaching out!

From what you describe it looks like your Node-RED instance is not connected to VSH's MQTT endpoint. Since I didn't change anything it could just be an AWS glitch or even a network issue on your end.

- Which status do your VSH nodes show?
- Is there by any chance any helpful output in your Node-RED logs?
- Unfortunately I couldn't look up your Thing by it's suffix. Could you please send me your full ThingId via email to vsh@csuermann.de ? 

Thanks a lot!

Best,
Cornelius

**Comment by tt2g89** [comment]
Hey Cornelius,

- The nodes do not show any error, if you mean that. Except that no status.

- 9 Dec 15:28:42 - [info] [vsh-connection:abc@xy.de] skipping ChangeReport - no properties changed
19 Dec 15:28:43 - [error] [vsh-connection:abc@xy.de] version check failed! Cannot read properties of undefined (reading 'status')
- ThingID sent via mail.

Best regards,
Thomas

**Comment by tt2g89** [comment]
Forget that, as you wrote it was on my end... DNSMasq killed the DNS resolution because of misconfiguration.
Sorry for the disturbance and merry christmas!

**Comment by csuermann** [comment]
Hi Thomas,

Thanks for reporting back! Glad to hear you could locate the problem and resolve it!

Happy holidays!

Cornelius
