### ISSUE TITLE
[FEATURE REQUEST] Generic Usage Sensor

### ISSUE THREAD

**Issue by ThetaGamma** [csuermann/node-red-contrib-virtual-smart-home#178]
Hi @csuermann 

I'd like ask Alexa to tell me the remaining range of my electric car (eg: "Alexa, what is the range of my Fiat?" -> "Your Fiat has 156km left"

**Describe the solution you'd like**
As far I understand, this might be implemented by using the [Alexa.InventoryUsageSensor Interface 3](https://www.developer.amazon.com/en-US/docs/alexa/device-apis/alexa-inventoryusagesensor.html). As Input I'd use an existing value e.g. from IOBroker.
This object could also be used as a generic output of any given value. (I like the example of remaining coffee pads)

**Describe alternatives you've considered**
currently I use a flow with input from IOBroker for the range, create a new msg Object (msg.payload = "Der Fiat hat noch eine Reichweite von " + msg.payload + " Kilometern";" and pass it to an Object from "node-red-contrib-alexa-remote2-applestrudel" to say the result. Downsite of this solution, that the answer always comes from one device, no matter which echo device you asked. (--> low WAF ;) )

**Comment by csuermann** [comment]
Hi @ThetaGamma,

Thanks for the neat suggestion!

Wouldn't be [InventoryLevelSensor](https://www.developer.amazon.com/en-US/docs/alexa/device-apis/alexa-inventorylevelsensor.html) even be more fitting for your use case?

**Comment by ThetaGamma** [comment]
Much better, you‘re right! It even has the option of defining individual units for the count object

**Comment by ThetaGamma** [comment]
I still think this would be a nice Feature (comment to remove stale label)

**Comment by csuermann** [comment]
In the attempt to integrate support for Inventory Level Sensors, I discovered that the reported levels cannot be queried through Alexa or the Alexa app, making them essentially impractical. Apparently, Alexa implemented Inventory Sensors to facilitate automated reordering of supplies (Amazon Dash) rather than to display actionable information.
