### ISSUE TITLE
Feature Request: Filter Output by [directive]

### ISSUE THREAD

**Issue by nicedevil007** [csuermann/node-red-contrib-virtual-smart-home#18]
Good morning @csuermann,

was struggling with a command to only set the brightness for a bulb/light.
If the directive is set to `SetBrightness` your node will send all color objects what is not neccesary.

That leads to always turn my bulbs to red if I only wanted to change the brightness.
Same could be done for `SetColorTemperature`, `TurnOn`, `TurnOff`. Brightness should be included because some bulbs need a brightness setting.... or sometimes without brightness the transition wouldn't be applied.

`{"powerState":"ON","brightness":100,"colorTemperatureInKelvin":7000,"lightMode":"temp","color":{"hue":0,"saturation":1,"brightness":1},"source":"alexa","directive":"SetBrightness","name":"Licht im Schlafzimmer","type":"COLOR_CHANGING_LIGHT_BULB","color_rgb":[255,0,0],"color_hex":"#FF0000","color_cmyk":[0,100,100,0],"color_lab":[53,80,67],"color_xyz":[41,21,2]}`

![image](https://user-images.githubusercontent.com/17103076/103878067-32c61d80-50d6-11eb-83de-5b5205596906.png)

Sure no problem to fix this by user with a node function, but I guess it isn't neccessary to respond an object that isn't wanted/needed at this point or?

**Comment by csuermann** [comment]
Well, the node always emits its entire current state. If you use two distinct voice commands to first set the color to red and then adjust the brightness to 50%, the color will still be red but dimmed to 50%. That's by design. Expecting the light to show a different color after just adjusting the brightness would be counter-intuitive, I think.

I see two ways to work around this:

1. inspect the "directive" attribute to check whether you need to adjust the brightness (SetBrightness) or color (SetColor) of your physical light.
2. feed state changes that do not originate from Alexa to the node as incoming msg object. This way the node's state will always be in sync with the actual state of the physical light.

**Comment by nicedevil007** [comment]
Mhhh, I think the most hubs/zigbee adapters work the same as if you set a bulb f.e. to blue and you turn it off and then just send a command to turn it on again, it will take the last known state without having to send the color again, maybe I'm wrong for others but that is how zigbee2mqtt works and phoscon as well.

As I told you, no problem to fix it after your node with inspecting the directive, was just a question if that can be possible or if that makes sense :)

Just an other question: Can you track what Echo device did send the command? that would be JUST awesome! Standing in a room with an echo device and I just say "Turn on the light" and it will only turn on the light where I am standing right now...

**Comment by csuermann** [comment]
That's precisely how VSH behaves as well: You set the color to blue, turn it off and when you turn it on again, the color is still blue.

Maybe I'm missing your point here, but the goal of VSH is to expose virtual devices that can be controlled via Alexa, in accordance with the official Alexa smart home skillset.

Amazon doesn't expose the device a command was spoken to, but at least for lights you can still accomplish what you want by putting the echo device and the VSH virtual device into the same room in your Alexa app. As long as your VSH device is a light, you can instruct Alexa to "turn off lights" and she will switch the lights off only in that room.

**Comment by nicedevil007** [comment]
Ok wait, here an example of what happens to me:

I started a scene from zigbee2mqtt that is saved there. 2 bulbs of 4 in my living rooms turns violet and pink f.e. the other 2 stay off.
Now I say: "Alexa set the brightness of my living room to 30%".
Your node now sends the color "#FFFF00" (I guess the color from its last activation over Alexa itself and not from 3rd party nodes).

So maybe a simple solution for both worlds would be to have an option or a checkmark to wether your node should rely on alexas saved stuff or only sends the values for its used directive?

**Comment by csuermann** [comment]
v1.18.0 adds support for a "diff" switch. When activated, the outbound msg object will only contain attributes that were updated by the most recent update event (either by Alexa or via an inbound msg).

![image](https://user-images.githubusercontent.com/10939809/104104899-07e0f280-52ab-11eb-8771-2a792f662191.png)

Hope this helps!

**Comment by nicedevil007** [comment]
Thank you a lot!
