### ISSUE TITLE
[FEATURE REQUEST] Entertainment Device - Remote Video Playback

### ISSUE THREAD

**Issue by spamoom** [csuermann/node-red-contrib-virtual-smart-home#180]
Hello,

In order to achieve "Alexa, play Peppa Pig on Snug TV" which passes through to node red and lets me do some automations for my 3 year old 😂

I believe this is done using the RemoteVideoPlayer API: https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-remotevideoplayer.html

**Comment by jeffersantoss** [comment]
On the current version, how can I send a Play/Pause command to Alexa and process an action based on that command?
