### ISSUE TITLE
[FEATURE REQUEST] Source Device Name

### ISSUE THREAD

**Issue by spamoom** [csuermann/node-red-contrib-virtual-smart-home#181]
This might already be possible and I'm just blind, but it'd be super helpful to know which Alexa device triggered the request. 

Scenario: I'd like to create a device called "TV" that responds to commands by seeing which Alexa called it and action the request on the appropriate TV

**Comment by fkhr79** [comment]
unfortunately it seems to be not possible (at the moment) > see #169 (and perhaps other issues as well)

**Comment by spamoom** [comment]
Ah what a shame, thanks for the link 👍
