### ISSUE TITLE
a Question because I do not understand a thing

### ISSUE THREAD

**Issue by SlashGIP** [csuermann/node-red-contrib-virtual-smart-home#182]
Hi, 

maybe I just dont get it. 

I put a virtual "light" in here called "light1". With this virtual "light1" I want do control a physical light which is connected via MQTT called "lightphysic".

If I put in a node "light1" Alexa find it and with debug I can see, that I have the full control of this virtual "light1". Everything works. "dimm the light to 30%" -> works. But now comes my question and I absoloutly do not understand this one. How can I force the physical light "lightphysic" with the virtual one "light1" ? 

I want to say to Alexa "dimm the light to 30%". Alexa will give the command to "light1" and now? Every example I looked at has an Inject with an explicit % like 60% oder 50% but always needs an Inject to start. 

I hope I could explain my problem here. In Germany we say "ich stehe auf dem Schlauch."

 I saw, in the Issue with the shutters, that this should work. But how? 

Thx a lot

**Comment by csuermann** [comment]
Not sure if I really understood your problem, but you would have to connect the virtual light with an MQTT node, either directly (if the payload coming out of the vsh node is already in the right format for your physical light), or via a change node or function node to massage the data before passing it on to MQTT.

If this didn't help, please post a screenshot and/or example flow illustrating your problem.

**Comment by csuermann** [comment]
Hi @SlashGIP,
Have you been able to make progress?
