### ISSUE TITLE
[BUG] SyntaxError: Unexpected token '.' (line:602)

### ISSUE THREAD

**Issue by ChocoTonic** [csuermann/node-red-contrib-virtual-smart-home#184]
**Describe the bug**
Hard to know what the bug is because I haven't changed anything since it broke

**Screenshots**

**Environment (please complete the following information):**
 - virtual-smart-home version: 3.0.7
 - Node-RED version: 2.1.3

**Comment by csuermann** [comment]
Hi @ChocoTonic,

Do you know which file the SyntaxError occurs in?

Also, which Node.js version are you running?

**Comment by ChocoTonic** [comment]
I'm not sure how I can identify the file the error occurs in

this is what I'm currently seeing
![image](https://user-images.githubusercontent.com/41702116/216917468-dcd42e67-d2f4-4bdf-8dc5-0c565c5266ea.png)

I thought it could be the Node.js version but I updated it to v18.14.0 and it's still encountering the same issue

**Comment by ChocoTonic** [comment]
I do see this as well when I try to add a new vsh connection when it hasn't done it before yesterday

![image](https://user-images.githubusercontent.com/41702116/216918319-aa04fba4-2824-42c2-b0c0-93775c944aa4.png)


![image](https://user-images.githubusercontent.com/41702116/216918281-37f9d8f2-3928-4667-8033-47caab12cc50.png)

**Comment by csuermann** [comment]
Thanks for providing additional info. Are you saying it used to work and just stopped without any obvious change? The error message reads as if there is a syntax error, but the code hasn't been changed since end of last year and is working flawlessly (syntax error free) on my machine for more than a month. Mind you, I'm running Node-RED 3.0.2, perhaps it's worth upgrading your Node-RED as a first attempt?

**Comment by ChocoTonic** [comment]
to give a little more context, this non working package is running on Linux, I have node-red also running on Windows 10 as well and it's currently working just fine. 

I'll give upgrading node-red a shot but I don't know if that will make a difference since I haven't made any significant changes to the Windows 10 machine with respect to node-red.

is there a way I could look into it myself and fine out where that syntax error could be so that I could possibly attempt to debug it?

**Comment by solaech** [comment]
I'm having the same issue, running a Linux VM with Ubuntu 20.04.5 LTS, node-red v3.0.2 and VSH 3.0.7.
Only way to get it working was downgrading VSH back to 3.0.6.
If i can help you some how just get back to me.

**Comment by csuermann** [comment]
Reopening as some users apparently experience errors due to the nullish coalescing operator (??).
