### ISSUE TITLE
[FEATURE REQUEST] Tank Level Sensor Type

### ISSUE THREAD

**Issue by myervin** [csuermann/node-red-contrib-virtual-smart-home#186]
**Describe the solution you'd like**
Addition of a simple "Level Sensor" device type, as in the level of fluid in a tank 0-100%. "Alexa, what is the level of the Fresh Tank?

**Describe alternatives you've considered**
The Temperature Sensor type is similar except the verbal command and scale are inappropriate. 

**Additional context**
I use VSH in RV and Marine environments and it would be useful to have tank level information accessible to Alexa. RV's and boats have assorted tank types such as black, grey, fresh, fuel, propane, diesel, gas, DEF, coolant, etc. I would imagine there are also some home applications also such as level of fuel oil, propane, aquarium, pool, etc. In my applications tank levels are standard PGN's available on the existing boat or RV CAN bus via RV-C/NMEA2000/J1939 and are gatewayed to node-red via socketcan or another gateway. 

Thanks!

**Comment by ThetaGamma** [comment]
Well, another valid usage example  for [Alexa.InventoryLevelSensor Interface 3](https://www.developer.amazon.com/en-US/docs/alexa/device-apis/alexa-inventorylevelsensor.html) as requested in #178 :-)

**Comment by Bagarre** [comment]
+1 Came here to request this exact feature.
