### ISSUE TITLE
[BUG]  I can't manage payment on PRO account

### ISSUE THREAD

**Issue by Gml10** [csuermann/node-red-contrib-virtual-smart-home#187]
The account payment management link does not appear on the node, my card is being charged and I need to change my payment method!

**Comment by csuermann** [comment]
Hi @Gml10,

You should be able to access the Stripe dashboard directly at https://billing.stripe.com/p/login/6oE00vdQ62Tp3LidQQ

Could you kindly share a screenshot of your _VSH connection edit dialog_ that shows the problem with the in-app "_manage subscription_" button?
