### ISSUE TITLE
All devices disappeared from Alexa 

### ISSUE THREAD

**Issue by Spazpeker** [csuermann/node-red-contrib-virtual-smart-home#189]
**Describe the bug**
All the devices have disappeared from Alexa

All the devices are showing as connected in node red
I do have pro version

**Comment by csuermann** [comment]
Hi @Spazpeker,

Sorry to hear you're experiencing issues with VSH and Alexa. To troubleshoot this further, could you please share more info?

- Do you have an idea what might have caused the issue?
- Do your VSH devices still appear as "online" after restarting Node-RED?
- Please provide the first 10 digits of your Thing ID so that I can have a look

**Comment by Spazpeker** [comment]
Haven’t really done anything different 
Says online after reboot
ID vsht-1b5adf38

**Comment by Spazpeker** [comment]
I do have https://github.com/586837r/node-red-contrib-alexa-remote2 running on pi and that is still working 
I use it to report my battery level

**Comment by Spazpeker** [comment]
Don’t know if you have done anything but got a Alexa notification of 79 devices added, and it’s all back working

**Comment by csuermann** [comment]
Thanks, @Spazpeker!

The current state in the backend DB indeed contains just one device (sliding gate). In the logs I see a number of `bulkundiscover` commands around 2023-03-04 00:09 UTC. I'm guessing something went somewhat wrong there.

In any case, I just triggered a `rediscover` command for your devices and hope that fixes it.

**Comment by Spazpeker** [comment]
Hi, its just deleted everything again, if i disable each node save and then re enable it, that node comes back on alexa, as i have 80 devices thats quite a pain, could you reset it again please

**Comment by csuermann** [comment]
Hi @Spazpeker,

I just did another reset for your devices. However, I'd like to understand how this situation could occur. Could you please share which steps led to your devices disappearing from Alexa?

**Comment by Spazpeker** [comment]
Hi @csuermann,
Most of my devices are ZWave connected to Fibaro HC3 via http to node red and your Alexa nodes,
The HC3 has been very problematic, so I have setup a separate pi with home assistant on, I have moved 4 devices across and had been using MQTT to the Alexa there has been a lot of changes to get it to work.
I usually don’t have the Alexa nodes connected to my new bits till I think they are working, but I had been doing alot of deployments.

**Comment by Spazpeker** [comment]
just to add i havent messed with the Alexa nodes,
