### ISSUE TITLE
Huge Feature Request: New Dropdown Menu in your node to prepare Output for different Backends

### ISSUE THREAD

**Issue by nicedevil007** [csuermann/node-red-contrib-virtual-smart-home#19]
Hey again,

after my thoughts about your node I came a long with a huge idea that could be realy helpfull for beginners or even makes things a lot easier to setup.

What if you implement a new Menu item in your node with a dropdown where the user could select the backend.
F.e. deconz/phoscon or zigbee2mqtt (that are both tools I'm used to, and there a many more).

If the user set nothing up, everything will be like it is right now. If the user setup zigbee2mqtt as the backend, the output will be somewhat "simplified" that your node should only be connected to the endpoint in node-red rather than having to manipulate the output with function nodes that much.

If that is possible and you like to do it, I can help you with 2 backends above. Other guys that want other backends can help here as well.

**Comment by csuermann** [comment]
Just to make sure I understand this request: The output of the VSH node would then be formatted / decorated in accordance to what target system was selected, e.g. zigbee2mqtt, but the general behavior of the VSH node would not change at all, correct?

Can you share your helper function-nodes that currently do the trick for you?

**Comment by steff75** [comment]
Hi. Since nicedevil007 has not yet answered, attached my helper subflow to convert the output for deCONZ. For me it does what it should, although there is certainly much that can be optimized and extended.
[deconz-helper-subflow.zip](https://github.com/csuermann/node-red-contrib-virtual-smart-home/files/5936814/deconz-helper-subflow.zip)

**Comment by nicedevil007** [comment]
Oh thank you for reminding me... just forgot about my own created issue O_O

zigbee2mqtt wants commands like this:

```
payload: {
  brightness: 255,
  color: {hex: #FF0000},
  color_temp: 150,
  state: "on"},
topic}
```

`brigtness` must be a value between `0` and `255`
`color` would be the easiest way to send a hex value
`color_temp` is a value between `150` and `500` where `150` is coldest white and `500` is warmest white.
`state` should be `on` or `off` but can also be `ON` or `OFF`

there is one more possible variable but I guess the transition time won't make sense to send this by voice command. I think there is no usecase for this.

**Comment by csuermann** [comment]
I thought about custom converters some more and for now decided against implementing this as part of VSH. I believe converting logic could easily be put in a function node that gets placed behind the vsh-device node. Those function nodes could even be [shared](https://flows.nodered.org/) with the Node-RED community.
