### ISSUE TITLE
[BUG] Installation fails

### ISSUE THREAD

**Issue by kamellemann** [csuermann/node-red-contrib-virtual-smart-home#190]
**Describe the bug**
Unable to install Error:
2023-03-04T11:54:36.617Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-virtual-smart-home@3.0.9
2023-03-04T11:54:40.131Z [out] 
2023-03-04T11:54:40.131Z [out] up to date in 3s
2023-03-04T11:54:40.174Z rc=0

**To Reproduce**
1. Try to install node-red-contrib-virtual-smart-home via Node-Red GUI

**Expected behavior**
Node should be installed

**Environment (please complete the following information):**
 - virtual-smart-home version: 3.0.9
 - Node-RED version: 7.2.1

**Comment by csuermann** [comment]
Hi @kamellemann,

> Node-RED version: 7.2.1
This must be a typo. [Latest](https://www.npmjs.com/package/node-red) Node-RED version is 3.0.2

- Which Operating System are you using?
- Are you trying to install VSH for the first time or is this an update installation?
- Can you install other packaged without any issue?

**Comment by kamellemann** [comment]
Sorry, it´s RedMatic Version 7.2.1.
It´s first time installation.
Other packages are working fine (WhatsApp, Alexa etc.)

**Comment by kamellemann** [comment]
![image](https://user-images.githubusercontent.com/24431844/222908022-dc1aa1b9-ce2e-4ae1-bda6-de945bbc3587.png)

**Comment by kamellemann** [comment]
![image](https://user-images.githubusercontent.com/24431844/222908109-ffd96b2d-5399-4e1f-8d21-fc697b341752.png)

**Comment by fkhr79** [comment]
If I remember correctly Redmatic is based upon NodeRed 2.x
You will need NodeRed 3.x for vsh
This is why I abandoned RedMatic and set up a separate Pi running NodeRed 3.x
Try it! It's easy... and Redmatic is dying anyway!

**Comment by kamellemann** [comment]
Ah OK. Got it. Thank´s for your fast support!

**Comment by csuermann** [comment]
Thanks for helping out, @fkhr79! @kamellemann, I'm closing this issue for now. Feel free to re-open it in case you run into the same problem with a more recent Node-RED version.
