### ISSUE TITLE
I have a problem with the subscription type

### ISSUE THREAD

**Issue by sRspectrect68** [csuermann/node-red-contrib-virtual-smart-home#191]
Hi!
I subscribed to the PRO subscription, but I still see the FREE plan in the properties of the virtual device.
The "Alexa can retrieve device staate" property is disabled.
what could be the problem?
Tanks Spectre68

**Comment by fkhr79** [comment]
Had the same issue at first: did you try to restart the flows already? ... or to restart Node-RED? - Solved the problem for me.
