### ISSUE TITLE
Übergabe von Zusatzinformationen mit Sprachbefehl

### ISSUE THREAD

**Issue by cybersmart-eu** [csuermann/node-red-contrib-virtual-smart-home#193]
Servus aus München,

ich teste gerade VSH in Verbindung mit einer Garagensteuerung und das funktioniert wunderbar in dem die Steuerung eine URL aufruft die dann bei mir eine Routine triggert.
Habe mich nun etwas eingelesen in die Möglichkeiten auch in Verbindung mit Node-Red und da kommt eine Frage auf.
Ich habe eine WLED hinterleuchtete Weltkarte und der ESP32 Controller kann 10+ verschiedene Lichtszenarien „abspielen“. Dazu schicke ich ein einfaches Kommando der Form http://<IP>/?cmd=Rainbow wobei Rainbow dann das zugehörige WLED Muster auslöst.

Ist es möglich mit dem node-red node auch „custom commands“ auszulösen.

Also wenn ich sage Alexa, Weltkarte Regenbogen wird automatisch die URL mit „cmd=Rainbow“  aufgerufen? Ähnlich ist es ja bei LEDs die Farben bilden sollen, aber da ist es vermutlich fest schon hinterlegt. Ich würde irgendwie halt eine Matching table brauchen (Regenbogen -> Rainbow).

Ist jetzt eine sehr spezielle Frage aber bevor ich da jetzt tiefer eintauche kann das vielleicht schnell beantwortet werden. Wäre super hilfreich und erhöht im Haus den WAF (Wife Acceptance Factor).
Ich wäre dann auch sofort mit einem Pro Abo dabei unabhängig von der Anzahl der Geräte als Supporter.

Viele Grüsse,

Uwe

**Comment by fkhr79** [comment]
Grüße aus dem Rheinland!

So eine Spielerei erhöht bereits den WAF? ... Du gehörst glaube ich eher zu den Gesegneten... ;-)

Zu Deiner Frage: so, wie Du Dir das vorstellst, geht es meines Wissens nicht: VSH kann "nur" bestimmte bzw. von Alexa vorgegebene SmartHome-Devices mit ebenfalls vorgegebenen Befehlssätzen simulieren.

ABER: es gibt doch eine (in meinen Augen) viel einfachere Lösung. Je Lichtszene einfach ein VSH-Device vom Typ "Scene" anlegen, die dann das jeweilige HTTP-Kommando an den ESP32 absetzt (bzw. einen http-node anstubst, der das dann erledigt). Fertig! Je Szene dauert das keine 5 Minuten.

Grüße!
FKHR

P.S.: English would be nicer for our international friends...
