### ISSUE TITLE
Problem with Temperature Sensor

### ISSUE THREAD

**Issue by namirda** [csuermann/node-red-contrib-virtual-smart-home#195]
**Describe the bug**
I have several Temperature Sensor virtual devices and none are working. The other virtual devices which I have tried all seem to be working normally. 

The problematic virtual temperature devices appear as expected in the Alexa app and do show the correct temperature but when Alexa is asked for the temperature she says "I'm not quite sure what went wrong"

In case it is relevant, I upgraded to PRO yesterday and although my account shows PRO in the "Edit Connection Node" it still shows FREE in the "Edit Virtual Device Node"

How can I debug this temperature sensor problem? I have selected the debug option in the "Edit Connection Node" but the output in the log file does not show any obvious errors or problems.

**Environment (please complete the following information):**
 - virtual-smart-home version: 3.0.9
 - Node-RED version: 3.0.2

**Comment by csuermann** [comment]
Hi @namirda,

Have you tried restarting your Node-RED flows or Node-RED altogether as suggested [here](https://github.com/csuermann/node-red-contrib-virtual-smart-home/issues/191)? This should typically resolve this bug, which unfortunately I haven't managed to reliably reproduce yet.

Best,
Cornelius

**Comment by namirda** [comment]
Hi Cornelius,

Yes of course. I had to restart Node Red after updating VSH to 3.0.9.

All virtual devices are working fine - except for the temperature sensors! How can I debug/investigate this further - the log output doesn't show any obvious issues.

Thanks

**Comment by csuermann** [comment]
Hi @namirda,

So your Node-RED no longer shows that you're on the "FREE" plan? Good!

Have you enabled the "retrievable" option for your VSH temperature sensor?

**Comment by namirda** [comment]
Hi,

No - it still shows the FREE plan on the "Node Config" page - but shows the PRO plan on the "Edit Connection" page.

And because it shows Free plan, the retrievable option is disabled.

**Comment by csuermann** [comment]
Ah, sorry, I misinterpreted. The symptom you describe usually go away after restarting Node-RED. Are you saying that in your case this doesn't work?

**Comment by namirda** [comment]
Hi Cornelius,

I have just rebooted my swarm including the node-red service one more time and it all looks fine now - thanks
Alexa is even taking to me again!
I had rebooted after upgrading VSH to 3.0.9 but not since - the extra reboot after going PRO fixed it.
Thanks

**Comment by csuermann** [comment]
Perfect! Thanks for reporting back! Glad to hear everything is working as it should now!
