### ISSUE TITLE
Discover Alexa device identifier that received the voice-command

### ISSUE THREAD

**Issue by vialkoje** [csuermann/node-red-contrib-virtual-smart-home#197]
Is there a chance to identify the Alexa device id that received the command ? I'd like to respond with spoken text on the same device that was receiving the cammdn and therefore I hav to find out what the identifier of the device was that received the voice command.

Regards Jens

**Comment by fkhr79** [comment]
nope :( 
see #169

**Comment by thermseekr** [comment]
Hello all, I too would like to reply to the same device. Can the echo devices be identified? I mean, is this information available in the exchanged data?

**Comment by csuermann** [comment]
This is unfortunately technically not possible. See [FAQ #2](https://github.com/csuermann/node-red-contrib-virtual-smart-home#faq) for a workaround.
