### ISSUE TITLE
VSH devices disappearing from Alexa

### ISSUE THREAD

**Issue by ripbucks** [csuermann/node-red-contrib-virtual-smart-home#198]
- virtual-smart-home version: [e.g. 3.0.9]
 - Node-RED version: [e.g. 3.0.2]

I am assuming this might be a bug; Today Alexa no longer responds and looking at the Alexa App, ALL my VSH devices are missing.

If I add a new VSH Node Red device, Alexa acknowledges it and it works fine. 

If I change the name of an existing VSH device, Alexa finds that OK.

Why would Alexa drop all the VSH devices all of a sudden? My Node Red system has not been touched for weeks.

How can I get Alexa to see all my VSH devices again? I have so many that the idea of having to modify all the names of every one and set them back again is something that I'd rather not get into! Is there another way?

I have the Pro version and all the VSH devices show as 'connected' and all the devices show under 'Properties' of the VSH Connection Node.

Thanks

UPDATE: 

I have found that Disabling and then immediately Enabling the 'virtual smart home' skill in the Alexa iOS app causes all the missing VSH Devices to reappear in the Alexa App and thus they can once again be controlled via Alexa/Node Red.

**Comment by csuermann** [comment]
Hi @ripbucks,

Thanks for reporting this awkward behaviour!

Vsh-Connections and all associated vsh-devices get pruned after 30 days of inactivity, but this doesn't seem to be the explanation for the problem you were experiencing as re-enabling the skill in the Alexa app would not have restored your devices. Therefore I'm tempted to think that Alexa had a (temporary?) glitch.
