### ISSUE TITLE
Can't find any skill called "virtual smart home" in Alexa app

### ISSUE THREAD

**Issue by cymplecy** [csuermann/node-red-contrib-virtual-smart-home#2]
Is it a country specific one I wonder?  I'm in UK

**Comment by csuermann** [comment]
Hi @cymplecy! The skill is currently published in Germany and awaiting approval for 13 more countries. I can ping you here, once Amazon approves.

**Comment by cymplecy** [comment]
Thank you :)

**Comment by csuermann** [comment]
The skill should be available in the UK skill store by now.

https://www.amazon.co.uk/Cornelius-Suermann-Virtual-Smart-Home/dp/B08JV9RT7H/ref=sr_1_1?dchild=1&keywords=vsh&qid=1602138221&s=digital-skills&sr=1-1
