### ISSUE TITLE
Duplicate Devices Conflict Question

### ISSUE THREAD

**Issue by seaverd** [csuermann/node-red-contrib-virtual-smart-home#20]
So I have a virtual smart home device for my kitchen cabinet lights.  Every couple of days it stops working.  When I go to alexa.amazon.com and look at my smart home devices "Cabinet Lights" shows up three times.  When I click on the devices, two of them show as unavailable and the third is the correct device.  If I hit remove for the two unavailable devices, everything goes back to working.  After a day or two, the two unavailable devices show back up.  I have tried removing all three from the alexa.amazon.com, followed by removing the node from my nodered flow and then deploying it, followed by re-adding the node to the flow...but again in three days they show back up.

Are these devices cached somewhere?  Anyway to purge them?
Any suggestions would be greatly appreciated.

Also - thank you very much for implementing my suggestion for the Topic field!  It has simplified my flows.

Dan

**Comment by csuermann** [comment]
Hi @seaverd,

First of all, which version of virtual smart home are you currently using? Please update to the latest and let me know if the problem still persists.

Alexa periodically tries to discovery new devices and the ones you deleted (from Alexa) seem to be re-added when that happens because they still exist in the VSH backend. In the edit dialogue of the vsh-connection node you can lists all your known devices and delete them.

Looking forward to hearing back from you!

**Comment by seaverd** [comment]
@csuermann 
Thank you for your assistance, as I believe your reply fixed my situation.  I was on the latest version 1.18.0 at the time of writing my original message.  I was not aware of the registered devices being listed in the connection node.  Once I opened that, there were three entries for cabinet lights and two of them were shaded differently.  I deleted the two devices that were shaded.  I guess to be 100%, So currently I have only one cabinet light registered device and it works at it should.  I need to wait a day or two to make sure the other two devices don't reappear, but I don't suspect that they will.

Thanks again!
Dan

**Comment by csuermann** [comment]
Glad to hear I could help.

The shaded devices must have been artefacts of connection nodes that no longer exist.

If you don't want to wait for the next periodic Alexa discovery process, you can also initiate it manually by saying "Alexa, discover new devices"
