### ISSUE TITLE
Echo Dot Temperatur in Node-Red zur Verfügung stellen

### ISSUE THREAD

**Issue by tt2g89** [csuermann/node-red-contrib-virtual-smart-home#201]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Es wäre hilfreich, wenn man die Temperaturdaten der aktuellen Echo-Geräte in Node-Red bekäme, um sie an anderer Stelle, z.B. in Loxone zur Verfügung stellen zu können.

**Describe alternatives you've considered**
Aktuell lässt sich meines Wissens nach nur das Gerät über die Gruppe, z.B. Büro wegen der Temperatur abfragen. Die Google-Ergebnisse beziehen sich quasi ausschließlich auf Drittgeräte-Anbieter, die die Daten z.B. über Homematic in Alexa verfügbar machen wollen, aber das funktioniert ja sowieso.
Ich habe versucht, über Anlage einer VSH-Objekts Temperatursensor und retrieve device status über eine Routine in der Alexa-App die Daten reinzuschieben, aber kann den Sensor nicht als Empfänger in der Routine auswählen (klar, ist ja ein Sensor, der gibt nur und nimmt normal nichts, aber hey, versuch macht klug ;-) ).

**Additional context**
Bei Fragen gerne kurz nachhaken. Da Du ja Status auch zurückgeben kannst, habe ich die Hoffnung, dass es vielleicht auch möglich ist, Werte der vorhandenen Echo-Geräte abfragen zu können.

Cheers,
Thomas

**Comment by csuermann** [comment]
Hi Thomas,
das ist leider technisch nicht möglich :-/

**Comment by tt2g89** [comment]
Hi Cornelius,
thanks für die Rückmeldung. Schade.
