### ISSUE TITLE
 Question - Would it be possible to add the variable "ID of the Echo device" ?[FEATURE REQUEST]

### ISSUE THREAD

**Issue by tro4444** [csuermann/node-red-contrib-virtual-smart-home#202]
In order not to have to assign a separate name to each device to be controlled and to use e.g. lights off and lights on when using several Echo devices in different rooms, the information on the ID of each individual Echo device would be very helpful

**Comment by csuermann** [comment]
Hi @tro4444,
Unfortunately Alexa's smart home API doesn't pass data about the Alexa device that was used for invoking the skill. However, there is a workaround, see [FAQ #2](https://github.com/csuermann/node-red-contrib-virtual-smart-home#faq)
