### ISSUE TITLE
Node-Red and Ring Doorbell

### ISSUE THREAD

**Issue by bobloeffler** [csuermann/node-red-contrib-virtual-smart-home#203]
Hi Cornelius,

I would like a notification sent to my wireless IoT device whenever someone presses the ring button on my Ring Doorbell 3.  I was hoping that the Ring doorbell would send a signal to Alexa and then Alexa could send a signal (skill?) to your VSH node in my Node-Red and then Node-Red could send an MQTT message to my MQTT broker which would then send the message to my IoT device (an esp8266 microprocessor that has LEDs that light up).    Do you know if that is possible with your node?  Or some other way?

Thanks,
Bob L

**Comment by csuermann** [comment]
Hi Bob,

I believe that should be possible by configuring a routine in the Alexa app which reacts to your Ring doorbell event and then triggers a state change of an VSH device. Once you have managed to route the signal to VSH / Node-RED, you should be able to do anything with it.

**Comment by bobloeffler** [comment]
Great!  Thank you, Cornelius.  I’ll give it a try.

Bob Loeffler

**Comment by bobloeffler** [comment]
Hi Cornelius,

I was able to get it to work!  It took a few hours because Alexa (I think) didn't see the doorbell as a device (or VSH?) as a device.  I had to set it up as a "scene".  It was very confusing and is hard to explain.  Anyway, it's working now.  My IoT device lights up when I press the doorbell's button.  Thanks!

Bob L
