### ISSUE TITLE
revoking access to my PRO subscription from old Node-Red device

### ISSUE THREAD

**Issue by MrCO0OL** [csuermann/node-red-contrib-virtual-smart-home#204]
Hi,
some old Node-red server has my PRO account configured .... I dont have access to that server anymore ... how can I revoke that old Node-red server from accessing my PRO account ?
it keeps registering new devices and delete my devices without any control from my side

is there a configuration screen where I can manage authorized Node-Red connections that I can use to revoke such authorizations? because it can happen again in the future

if possible remove all of my authorizations linked to my amazon account mert9.deniz@gmail.com
so that I can redefine them again on authorized servers

thanks in advance

Kind regards

**Comment by csuermann** [comment]
Hi,

I believe disabling the VSH skill in your Alexa app will revoke all access. This sledge hammer approach might be a bit inconvenient as you will need to go through the account linking process once more on the server(s) you wish to continue using with VSH.
