### ISSUE TITLE
[FEATURE REQUEST] Return Alexa Device and Call Summary

### ISSUE THREAD

**Issue by leadersls1ss** [csuermann/node-red-contrib-virtual-smart-home#205]
Up until recently, I have been using Virtual Smart Home for controlling devices along with node-red-contrib-alexa-remote2-applestrudel to control devices based on the location of the Alexa device.   For example, when in the basement, I would have 'Alexa turn off the lights', then VSH device would fire, and then I would check output from the 'on device activity' node in applestrudel to see which Alexa device the request was made from.   This allowed me to say 'Alexa turn off the lights' in any room with an alexa and it would only turn off the lights based on which alexa it was requested from the flows I had put together.   The 'On Device Activity' in applestrudel continues to be hit or miss for working and Amazon recently made some changes that caused this feature to break.   Would it be possible to add a feature where VSH could also return the alexa device name where the request was made from along with and a summary of the question asked to the device?    Possible or not, thank you for the VSH because it was worked very well for me.

**Comment by csuermann** [comment]
Hi @leadersls1ss,
This has been asked many times before, e.g. here #197 and #202. It is technically not possible to implement this feature due to limitations of the Alexa Smart Home API. However, consider the workaround described in [FAQ #2](https://github.com/csuermann/node-red-contrib-virtual-smart-home#faq). Hope that works for you.

**Comment by leadersls1ss** [comment]
Ok, thanks for the response.   I missed the FAQ section.   Sorry about that.

Jon
