### ISSUE TITLE
reusing existing virtual devices

### ISSUE THREAD

**Issue by langrock** [csuermann/node-red-contrib-virtual-smart-home#206]
Hi,

Not sure if this a bug (unlikely) or a user error (very likely), but I cannot figure out how to reuse an existing virtual device in a separate context without creating a duplicate of the device. For example, I would like to use the same 'switch' VSH object in several logical contexts. So far, this results in the very same object showing up multiple times both in the Alexa app as well as the list of virtual devices. This, in turn, causes grief and keeps Alexa from working as expected. The only way that appears to work for me is to connect the output of one VSH object to separate logic circuits as shown below. I would appreciate if someone could point me towards a cleaner solution; I suppose the 'virtual in / out' node would work, but that seems kludgy.

Thanks

<img width="797" alt="Node-RED___piella_local" src="https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/555029/37e0dbaa-d020-4a13-b685-79f92b4e0256">

**Comment by csuermann** [comment]
Hi @langrock,

Every VSH device added to the Node-RED canvas automatically registers a new smart home device with Alexa. While this adds convenience, it comes with the limitation you observed: Two identically named VSH nodes create two Alexa devices with a naming conflict, thus making it more or less impossible to control them via voice commands.

However, Node-RED's built in `link in` / `link out` nodes allow you to accomplish what you want. You could use `mqtt` nodes, too.

**Comment by langrock** [comment]
I appreciate you taking the time to answer this question. I was able to use the link in / out nodes to accomplish what I'd been wanting to do, but will also explore the mqtt option to see what feels more natural. Regards
