### ISSUE TITLE
[FEATURE REQUEST] payments via paypal

### ISSUE THREAD

**Issue by JoranJix** [csuermann/node-red-contrib-virtual-smart-home#207]
I dont own a visa card and my card will not be accepted by link
I would love to see a payment via paypal which is linked to my bank account.

**Comment by csuermann** [comment]
Hi @JoranJix,

Thanks for reaching out. I plan to add PayPal as a payment method as soon as I find some time.

Best,
Cornelius

**Comment by csuermann** [comment]
Quick update that PayPal is finally available as a payment option.
