### ISSUE TITLE
How can i add a humidity sensor virtual device?

### ISSUE THREAD

**Issue by MrCO0OL** [csuermann/node-red-contrib-virtual-smart-home#208]
Hello,
How can i add a virtual device for my humidity ? And is there a way to add custom devices which are not mentioned in vsh templates ? e.g. regular light device (similar to switch but has an icon of lamp instead of switch)

**Comment by csuermann** [comment]
Unfortunately humidity sensors are not yet supported by VSH. But you can configure your switch to show up as a light in the Alexa app.
