### ISSUE TITLE
PRO upgrade

### ISSUE THREAD

**Issue by EkiSkyten** [csuermann/node-red-contrib-virtual-smart-home#209]
I purchased the PRO upgrade.  In the connection page it shows I have a PRO account.

But, on the device property page it says FREE and I am unable to set the retrievable temperature property

**Comment by csuermann** [comment]
Hi @EkiSkyten,

Thank you for supporting VSH! Usually this kind of issue should resolve itself after restarting Node-RED.

**Comment by EkiSkyten** [comment]
I restarted node-red.  Then redeployed the flow.  Same thing happening.  Still says “FREE”

**Comment by csuermann** [comment]
Hi @EkiSkyten,

Sorry to hear that restarting Node-RED didn't do the trick. To troubleshoot this further, please send me an email to vsh@csuermann.de with the following information:

- VSH thing ID (can be found in the VSH connection details)
- Node-RED version
- VSH version
- Does VSH generally work? (apart from the PRO features)

Best,
Cornelius

**Comment by EkiSkyten** [comment]
The ID is             Vsht-0909b0f2-042d-4887-8154-08b2d87c166a

NodeRed            v2.2.2

VSH                     v3.0.9

 

Does it work?  It seems to work just fine.  I can set the temperature on the virtual device (temperature) and it shows up on the virtual device in the alexa app.

 

While I can see the temperature on the virtual device in the alexa app, I cannot get a response from alexa when I verbally ask for the temperature.  I assume it is because alexa is not looking at the virtual device in the alexa app, but rather querying for the data which will not work because of the FREE/PRO issue.

 

Thanks

 

Eki

**Comment by csuermann** [comment]
Hi @EkiSkyten,

Hmm, everything looks pretty alright on the backend side of things. The only thing I noticed is that you're running a rather old Node-RED version. If you can, try updating it.

Also, would you mind observing you browser's network tab while opening the VSH device details? There should be a GET call to `http://[your-host]:1880/vsh-connection/[unique ID]` - see example below.

What does the response look like on your end?

<img width="399" alt="image" src="https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/10939809/619d384f-0dfc-4e47-8474-9de9e65c69dd">

**Comment by EkiSkyten** [comment]
I upgraded nodered to 3.1 and now I see the PRO subscription on the node!!!!

I can now set the temperature and when I ask alexa for the temperature it responds.

 

However, it looks like alexa responds with the property on the virtual device, that is the temperature I push down to amazon service.

I expected that Alexa would call back to the nodered service and that I would see a query, but I see nothing happening in nodered debug log.

 

Is this normal?
