### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by thmeger** [csuermann/node-red-contrib-virtual-smart-home#21]
First of all, I like the skill a lot. It works much better than the local skill I used before. 
Could you please point out what security concept runs behind the scenes and what risk I take using your skill.
I ask this, because I want to know alittle bit more before I advice others on e.g. (loxforum.com) to try your skill. 
Thanks in advance.

**Comment by csuermann** [comment]
Hi there! Thanks for the question.

As with any smart home skill, you need to trust the provider. VSH is no exception.

You need to know that VSH is a pet project of mine that I dedicate some of my spare time to.

Here are a few things that you find security related. Let me know if you want to know anything else.

- The backend runs on AWS, leveraging the IoT core platform and lambda functions.-
- Your device information are stored in a DynamoDb table as well as parts of your Amazon profile information (namely your unique account identifier, email address and OAuth access- and refresh tokens).-
- The Node-RED vsh-connection node establishes an encrypted MQTT connection to the AWS IoT core. When you give a command to Alexa, a lambda function is triggered that ultimately publishes an MQTT message that only your vsh-connection node can subscribe to.
- The Alexa skill lambdas are deployed in multiple regions for better latency, the rest of the backend however currently runs in the eu-west-1 region (Ireland).
- I am not interested in your usage-patterns and am not spying on you
- Mind you, if my monitoring system spots abnormal traffic spikes originating from your device, I might take a look at it to understand what's going on. I might even close your connection to stop my costs from exploding.

**Comment by thmeger** [comment]
Thanks, that helps a lot. 
Your skill retrieves all information when my echo interacts with one of the registered devices, correct? What is all in this case? :-)
Example: 
I say, Alexa turn on "television". 
"televison" is a device I registered in Node-RED with your skill-node. 
But if I say Alexa play radio NDR2, this is no interaction with one of the skill-devices and that is why you won't retrieve this information? 
What does the information you retrieve look like? Who is sending what information back to my Node-RED? 
When the info comes back, the Node-RED on my pi executes the smarthome action/logic - that is clear and fine. 
Thanks again!

**Comment by csuermann** [comment]
When you interact with your echo device, Alexa transforms your voice command into a "directive", which gets routed to the VSH skill backend. For example, when you say "Alexa, dim the kitchen light to 50 percent", the Alexa service first determines which smart-home skill your kitchen light belongs to and then sends the respective directive event to that skill's backend. The directive contains just the data needed to fulfil the request, in this case the desired brightness level and the identifier of the virtual device (Amazon calls this "endpoint").

Here is an [example](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-brightnesscontroller.html) of the payload my skill backend may receive from Alexa:
```
{
  "directive": {
    "header": {
      "namespace": "Alexa.BrightnessController",
      "name": "SetBrightness",
      "messageId": "<message id>",
      "correlationToken": "<an opaque correlation token>",
      "payloadVersion": "3"
    },
    "endpoint": {
      "scope": {
        "type": "BearerToken",
        "token": "<an OAuth2 bearer token>"
      },
      "endpointId": "<endpoint id>",
      "cookie": {}
    },
    "payload": {
      "brightness": 50
    }
  }
}
```
