### ISSUE TITLE
device in alexa app is cropped

### ISSUE THREAD

**Issue by EkiSkyten** [csuermann/node-red-contrib-virtual-smart-home#210]
**Describe the bug**
Functionally everything seems to work.  However, the text on the device is cropped when displayed

**To Reproduce**
1 Get a functional virtual device that returns status
2 See that it is cropped

**Expected behavior**
Expect the data being displayed is not cropped

**Screenshots**
See attached

**Environment (please complete the following information):**
 - virtual-smart-home version: 3.0.9
 - Node-RED version: 3.1
 - iPhone 14 Pro

**Additional context**

![IMG_1700](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/1634792/72e8376c-0aab-4596-b1b5-a1af89df1719)

**Comment by csuermann** [comment]
Not sure there is anything VSH can do about this as it looks like a shortcoming of the Alexa app.
