### ISSUE TITLE
Bezahlung nicht übernommen

### ISSUE THREAD

**Issue by SnakeShiter** [csuermann/node-red-contrib-virtual-smart-home#213]
Hallo,
ich hatte ein Jahr lang die Pro Version.
für das  neue Jahr wurde das Geld bereits abgebucht (komischerweise obwohl die Visa abgelaufen ist)
aber in Node-Red ist noch der FREE plan aktiv.
wie gehe ich vor um das zu fixen?

**Comment by csuermann** [comment]
Hallo @SnakeShiter,

Gerne überprüfe ich, was da schief gelaufen ist. Bitte sende mir dazu eine Nachricht mit Deiner für das Abo verwendeten Email-Adresse an vsh@csuermann.de

Viele Grüße
Cornelius
