### ISSUE TITLE
Turn Smart Plug on/off based on Temperature

### ISSUE THREAD

**Issue by hutny1980** [csuermann/node-red-contrib-virtual-smart-home#214]
Hi - looking for some help, please. 

I'm using the free version of VSH with Node-Red and managed to display the current room temperature within the Alexa app, using the temperature sensor and passthrough options. 

What I now want to be able to do is turn a smart plug on/off within the Alexa app based on the room temperature being sent to the Alexa app i.e. automatically turn a smart plug on/off (which is paired in the Alexa app) when the temperature reaches a certain temperature.

The smart plug is not supported by Node-Red, so can only be controlled within the Alexa app.

Is this possible?

Thanks G

**Comment by csuermann** [comment]
Hi @hutny1980,

You can configure routines in the Alexa app based on certain triggers. Unfortunately it doesn't seem to support temperature readings as a trigger.

You might be able to work around that limitation by using a different virtual device, e.g. contact sensor, which seems capable of triggering routines when its state changes. So in Node-RED, whenever your room temperature reaches your defined threshold, you pass a msg to a vsh contact sensor with payload.detectionState = 'DETECTED'. In the Alexa app, you configure a routine that turns your smart plug on/off when the vsh contact sensor state changes.

**Comment by hutny1980** [comment]
thank you @csuermann - this worked perfectly. Thank you for the swift response - it's hugely appreciated.

Cheers,
G
