### ISSUE TITLE
[Question] Blinds not showing controls in Alexa APP

### ISSUE THREAD

**Issue by pedroportasvieira** [csuermann/node-red-contrib-virtual-smart-home#216]
Hi,

First thanks for your work, seems amazing and super easy to use. 

Second, i added a blinds device, everything went smooth, but then on Alexa APP when opening the device I don't have any options to control it, just shows the settings.
On the other hand I added a light switch and in the the APP I am able to see the controls to turn on/off and create routines.

Am I missing something here?

Thanks in advance

**Comment by csuermann** [comment]
Hi @pedroportasvieira,

Thanks for reaching out! For whatever reason the Alexa app will only display controls for blinds when the "retrievable" option is enabled on your VSH device.
