### ISSUE TITLE
Connection to Amazon Alexa not working any more (connection failed) [BUG]

### ISSUE THREAD

**Issue by Mikee1234K** [csuermann/node-red-contrib-virtual-smart-home#217]
I use this to have Ring doorbell and motion events in NR. Has worked for a long time, then it stopped. I started again, disabling the skill, then enabling and linking again. I also deleted the old vsh connection from NR, and recreated it. Linking the the Alexa account, after 'Allow@ it said registration complete. But still, ander the nodes it says in red connection failed, retrying in 30 seconds

**Comment by csuermann** [comment]
Hi @Mikee1234K,

Sorry to hear you're having issues with VSH. Could you please share your Thing-ID so that I can have a look? Also, did you switch all your VSH devices to the new VSH connection? Is there anything helpful in the Node-RED logs?

**Comment by Mikee1234K** [comment]
My thing ID is vsht-422c9b5a-7b32-4c34-9d0b-b7d215c6ea44
I did delete the old connection, and then set it up again, and all nodes (I have 2) use the new connection
I am running NR as a service, and dont have a window open for it... not really sure how to access the logs.. 
Under the nodes it now says connection quota exhausted

**Comment by csuermann** [comment]
On the server side everything looks good. In the past I've seen connection problems like this stemming from multiple Node-RED instances trying to connect to the AWS MQTT service with identical credentials, which leads to connections getting reset.

Is there anything in your setup that might intervene with those connections, e.g. a Firewall, Proxy etc?

Your local logs would be handy to debug this further.

**Comment by csuermann** [comment]
Glad to hear it's working again! 🚀
