### ISSUE TITLE
Problem creating connection

### ISSUE THREAD

**Issue by axelpip** [csuermann/node-red-contrib-virtual-smart-home#218]
Hi,

I have an issue creating a connection (first time). When I try I get an error 'ERROR code expired' after a few seconds (much to fast to enter the code in the Amazon page) in the add connection window. I am using NR 2.1.3, language is set to german. Also the Amazon account is a german one. The node version is 3.0.12. The virtual smarthome skill is linked to my amazon account. Any Idea what the issue could be?

Many thanks,
Axel

**Comment by csuermann** [comment]
Hi @axelpip!

Thanks for reaching out! I could not reproduce that problem. Just an idea, but could you please check if your computer's time is correctly synced? Also, it might help to observe what's going on on the network tab of your browser's dev tools.

Best,
Cornelius

**Comment by axelpip** [comment]
Hi @csuermann,

the time was correct on the NR as well as on the Windows-Maschine (W11) I was using for registration. I tried it on another Windows-Maschine (W10) today and it worked. No idea why but its Windows ;-). Thanks for your help. 

Axel
