### ISSUE TITLE
Instability [BUG]

### ISSUE THREAD

**Issue by kxkayser** [csuermann/node-red-contrib-virtual-smart-home#219]
*Hi.  Have been using the PRO version for a few years,.  Great Node.  However, as of today, several of my devices have stopped working.  Alexa just displays a short blue light.  Redeploying the flow doesn't help.  However, if I modify the node by changing say the capitalization of the name and then redeploy, it works for a while.  Running the latest release of NR on Raspbian and the latest update to the Node.  Thanks.

**Comment by csuermann** [comment]
Hi @kxkayser,
Thanks for reaching out! What you describe sounds like it could be a glitch on Alexa's side. Or has there been any recent change of the setup on your side? If you could share your "Thing-ID", I can take a look at the logs.

**Comment by csuermann** [comment]
Thank you! While I didn't find any suspicious entries in the server logs, I did observe an interesting pattern with your "antenna" device. It appears to have connected to the VSH cloud using two different Thing-IDs. If you're running a single instance of Node-RED, I recommend consolidating all your vsh-device nodes to use the same vsh-connection node (also known as Thing-ID).

If this adjustment doesn't resolve the issue, could you please provide the exact date and time of a command that Alexa didn't execute correctly? This information will be invaluable in helping me analyze the situation more precisely.

**Comment by kxkayser** [comment]
Hi,

 

Thanks for your response.  The antenna device may have been connected to my test system for a while.  The “radio” device surely was and has just been moved over to my production N-R instance.  I have renamed the development device radio_dev and both “antenna” and “radio” should only be connected to the Thing-ID I sent you.  Lease let me know if you have seen either of these devices connected to a different Thing-ID as of today.

 

Thanks again for your help. I will report any additional errors to you with all the details.

 

Regards

 

Ken Kayser

Tobaccoville, NC

 

 ***@***.***> ***@***.***

**Comment by kxkayser** [comment]
Hi Cornelius.  I just noticed a failure in device “antenna”.  It shows “online” in the NR flow but Alexa doesn’t “see” it.  Time is 22:30 Z.  I’m now going to tickle the node and redeploy.

 

After redeploying, it worked at about 22:38.

 

Is it still showing that device on 2 Thing Id’s?

 

Thanks for your help

 

Ken Kayser

Tobaccoville, NC

 

***@***.***

**Comment by csuermann** [comment]
Hi Ken,

Thanks for providing these insights. When you say "Alexa doesn't see it", what exactly do you mean by that?

I'm pasting an excerpt of my server logs from the night you mentioned below.

Currently, your "_antenna_" device is registered as endpointId `vshd-ab75f7787ace98`. I've marked all occurrences in the log in **bold**. The same goes for the timestamps that you provided.

I can't seem to find any traces in the logs for the time you mentioned Alexa didn't react to your command (22:30). Maybe Alexa didn't understand you correctly and therefore couldn't tie it to VSH? Can you still find it in your Alexa app history?

---
| timestamp (GMT) @2023-12-07  | message |
| --- | --- |
| 22:40:45.206 | { "directive":    { "header": { "name": "SetBrightness" },      "endpoint":       { "endpointId": "**vshd-ab75f7787ace98**",         "cookie": { "template": "DIMMABLE_LIGHT_BULB", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| 22:40:26.488 | { "directive":    { "header": { "name": "SetBrightness" },      "endpoint":       { "endpointId": "**vshd-ab75f7787ace98**",         "cookie": { "template": "DIMMABLE_LIGHT_BULB", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| **22:38:53.930** | { "directive":    { "header": { "name": "SetBrightness" },      "endpoint":       { "endpointId": "**vshd-ab75f7787ace98**",         "cookie": { "template": "DIMMABLE_LIGHT_BULB", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| **22:38:45.882** | { "directive":    { "header": { "name": "SetBrightness" },      "endpoint":       { "endpointId": "vshd-f0d5791cdd120172",         "cookie": { "template": "DIMMABLE_LIGHT_BULB", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| **22:38:41.141** | { "directive":    { "header": { "name": "SetBrightness" },      "endpoint":       { "endpointId": "vshd-f910cb345a8a68",         "cookie": { "template": "DIMMABLE_LIGHT_BULB", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| 22:35:01.424 | { "directive":    { "header": { "name": "SetBrightness" },      "endpoint":       { "endpointId": "vshd-ecc6dff53a109141",         "cookie": { "template": "DIMMABLE_LIGHT_BULB", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| 22:11:36.370 | { "directive":    { "header": { "name": "ReportState" },      "endpoint":       { "endpointId": "vshd-f0d5791cdd120172",         "cookie": { "template": "DIMMABLE_LIGHT_BULB", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| 22:10:44.467 | { "directive":    { "header": { "name": "ReportState" },      "endpoint":       { "endpointId": "vshd-f0d5791cdd120172",         "cookie": { "template": "DIMMABLE_LIGHT_BULB", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| 22:10:44.364 | { "directive":    { "header": { "name": "ReportState" },      "endpoint":       { "endpointId": "vshd-f0d5791cdd120172",         "cookie": { "template": "DIMMABLE_LIGHT_BULB", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| 21:43:07.109 | { "directive":    { "header": { "name": "SetBrightness" },      "endpoint":       { "endpointId": "vshd-f910cb345a8a68",         "cookie": { "template": "DIMMABLE_LIGHT_BULB", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| 21:31:47.121 | { "directive":    { "header": { "name": "TurnOn" },      "endpoint":       { "endpointId": "vshd-5d21a5350004cc",         "cookie": { "template": "ENTERTAINMENT_DEVICE", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| 21:31:30.924 | { "directive":    { "header": { "name": "TurnOff" },      "endpoint":       { "endpointId": "vshd-5d21a5350004cc",         "cookie": { "template": "ENTERTAINMENT_DEVICE", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| 21:29:47.228 | { "directive":    { "header": { "name": "TurnOn" },      "endpoint":       { "endpointId": "vshd-5d21a5350004cc",         "cookie": { "template": "ENTERTAINMENT_DEVICE", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
| 21:29:10.205 | { "directive":    { "header": { "name": "TurnOn" },      "endpoint":       { "endpointId": "vshd-5d21a5350004cc",         "cookie": { "template": "ENTERTAINMENT_DEVICE", "thingId": "vsht-af4d3de6-f495-4218-96fd-ede944e5278b" } } } } |
---

**Comment by kxkayser** [comment]
Hi Cornelius,

 

Thanks for your note.  When I say Alexa doesn’t see it I mean either she says no device called antenna or she emits a short blue light.  When this is happening, the device is not listed in the app Devices screen.  Once I change the punctuation of the node, say from antenna to Antenna or back again, it shows up in the Devices page and Alexa responds to commands.  I know it sounds weird but that’s what’s happening.  Seems now to behappening only with that device.  Previously it happened to the device “radio” which was a new device.  Thanks again

 

Ken Kayser

Tobaccoville, NC

 

 ***@***.***> ***@***.***

**Comment by csuermann** [comment]
What you describe sounds like your VSH "antenna" device somehow gets unregistered from Alexa. That would explain the behavior you experience as well as why I cannot find anything in the server logs. And when you redeploy the device, it gets registered again.

A VSH device should only ever get unregistered when you redeploy a Node-RED flow after deleting or disabling the the respective node.

It might be worthwhile enabling "debug" for your VSH Connection and checking your Node-RED CLI logs.

**Comment by kxkayser** [comment]
OK, I have set debug on and will wait for a failure and get back to you.  Thanks for your help

 

Ken Kayser

Tobaccoville, NC

 

***@***.***
