### ISSUE TITLE
[BUG] Color Changing Light Bulb not setting color related codes when instructed to switch to White

### ISSUE THREAD

**Issue by bummzulu** [csuermann/node-red-contrib-virtual-smart-home#221]
**Describe the bug**
when changing the color of the device either over voice or the Alexa app to a white color the only attribute changed in the payload is the "colorTemperatureInKelvin". The color settings stay unchanged.

e.g. setting it to daylight white:
`{"powerState":"ON","brightness":45,"colorTemperatureInKelvin":5500,"lightMode":"temp","color":{"hue":240,"saturation":1,"brightness":1},"source":"alexa","directive":"SetColorTemperature","name":"LedBandJana","type":"COLOR_CHANGING_LIGHT_BULB","color_rgb":[0,0,255],"color_hex":"#0000FF","color_cmyk":[100,100,0,0],"color_lab":[32,79,-108],"color_xyz":[18,7,95],"color_xy":[0.13550301400290363,0.03987867049354716],"rawDirective":{"directive":{"header":{"namespace":"Alexa.ColorTemperatureController","name":"SetColorTemperature","correlationToken":"SUdTVEs6AAE6AAg6eyJpZCI6Ijg1ZmYwMzIxLTg0MjUtNDIyZS1iNzcyLWE4MDE2MDJkNGFmMSIsInVyaSI6Imh0dHBzOi8vZC1hY3JzLWV1LXAtNWEzLTcxZDg2ZjQ1LmV1LXdlc3QtMS5hbWF6b24uY29tOjk0NDQiLCJzZXNzaW9uSWQiOiIwMGFlN2MyOC01MGMxLTQyNDQtOWI1Yy03ZDFlNmRkODdlYTkifQ=="},"endpoint":{"endpointId":"vshd-9a0a5c3bf0b40d7e"},"payload":{"colorTemperatureInKelvin":5500}}}}`

Setting it to warm white:
`{"powerState":"ON","brightness":45,"colorTemperatureInKelvin":2700,"lightMode":"temp","color":{"hue":240,"saturation":1,"brightness":1},"source":"alexa","directive":"SetColorTemperature","name":"LedBandJana","type":"COLOR_CHANGING_LIGHT_BULB","color_rgb":[0,0,255],"color_hex":"#0000FF","color_cmyk":[100,100,0,0],"color_lab":[32,79,-108],"color_xyz":[18,7,95],"color_xy":[0.13550301400290363,0.03987867049354716],"rawDirective":{"directive":{"header":{"namespace":"Alexa.ColorTemperatureController","name":"SetColorTemperature","correlationToken":"SUdTVEs6AAE6AAg6eyJpZCI6IjY0YjAwYjdjLTkxMTUtNGVmOS04YmZkLTAyNDM3N2RlZWQ1NSIsInVyaSI6Imh0dHBzOi8vZC1hY3JzLWV1LXAtNWMyLTc3ZWI1NGFlLmV1LXdlc3QtMS5hbWF6b24uY29tOjk0NDQiLCJzZXNzaW9uSWQiOiJlZGU5YzQwZi05MTE2LTRiOWYtYWNhNy1hZmYxNWM5Y2M2MWUifQ=="},"endpoint":{"endpointId":"vshd-9a0a5c3bf0b40d7e"},"payload":{"colorTemperatureInKelvin":2700}}}}`

**To Reproduce**
Control a virtual device of the type "Color Changing Light Bulb" over voice or the app and try to change the color over voice command or the Alexa app to a white color like: Warm white / Soft white / Daylight white / Cool white

Changing to other colors work fine.

**Expected behavior**
Color of the device to change to a white tone.

**Environment (please complete the following information):**
 - virtual-smart-home version: 3.0.12
 - Node-RED version: 3.1.1

**Comment by csuermann** [comment]
Hi @bummzulu,

Thanks for reaching out!

Various white tones, such as warm white, soft white, daylight white, etc., are indicated by different `colorTemperatureInKelvin` values under `lightMode` = "temp." However, VSH retains the state of any other non-active dimensions, such as `color`, `color_rgb`, etc. Therefore, to ensure the accurate configuration is transmitted to your physical lights, it's essential to always consider the respective `lightMode`.

**Comment by bummzulu** [comment]
Hi Cornelius, any hint how I can use Alexa to change the color to white then? How can I consider different lightModes?

**Comment by csuermann** [comment]
Hi @bummzulu,

Check out the examples you can import via the Node-RED UI (_Import > Examples > node-red-contrib-virtual-smart-home > color-changing-light-bulb_).

<img width="780" alt="image" src="https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/10939809/13839004-101d-44b5-aab6-c431798a15d0">

**Comment by bummzulu** [comment]
Great, thanks.

Am Mo., 11. Dez. 2023 um 08:36 Uhr schrieb Cornelius Suermann <
***@***.***>:
