### ISSUE TITLE
[BUG]Device loses status after a few seconds

### ISSUE THREAD

**Issue by Spunckie** [csuermann/node-red-contrib-virtual-smart-home#222]
I set up various devices via Node Red and also activated the Alexa skil. Alexa also recognizes the devices very quickly. For example, if I turn on or off a lamp or switch in the Alexa app, the status is only retained for a few seconds. After that, the device no longer has a status in the Alexa app. How can I keep the status permanently?

**Comment by csuermann** [comment]
Hi @Spunckie,

Try enabling the "retrievable" option on your VSH devices.
