### ISSUE TITLE
Problem with Registered Devices - limited to 7 on Pro subscription

### ISSUE THREAD

**Issue by callingsimon** [csuermann/node-red-contrib-virtual-smart-home#224]
Hi Cornelius
I've been using VSH on Node-red on Pi for a while and it works well. However, I've just tried to move my Node-red to a different Raspberry Pi and am having some problems. I'm now being restricted to 7 registered devices even though it recognises that I have Pro subscription:

![image](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/77575764/7067da37-f92f-42db-9739-76cb16b0b4aa)

Can you reset my device limit?

Thanks

Simon

**Comment by csuermann** [comment]
Hi @callingsimon,

Thanks for reaching out! The Pro plan should give you access to up to 200 virtual devices in total, regardless whether you use one or multiple Node-RED instances. For this to work you need to use the very same Amazon account during the account linking process.

What issue are you running into on your second Raspberry Pi? The screenshot you shared doesn't seem to show a problem?!

Also, could you please share your old and new "Thing ID"?

**Comment by callingsimon** [comment]
Hi Cornelius

Thanks for getting back to me so soon.

I had about 45 devices configured on my old Node-red.  I copied all the code to a new raspberry pi and created a new connection to the same Amazon account.  I then saw duplicates of all the devices - not surprising as two node-reds were now exposing them.  Unable to tell which duplicate was from old instance and which from new, I deleted all registered devices, shut down the old node-red and expected the devices to be re-created from the new instance when I re-deployed.  However, I'm only getting the 7 devices registered in the screenshot I sent earlier.

The Thing ID for the new server is:
[cid:24cc4ab5-c8b7-4277-83e6-03cc8bda15cf]
and the ID for the old server is:
[cid:2e26cab2-4129-457d-9733-b9d2b9949ff9]

I have re-started the old instance and it is showing the same 7 registered devices.  I'll shut it down again as I can understand that having the same devices being requested from two instances is not going to be helpful!

Thanks

Simon

________________________________

**Comment by csuermann** [comment]
Hi Simon,

> Unable to tell which duplicate was from old instance and which from new [...]

The "Registered Devices" table will show devices connected through another VSH connection with gray shaded background.

> The Thing ID for the new server is:
> [cid:24cc4ab5-c8b7-4277-83e6-03cc8bda15cf]
> and the ID for the old server is:
> [cid:2e26cab2-4129-457d-9733-b9d2b9949ff9]

These don't look like valid VSH Thing IDs. You'll find yours on the VSH connection page. They begin with "vsht-xxx".

**Comment by callingsimon** [comment]
Hi Cornelius

I'd sent the Thing IDs as screen shots, I guess the image embedding is causing the problem, so they are now as attachments.

I had assumed the grey background was just alternate rows in the table - because everything was duplicated, it was every other row!

With this knowledge, I deleted some of the greyed out devices from the seven that were showing as registered.  Now I have 4 registered devices, even thought he connection dialog says that 43 nodes are using it (screenshot attached).

How can I reset/resend the set of devices?  I'd assumed that Deploying the Node-red flow would do it (while doing its 'Initializing..')

Regards

Simon

________________________________

**Comment by csuermann** [comment]
Hi Simon,

Could you please reply through the GitHub user interface as GitHub strips attachments when you reply via email.

**Comment by callingsimon** [comment]
![Old instance](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/77575764/456cc843-a202-4094-bf1c-18d7c3917bd5)
![New Instance](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/77575764/728878c0-0c83-4ef7-989d-e70dc14fbeac)
![Registered devices](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/77575764/0668c9f3-4994-4268-a862-2d5b071c33ec)

**Comment by csuermann** [comment]
Thanks!

When you remove devices using the table in Node-RED, they are automatically unregistered from Alexa and deleted from the VSH server. However, it's crucial to also delete the corresponding nodes from your Node-RED flows. Failing to do so will result in their rediscovery, leading to their addition back into the VSH server database and re-registration with Alexa.

In the information you have provided thus far, I did not come across any indication that you indeed hit a limit of allowed devices.

**Comment by callingsimon** [comment]
The problem is they are not being re-discovered! I have 43 devices configured in Node-red but only 4 now registered in VSH.  I can't get the rest of them to be discovered since I deleted the registrations

**Comment by csuermann** [comment]
Redeplying your Node-RED flows doesn't fix it?

**Comment by callingsimon** [comment]
correct

**Comment by csuermann** [comment]
Could you please try to disable all your vsh-device nodes except one, and then re-deploy your Node-RED flows? Then disable the last node you left out, re-deploy again, enable it and re-deploy one last time.

**Comment by callingsimon** [comment]
Yay! That worked.  All my devices are now correctly registered and are linking to Alexa.

Thanks for your help, and thanks for a good product!

Simon

**Comment by csuermann** [comment]
Fantastic! Thanks for reporting back!
