### ISSUE TITLE
[BUG] Devices not discovered by Alexa

### ISSUE THREAD

**Issue by Tushky-Wolf** [csuermann/node-red-contrib-virtual-smart-home#225]
It seems like you're experiencing an issue where, in the Alexa app, irregularly, no devices are present within the skill. Node-RED is running, and all devices are available in the VSH Konto. The workaround is to reconfigure each routine again.

After performing a device search, they reappear again.

node-red v3.0.2
node-red-contrib-virtual-smart-home 3.0.6

**Comment by csuermann** [comment]
Hi @Tushky-Wolf,

Thanks for reaching out!

Allow me to ask a few follow-up questions:

- Could you please elaborate what you mean by "The workaround is to reconfigure each routine again."?
- Did your devices only appear from the Alexa **app** or did they get generally missing from Alexa?
- What did Alexa respond when you tried to control your devices?
- Did you have to re-enable the skill in Alexa to fix the issue?
- Did you have to re-deploy your Node-RED flows in order for the devices to re-appear or did it suffice to ask Alexa to search for new devices?
- You mentioned that the problem occurs "irregularly". Could you roughly specify how frequently this happens?

**Comment by Tushky-Wolf** [comment]
Could you please elaborate what you mean by "The workaround is to reconfigure each routine again."? -> translation error

Did your devices only appear from the Alexa app or did they get generally missing from Alexa? ->in both app and assistent

What did Alexa respond when you tried to control your devices? -> redirect me to my romba 

Did you have to re-enable the skill in Alexa to fix the issue? ->nein gerätesuche

Did you have to re-deploy your Node-RED flows in order for the devices to re-appear or did it suffice to ask Alexa to search for new devices? -> deploy no effect 

You mentioned that the problem occurs "irregularly". Could you roughly specify how frequently this happens? 3-4 months

**Comment by csuermann** [comment]
Thank you!

Device registration with Alexa occurs in only two scenarios:

**Explicit Deletion**: When you click the trash icon in the table listing your VSH devices in Node-RED. This action not only unregisters them from Alexa but also deletes them from the VSH database server. Consequently, Alexa won't be able to rediscover them in subsequent searches. We can therefore rule out this scenario.

**Flow Re-deployment**: If you re-deploy a Node-RED flow with fewer vsh-devices linked to the respective vsh-connection than before. This ensures that Alexa's records stay synchronized with changes made on your Node-RED canvas.

The only other plausible explanation remaining is that the devices were potentially deleted directly from Alexa, either manually or due to some form of bug.

**Comment by satchafunkilus** [comment]
I experienced the same issue. Tried deleting the skill from Alexa and re-adding it, also tried deleting the connection in node-red and re-adding it, devides still did not reappear in alexa.

What helped me in the end was an update of nodered. I'm on 3.1.3 now and devices reappeared, once the update was installed.

**Comment by ThetaGamma** [comment]
I have the same issue. In Nodered the vsh objects are shown as "online", but no device is recognized by Alexa. I tried restart node-red (V3.1.3 BTW), redeploy in Nodered, "discover devices" in Alexa- no result, devices are not available.

**Comment by csuermann** [comment]
Could you please post your ThingID so that I can investigate?

**Comment by ThetaGamma** [comment]
Sure! hopefully not giving away sensitive information by posting it publicly: vsht-afb5ce5c-cb47-41be-ad31-09908a1e5b6c

**Comment by csuermann** [comment]
Thank you. No worries, ThingID are not confidential.

It appears that you have two vsh-connections with duplicated vsh-device IDs linked to them. This is resulting in an error during Alexa's device discovery process:

> "Multiple endpoints cannot have the same endpointId."

To resolve this issue, you should recreate the non-unique vsh-devices. Please note that the vsh-deviceID is composed of the prefix "vshd-" followed by the Node-RED node ID, which ideally should be unique per Node-RED instance. Are you by any chance running two separate Node-RED instances?

**Comment by ThetaGamma** [comment]
[..]
> To resolve this issue, you should recreate the non-unique vsh-devices. Please note that the vsh-deviceID is composed of the prefix "vshd-" followed by the Node-RED node ID, which ideally should be unique per Node-RED instance. 

Thx! By "recreating" you mean delete the vsh object (e.g. "Stehlampe")  in Nodered and create it again? Or is there a way to remove all vsh connections and start registering from scratch?

> Are you by any chance running two separate Node-RED instances?

No, it's definitely only one instance. (within IOBroker) But some weeks ago, during upgrade to Nodered 3.x, I had issues with vsh not working anymore due to missing passwords and I remember I had several tries to reconnect again. Funny thing is: everything worked when I left home for Christmas...

**Comment by satchafunkilus** [comment]
> No, it's definitely only one instance. (within IOBroker) But some weeks ago, during upgrade to Nodered 3.x, I had issues with vsh not working anymore due to missing passwords and I remember I had several tries to reconnect again. Funny thing is: everything worked when I left home for Christmas...

I have the exact same setup, so it might indeed be related to the recent iobroker adapter upgrades... Also had the same issues with having to re-enter several passwords for a couple of times.

**Comment by csuermann** [comment]
> By "recreating" you mean delete the vsh object (e.g. "Stehlampe") in Nodered and create it again? Or is there a way to remove all vsh connections and start registering from scratch?

1. delete the 2nd vsh-connection (the one that has only 6 devices attached) by clicking the "Delete" button in the "Edit connection node" page in Node-RED.
2. Delete the following vsh-device nodes from your Node-RED canvas that should now no longer have a vsh-connection configured: Warmwasser, TH5, TH6, TH7, Außenküche.
3. Open the details page of your remaining vsh-connection and click the trash icon next to the 6 rows with grey background. They belong to the other, now deleted connection. Deleting them from the table also unregisters them from Alexa.
4. create new vsh-device nodes in Node-RED for these duplicate ones and link them to your single remaining connection:
  1. `vshd-71900e2c57b1eeb2` (Warmasser, Heizung Warmwasser)
  2. `vshd-9dedb30d8ac5b242` (TH7 & Badezimmer)
  3. `vshd-aac374655c5cf058` (TH5 & Schlafzimmer)
  5. `vshd-af0aa4778c136105` (TH6 & Arbeitszimmer Keller)
  6. `vshd-e14caf34f88d844f` (Außenküche & Außenküche)

Good luck!

**Comment by ThetaGamma** [comment]
Happy New Year!
-> Step 1: I only had 1 connection there. I deleted it, hence I didn't have any connection to vsh in the dropdown
-> Step 2: This would have meant to delete all, as none has a valid connection
-> Step 3+4 can not be done 

I created  a new connection and got thing ID vsht-4ee41c29-440b-4b7a-9cae-649f78976c5b
now it's working but I still have some elements doubled (e.g. "Stehlampe")
Thanks!

**Comment by csuermann** [comment]
Happy New Year to you, too!

I've just removed your outdated devices from the database and initiated an Alexa device discovery process, which appears to have resolved the issue. Your account now has one connection with 14 registered devices.

**Comment by csuermann** [comment]
Closing this for now. The latest VSH version (4.0.0) shows duplicated device IDs, which seem to be the culprit of this issue, in the Node-RED UI.
