### ISSUE TITLE
Retrieving the temperature from our dining room Echo Dot

### ISSUE THREAD

**Issue by invictagunner** [csuermann/node-red-contrib-virtual-smart-home#227]
I am developing an automation of our heating system (as a novice!!!) which requires determining room temperatures. Some time ago I decided to use Echo dot as the temperature sensor. Alexa via voice control or the app retrieves the temperature very reliably. I now want to use the temperature in a node red flow. I have  **node-red-contrib-virtual-smart-home 3.0.12** installed and can add virtual devices to the flow. These appear in Alexa. However I have now realised this is not an answer to my requirement. The examples contain references to '"name": "Alexa, what's the temperature of pizza oven?" for example. Am I still able to do this type of retrieval, or does it require the new PRO option?
Any advice gratefully received.
Node-RED version: v3.1.3

**Comment by csuermann** [comment]
Hi @invictagunner,

As the name implies, "*Virtual* Smart Home" allows you to configure _virtual_ devices that can be controlled by Alexa. For example you can create a virtual light that you can control by saying "Alexa, switch light on" which will result in a msg getting emitted from the virtual device node in Node-RED. You can then handle that message in Node-RED, e.g. to actually switch on a physical light. You can also configure virtual sensors, e.g. temperature sensors, in Node-RED, pass it msg objects with temperature values which will can then be retrieved by Alexa (e.g. "what's the temperature in the living room?").

Your use case sounds like you want to query the state of a _physical_ sensor (Echo Dot) for which VSH is not a viable option.

**Comment by invictagunner** [comment]
Thank you very much for the prompt answer. Yes it makes sense and I have added a virtual thermostat which is working well. The only item missing now is the temperature sensor which I originally thought would be one of the easiest. Very impressed with your integration with Amazon/Alexa. Thank you. Happy to go pro if there is ever a chance to retrieve device parameters such as temperature from Echo dot. If anyone has got any ideas they would be greatfully received.

**Comment by csuermann** [comment]
I haven't tried it, but perhaps this [package](https://flows.nodered.org/node/node-red-contrib-alexa-remote2) might do the trick for you?!

**Comment by WarNeedle** [comment]
I would avoid that version as it hasn't been updated recently. 
The applestrudel fork is currently being maintained so you may have move luck there.
https://flows.nodered.org/node/node-red-contrib-alexa-remote2-applestrudel

**Comment by invictagunner** [comment]
Thank you. I noticed the same and have tried the applestrudel version. Some of it works OK but authenticating with Amazon was a challenge and I have to repeat this step very frequently. In my case, asking Alexa for the temperature of the sensor in the Echo Dot  causes the expected audible response but the Device Activity setting in the Alexa Event Node seems to have stopped working sometime ago and, as yet, has not been fixed. This means that the verbal message containing the temperature is not made available in Node Red (via Debug). Generally, it does not look a very reliable package. Thanks again for your input.

**Comment by WarNeedle** [comment]
Unfortunately Amazon changed something a while ago that broke the device activity part.
It's still useful for sending voice notifications to the echos.

**Comment by smcgann99** [comment]
> Device Activity setting in the Alexa Event Node

This should be fixed in the latest release of the applestrudel version
