### ISSUE TITLE
Blinds-type devices do not support the 'stop' command on Alexa

### ISSUE THREAD

**Issue by christianbalz** [csuermann/node-red-contrib-virtual-smart-home#229]
**Describe the bug**
When asking Alexa to open and close the curtain, everything works fine. However, when requesting to "stop" the curtain, it is the closing command that is mistakenly executed.

**To Reproduce**

1. Add a virtual device node
2. Set the type as blinds
3. Add a debug node
4. "Alexa, open curtain" (works fine)
5. "Alexa, close curtain" (works fine)
6. "Alexa, stop curtain" (executes the closing command)
7. "Alexa, set curtain to 73%" (works fine)

**Expected behavior**
It is expected that the curtain stops when requested through Alexa.

**Screenshots**
![image-01](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/26635391/f37ea8d7-f442-42e3-bd93-ae7cc931c417)

![image-02](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/26635391/42a17943-0603-4d6f-8099-3fabe6ae5d97)

**Environment (please complete the following information):**

- virtual-smart-home version: 4.0.0
- Node-RED version: 3.1.3

**Additional context**
1. I have some Sonoff Dual R3 devices, and I can simulate the commands to open, close, and stop with Alexa.

2. I am using a Zigbee + RF curtain switch module Moes MS-108ZR, which is designed to support three states: open, close, and stop.

**Comment by jpadie** [comment]
@csuermann @christianbalz 
perhaps adding a powerController interface to the endpoint template would be an idea.   
some logic could sit in node-red to cut power to the blinds or send a position adjustment to the then current location of the blind.

**Comment by christianbalz** [comment]
Hello, I'm revisiting the previously reported issue where the "stop" command for the curtains via Alexa was mistakenly interpreted as a closing command. I would like to know if there have been any progress or updates in recent versions that now allow proper support for the "stop" command. Thank you in advance for your attention and for the continued development of this component.

**Comment by csuermann** [comment]
Hi @christianbalz! Unfortunately no progress was made on this issue. Unless Amazon adds official support to the Alexa API for stopping curtains / blinds etc. I'm not sure how VSH could fix this.

**Comment by jpadie** [comment]
> Hello, I'm revisiting the previously reported issue where the "stop" command for the curtains via Alexa was mistakenly interpreted as a closing command. I would like to know if there have been any progress or updates in recent versions that now allow proper support for the "stop" command. Thank you in advance for your attention and for the continued development of this component.

@christianbalz there are ways to make this work with vsh.  The easiest is to add an onoff virtual device and link the off state (in node red) to the stop command of your ZigBee window covering node.  The Alexa utterances would reference the name of that onoff device.   So it would be open the curtains and then maybe stop the motor.

As an alternative the matter protocol supports stopMotion and I have built synthetic matter window covering devices in node red that function with Alexa and other ecosystems.  I have not tried the stopMotion command and as @csuermann says, if Amazon have not augmented their NLP to include this utterance then you're stuck with the UI or a workaround
