### ISSUE TITLE
Node not sending any message if "Emit only changed attributes" is checked

### ISSUE THREAD

**Issue by nicedevil007** [csuermann/node-red-contrib-virtual-smart-home#23]
Hey @csuermann,

you added this awesome feature by my request a couple days ago. Maybe it is not absolutly working as it should be.
The intention was to only send the payload that needed to do the request of the user.

So here an example:

I turn on the lights in the kitchen with my smart switch at the wall. Then I tell alexa to turn off the light in the kitchen. Nothing will happen if the new option is enabled.

Why will this happen: I think you made the logic as this that alexa knows the last state that she did for the user to turn on or turn off the lights f.e. And if this status isn't changed it won't send any message. (That is what your option is telling me right).

Here just to clear things up:

- your node should send only that part that is told to alexa like turn on or turn off or change brightness etc.
- if I turn the lights on it wouldn't be neccessary to send a message with the last color saved in alexa, only send the powerState
- if I change the brightness it should only send the brightness instead of the powerState and color_temp and so on

Would this be possible as well?

**Comment by csuermann** [comment]
You're right, the behavior was not yet quite what you wanted. But I think in v1.18.1. it is. Let me know!
