### ISSUE TITLE
Node Red Crash - Alexa related?

### ISSUE THREAD

**Issue by invictagunner** [csuermann/node-red-contrib-virtual-smart-home#230]
Node Red crashes with an uncaught exception.

12 Jan 02:09:00 - [error] Error: getaddrinfo ENOTFOUND bob-dispatch-prod-eu.amazon.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)

The only Alexa interaction in my flows is via node-red-contrib-virtual-smart-home

I did a fair amount of testing yesterday and a quick Google throws up some indication of Amazon using blacklisting techniques.

I am way out of my depth but thought it was worth a quick post.

12 Jan 10:46:55 - [info] Node-RED version: v3.1.3
12 Jan 10:46:55 - [info] Node.js  version: v20.10.0
12 Jan 10:46:55 - [info] Windows_NT 10.0.19045 x64 LE
3.	node-red-contrib-virtual-smart-home 3.0.12

**Comment by csuermann** [comment]
Hmm, that domain is not referenced anywhere in the VSH codebase. Do you happen to have a stack trace for that error?

**Comment by invictagunner** [comment]
I was running it from the command line and struggling with some JSON syntax. The frequent warning I know about and have now removed. I cannot find any other log but have attached the console messages.
[Windows PowerShell_errors_110124.docx](https://github.com/csuermann/node-red-contrib-virtual-smart-home/files/13923094/Windows.PowerShell_errors_110124.docx)

**Comment by csuermann** [comment]
Thank you. I couldn't find any reference to `node-red-contrib-virtual-smart-home` in your logs. Instead, there are some hints you're actually using `alexa-remote`?!

**Comment by invictagunner** [comment]
Thank you. You are right that the remote-applestrudel palette is loaded on my system but not used in any of the flows that I actually use. I have made very good use of node-red-contrib-virtual-smart-home in my live flows (thank you) and did do a lot of testing during the day before the uncaught exception. At the time of failure 2:09 nothing would have been happening with the flows. The system ran fine last night and was still up this morning. I will continue to monitor and to simplify things completely remove the Alexa remote palette from the system. Thanks again.
