### ISSUE TITLE
FEATURE REQUEST Alarm/Timer

### ISSUE THREAD

**Issue by invictagunner** [csuermann/node-red-contrib-virtual-smart-home#231]
I am developing a heating control system using vsh. The thermostat feature has been a key building block.

At the moment I am using hard coded times in my model. For example, at 08:00 set mode to HEAT. This is used to do a morning boost after the overnight COOL mode.

Rather than use a hard coded time I would like vary it according to when we are planning to get up. Therefore an alarm/timer type feature would be very useful.  This could be used to set a WAKEUP time for example. Before going to bed we would say Alexa set _VshTimer_ to WAKEUP at 8:00. 

In the heating logic the hard coded 8:00 would be replaced by the value from the timer.

Alternatives considered are using Alexa's built in alarm but I have not found a reliable way to get this value into Node Red. This is similar to not being able to retrieve the room temperature from the Alexa Echo temperature sensor. I am still looking for a good solution to this.

**Comment by csuermann** [comment]
Hi @invictagunner!

That is a nice idea indeed. Unfortunately I doubt it would technically be possible as VSH is constrained to what the Alexa smart home API offers. If you happen to have more information how this could be accomplished, I would be curious to learn about it.

**Comment by invictagunner** [comment]
I have found a way using an Android based alarm system which can pass the wake up time (with an offset to put the heating on in advance) to Node Red via MQTT. It works very well.
