### ISSUE TITLE
v4.2.1: Metadata field causing "device not responding"

### ISSUE THREAD

**Issue by umibozu83** [csuermann/node-red-contrib-virtual-smart-home#233]
I updated to version 4.1.2. Before then everything worked fine. Now any command I do on Alexa returns me "device not responding". I saw that in the us it compulsorily asks me for metadata, but before it was not essential; in the documentation you released and in the examples it requires configuration, how should I compile them?

![mio](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/39552398/61ecff7c-f3bd-4fbe-a0db-2cb33e8a84fd)

- virtual-smart-home version: 4.2.1
- Node-RED version: 17.0.3
- Node.js version: [e.g. 18.0]
- Thing ID: [e.g. vsht-...]

**Comment by csuermann** [comment]
Hi @umibozu83,

The new metadata field is optional. You can use it to have additional JSON data being output by VSH nodes which can be handy for example for routing purposes. I personally use it to carry data I can feed into a home assistant node for controlling lights, e.g. 

```JSON
{
    "domain": "light",
    "entityId": "kitchen"
}
```

Your screenshot seems to show an invalid value "`[Object Object]`". I wonder how this got there? Can you please try removing it?

**Comment by umibozu83** [comment]
even when deleting it always makes the same error, however if I write any value the error disappears

**Comment by MartinJura** [comment]
Same here. For whatever reason Metadata seems to be a mandatory field now, indicated by red frame.
Leaving metadata empty leads to an invalid node.

I am using VSH 4.1.2 / NodeRed 3.1.3

**Comment by MartinJura** [comment]
Found the problem in my case: I moved NodeRed to a new hardware. Metadata is an empty string, but should be an empty JSON {}.
After opening the editor and entering {} the node is no longer marked as invalid.

**Comment by csuermann** [comment]
Thanks for reporting this issue. I just released v4.1.3 which should fix that.
