### ISSUE TITLE
Thermostat set temperature response

### ISSUE THREAD

**Issue by invictagunner** [csuermann/node-red-contrib-virtual-smart-home#234]
I am using the virtual thermostat device and am a bit confused about Alexa's response to setting the temperature.

I say to Alexa set the cool room temperature to 20. The correct virtual thermostat is actioned.

Alexa's response to this is "Its Off".

However, the temperature is passed correctly to Node Red as 20 so the flow behaves correctly. It would be nice if the Alexa reply made more sense in the context of the action requested. For example, "Its Set" would be better. "Its set to 20" would be perfect.

**Comment by csuermann** [comment]
Hi @invictagunner,

Alexa's response is indeed rather irritating here. To fix it, I believe you need to set `payload.thermostatMode` once to something different than "off". You might find the thermostat example flow helpful which ships with this package and can be imported via the Node-RED menu `Import > Examples > node-red-virtual-smart-home > thermostat`.
