### ISSUE TITLE
Moving my node red iobroker flows over to another PC - not working anymore? Metadata field red?

### ISSUE THREAD

**Issue by Pino72de** [csuermann/node-red-contrib-virtual-smart-home#235]
I moved iobroker and node red over from one windows pc to another. I deleted all old dependencies which were greyed out and he discovers the new ones but there seems to be a problem with the new field Metadata which I did not have on the old installation?

![grafik](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/102967086/c5bb001f-44d9-480c-82c4-8af6b1782749)

Alexa app does find the new switch but is not responding when I want to turn it on or off. Also in node red there are these red triangles showing me that the node is not correctly configured?? Switch in the Alexa app is also not working...so there seems to be trouble with the connection to VSH?

![grafik](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/102967086/b28ea0a1-0157-48b3-ab6a-887eb3f577a5)

What is missing?

**Environment (please complete the following information):**

- virtual-smart-home version: no idea...
- Node-RED version: 4.1.3 old one was 3.0.9
- Node.js version: Node.js: v18.19.0
NPM: 10.2.3
Thing ID: vsht-d7e8349c-eab6-45da-ba24-b59c2d01fc48

Thanks

**Comment by csuermann** [comment]
Hi @Pino72de,

I'm very sorry for the inconvenience. Could you please try to just enter `{}` into the metadata field? Alternatively, update to the latest version of VSH (published today) that should fix the issue.

Hope that helps!

**Comment by Pino72de** [comment]
Hey Cornelius,Danke für die schnelle Hilfe, mit den Klammern geht es :-).Danke+LgAm 26.01.2024 um 18:38 schrieb Cornelius Suermann ***@***.***>:﻿
Hi @Pino72de,
I'm very sorry for the inconvenience. Could you please try to just enter {} into the metadata field? Alternatively, update to the latest version of VSH (published today) that should fix the issue.
Hope that helps!
