### ISSUE TITLE
how to disable the message rate limiter

### ISSUE THREAD

**Issue by jpadie** [csuermann/node-red-contrib-virtual-smart-home#237]
taking a thermostat node as an example, if I open the alexa app to view the thermostat then it does not take long until the message rate limiter kicks in and reports the thermostat as unresponsive.

(on a self-hosted backend) what is the correct way of preventing message limiting?

**Comment by csuermann** [comment]
The rate limiter configuration is hard-coded in the [backend code](https://github.com/csuermann/virtual-smart-home/blob/master/handler.ts#L363-L407). You'd have to adjust this according to your needs. Here is the documentation for the various settings: [Bottleneck](https://github.com/SGrondin/bottleneck?tab=readme-ov-file#docs)
