### ISSUE TITLE
Temp Sensor example Anomalies

### ISSUE THREAD

**Issue by Raibeart-Bruis** [csuermann/node-red-contrib-virtual-smart-home#24]
I am checking out your Node-RED vsh-virtual-device node and so far looks like it will perform nicely for me!

I did however discover some anomalies with the Temperature Sensor example from node-red-contrib-virtual-smart-home/examples/temperature-sensor.json.  In summary, for msg.payload.scale of FAHRENHEIT, KELVIN and Kelvin it consistently provides an incorrect result as if these are treated as reserved or special strings.

Using the sample provided, I got the following results:

Regardless of the msg.payload.scale entered into the "measured temp = 220.5 °C" inject node, I got the correct result for spoken by Alexa:
> From inject node: {"temperature":220.5,"scale":"CELCIUS"}, Alexa response: The pizza oven temperature is 220.5 degrees
> From inject node: {"temperature":220.5,"scale":"Celcius"}, Alexa response: The pizza oven temperature is 220.5 degrees
> From inject node: {"temperature":220.5,"scale":"abcdef"}, Alexa response: The pizza oven temperature is 220.5 degrees

For the msg.payload.scale entered into the "measured temp = 430 °F" inject node, I got the correct result for spoken by Alexa for anything other than "FAHRENHEIT"
> From inject node: {"temperature":430,"scale":"FAHRENHEIT"}, Alexa response: The pizza oven temperature is 221.5 degrees
> From inject node: {"temperature":430,"scale":"Fahrenheit"}, Alexa response: The pizza oven temperature is 430 degrees
> From inject node: {"temperature":430,"scale":"abcdef"}, Alexa response: The pizza oven temperature is 430 degrees

For the msg.payload.scale entered into the "measured temp = 495 K" inject node, I got the correct result for spoken by Alexa for anything other than "KELVIN|Kelvin" where 
> From inject node: {"temperature":495,"scale":"KELVIN"}, Alexa response: The pizza oven temperature is 221.9 degrees
> From inject node: {"temperature":495,"scale":"Kelvin"}, Alexa response: The pizza oven temperature is 257.2 degrees
> From inject node: {"temperature":495,"scale":"abcdef"}, Alexa response: The pizza oven temperature is 495 degrees

**Comment by csuermann** [comment]
Hi @Raibeart-Bruis,

The "scale" attribute supports only "CEL**S**IUS", "FAHRENHEIT" and "KELVIN" (all uppercase). All other values will silently be ignored and not lead to a state change. I think this is what you're experiencing here, as Alexa simply reports the old sensor value which has not been overridden by the invalid inject.

Although you can inject temperature readings in different scales, Alexa will always output its equivalent in the measurement unit configured for your Alexa device, e.g. Echo.
