### ISSUE TITLE
Disconnected periodically retrying

### ISSUE THREAD

**Issue by slopsjon** [csuermann/node-red-contrib-virtual-smart-home#244]
### Bug Description

Feb 14 14:07:52 HAPi node-red[8505]: 14 Feb 14:07:52 - [info] [vsh-connection:email@email.com] MQTT: connection offline
Feb 14 14:08:22 HAPi node-red[8505]: 14 Feb 14:08:22 - [info] [vsh-connection:email@email.com] MQTT: reconnecting...
Feb 14 14:08:22 HAPi node-red[8505]: 14 Feb 14:08:22 - [info] [vsh-connection:email@email.com] MQTT: connected to a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883
Feb 14 14:08:22 HAPi node-red[8505]: 14 Feb 14:08:22 - [info] [vsh-connection:email@email.com] MQTT: publish to topic $aws/things/vsht-74a6a4ce-8b43-4528-aba7-581cc0a0d046/shadow/update: {"state":{"reported":{"connected":true,"vsh_version":"4.1.5","nr_version":"3.1.5"}}}

This keeps happening every couple of minutes for about twenty seconds.

Never noticed it before, and now devices obviously become unresponsive for a while.

### To Reproduce

Only noticed over the last coupe of updates. All the nodes display "Disconnected periodically retrying" until connected again.

### Expected behavior

I would not expect it to disconnect every couple of minutes.

### Virtual-Smart-Home Version

4.1.5

### Node-RED Version

3.1.5

### Node.js Version

20.6.1

### Plan

PRO

### Thing-ID

vsht-74a6a4ce-8b43-4528-aba7-581cc0a0d046

**Comment by csuermann** [comment]
Hi @slopsjon,

Thanks for reaching out. AWS force-disconnects MQTT connections when there is another connection attempt with identical credentials. Could that be the culprit here? I've seen this being the problem in the past when users cloned their Node-RED settings and ended up with 2 instances competing for the connection.

**Comment by csuermann** [comment]
I have observed your connection for the last 20 minutes and not seen any disconnects. Is this one of these issues that disappear as soon as you look at it?

**Comment by slopsjon** [comment]
Yes, it has stopped disconnecting. The last disconnect was 15:01. I've not changed anything, every time I looked at the nodes, they would disconnect.

**Comment by dcbo** [comment]
I am facing the same problem. 

I had been using node-red-contrib-virtual-smart-home for over a year. 

However, I recently switched from NodeRed to HomeAssistant and started testing 
the Alexa integration from HomeAssistant. As a result, I uninstalled the skill 
from my Alexa devices. Unfortunately, it turned out that the HomeAssistant 
Integration does not meet my needs, so I reactivated  node-red-contrib-vsh. 

Everything seems to be working fine, but every couple of hours, I lose 
connection and Alexa says: "[Devicename] antwortet nicht, bitte überprüfe 
die Netzwerkverbindung und Stromversorung des Geräts" 

When I restart the integration by redeploying some changes in NodeRed, it works 
fine again. 

Here is my log:
- At 25th February 10:08:13 and 25th February 10:51:32, I issued two commands.
- At 25th February 18:03:32, I tried again and received the error message 


```
25 Feb 10:08:13 - [info] [vsh-connection:AMAZON-ACCOUNT] MQTT: message received on topic vsh/vsht-a797a03f-222b-42[...] 
25 Feb 10:08:13 - [info] [vsh-connection:AMAZON-ACCOUNT] MQTT: publish to topic vsh/vsht-a797a03f-222b-42a7-8ef3-c[...]
25 Feb 10:51:32 - [info] [vsh-connection:AMAZON-ACCOUNT] MQTT: message received on topic vsh/vsht-a797a03f-222b-42[...]
25 Feb 10:51:32 - [info] [vsh-connection:AMAZON-ACCOUNT] MQTT: publish to topic vsh/vsht-a797a03f-222b-42a7-8ef3-c[...]
25 Feb 11:00:00 - [error] [alexa-remote-other:bb3ed8c68a6a36ee] account not initialised
25 Feb 11:48:52 - [error] [alexa-remote-init:5748750063be58ed] account must be initialised before refreshing
25 Feb 15:48:52 - [error] [alexa-remote-init:5748750063be58ed] account must be initialised before refreshing
Unhandled rejection RequestError: Error: read ECONNRESET
    at new RequestError (/data/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/data/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/data/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/data/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/data/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
25 Feb 18:03:32 - [info] [vsh-connection:AMAZON-ACCOUNT] MQTT: connection offline
25 Feb 18:04:02 - [info] [vsh-connection:AMAZON-ACCOUNT] MQTT: reconnecting...
25 Feb 18:04:02 - [info] [vsh-connection:AMAZON-ACCOUNT] MQTT: connected to a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883
25 Feb 18:04:02 - [info] [vsh-connection:AMAZON-ACCOUNT] MQTT: publish to topic $aws/things/vsht-a797a03f-222b-42a7-8ef3-cf0e38b1dbb2/shadow/update: {"state":{"reported":{"connected":true,"vsh_version":"4.1.5","nr_version":"3.1.3"}}}
25 Feb 19:48:52 - [error] [alexa-remote-init:5748750063be58ed] account must be initialised before refreshing

```

**Comment by dcbo** [comment]
Just noticed,  that a newer version of VSH is available! 
Started the Upgrade from 4.1.5 to 4.1.10  (nr_version:3.1.3)
Will see, if it solved the problem.

**Comment by csuermann** [comment]
I believe this issue was fixed with a recent release of VSH. Please lease a comment here if you're still experiencing frequent disconnects.

**Comment by slopsjon** [comment]
Hi, still disconnecting, has been all day.

**Comment by csuermann** [comment]
@slopsjon,

Previously you mentioned

> This keeps happening every couple of minutes for about twenty seconds.

Since you updated to VSH v4.1.12, my logs only show 2 reconnections at

- 2024-02-29T10:49:28.998Z
- 2024-02-29T19:45:23.805Z

As long as there are just a few reconnections per day, we can consider the issue resolved.
