### ISSUE TITLE
Migrating flows to other Node-RED instance invalidates FREE plan

### ISSUE THREAD

**Issue by jowi1968** [csuermann/node-red-contrib-virtual-smart-home#247]
### Bug Description

I was running Node-RED as an add-on in HA, but i am in the progress of migrating all flows to a separate Node-RED VM (on UNRAID). If i copy a flow containing VSH nodes from the add-on NR to the VM-NR, and after doing the account-linking via amazon etc. it considers the VSH nodes in the new VM as new ones and the free plan limit is enforced.

So it is no problem to use the same 7 FREE VSH nodes in the same Node-RED instance multipe times, but you can't use the same 7 FREE nodes in multiple Node-RED instances? Despite the account-linking?

How do i fix this? And is this also an issuw with the paid subscription?

### To Reproduce

- Use all 7 free nodes
- copy flow containg free nodes to 2nd instance of node-red

### Expected behavior

I expect all 7 free nodes to be available in every instance of Node-RED i'm using, or at least be able to transfer them to another instance.

### Virtual-Smart-Home Version

4.1.2

### Node-RED Version

3.1.5

### Node.js Version

16.20.0

### Plan

FREE

### Thing-ID

vsht-a123c2a9-fe91-4920-aa4b-2a82fee6a4f7

**Comment by csuermann** [comment]
Hi @jowi1968,

The device limit is per account, not per Node-RED instance. When you open the vsh-connection details on your new VM-NR, you should see a table with all devices registered for your account. Once you no longer need your old NR, you can delete obsolete devices from the table. This will also unregister them from Alexa and free up your device limit again.
