### ISSUE TITLE
Alexa says device "isn't responding" for all devices

### ISSUE THREAD

**Issue by PlanoPilot** [csuermann/node-red-contrib-virtual-smart-home#248]
### Bug Description

In a previously working installation, attempting to activate a VSH device with Alexa results in the reply, "[virtual device] isn't responding, please check its network connection and power supply". All devices get the same message. This started earlier today. 

In the VSH config node, all of my registered devices have been duplicated, resulting in non-unique device IDs:

![Screenshot 2024-03-02 at 4 28 44 PM](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/161981046/b3ddecc9-ed31-4af5-9442-16bce67c1ec9)

I did not do this myself. In fact, I haven't even accessed the RPi in the last couple of days. Somehow it was caused by software.

Deleting one of the duplicate devices from the VSH config node does NOT restore functionality. Instead, Alexa reports that it can't find the device.

### To Reproduce

1. Verify RPi has good internet connection.
2. "Alexa, turn on [device name]"
3. Alexa responds "[device] isn't responding, please check its network connection and power supply".
4. Device can still be activated from Node-RED dashboard.

### Expected behavior

The virtual device should be turned on or off (or whatever the command to Alexa was), and Alexa should respond "OK".

### Virtual-Smart-Home Version

4.1.12

### Node-RED Version

3.0.2

### Node.js Version

16.17.1

### Plan

PRO

### Thing-ID

vsht-46680804-1f7a-421a-8902-bda877ff441f

**Comment by csuermann** [comment]
Hi @PlanoPilot,

Upon reviewing the backend, I noticed that your account is associated with _two_ ThingIDs:

1. `vsht-19088df3-f515-49b1-9129-cec4a91675cd`
    - Created at: 2024-01-08T17:23:56.000Z
    - VSH Version: 4.1.2
    - Connection Status: Not connected (since 2024-02-28T20:51:50.000Z)

2. `vsht-46680804-1f7a-421a-8902-bda877ff441f`
    - Created at: 2024-02-28T21:50:32.000Z
    - VSH Version: 4.1.12
    - Connection Status: Connected (since 2024-03-03T04:52:07.000Z)

It appears that you may have undergone the account linking process twice, resulting in the issuance of the second ThingID/vsh-connection, possibly after upgrading to VSH v.4.1.12 on February 28. I presume that you subsequently reconfigured all your existing VSH devices to utilize the new vsh-connection, leading to duplicates in the server database.

In any case, I have just removed all duplicates from the server, and anticipate that your setup should now operate smoothly again.

**Comment by PlanoPilot** [comment]
Hi @csuermann. Thanks for the quick reply. Yes, I had to restore my RPi from a backup image on February 28, and that's when I re-linked the account. 

After you deleted the duplicate connection, I did have to ask Alexa to "discover new devices" again, but after that all worked normally.

Thanks again for the help and for creating such a great skill!

**Comment by csuermann** [comment]
Thanks for reporting back. Glad to hear everything is back to normal! 🎉

**Comment by andrecamper** [comment]
Hello @csuermann, first of all congrats for the development! Very nice node and flows! The cost is quite fair!

I'm going through the very same situation as my friend described. Probablly there are two users there because i had to replace my old raspberry... Can you please delete all of them so I start another one from the nodes i have in my backup?

Best regards

**Comment by csuermann** [comment]
Hello @andrecamper,

You might find that you can resolve the issue by removing any duplicate devices (marked with a gray background) from the table in the vsh-connection details. If this doesn't resolve the issue, please share your ThingID with me so I can investigate further.

**Comment by andrecamper** [comment]
Hello Cornelius,
how's it going?!?
I tried to install the update today but got hte issue below:


 2025-05-15T14:54:26.957Z Instalar : node-red-contrib-virtual-smart-home 4.4.7
2025-05-15T14:54:33.041Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict ***@***.***:54:35.455Z [err] npm2025-05-15T14:54:35.457Z [err]  2025-05-15T14:54:35.458Z [err] WARN config production Use `--omit=dev` instead.2025-05-15T14:54:42.685Z [out] 2025-05-15T14:54:42.685Z [out] up to date in 7s2025-05-15T14:54:42.718Z rc=0


I'm really afraid i have lost all the configurations i did... What would you suggest me?
best regards,
André



    Em domingo, 17 de março de 2024 às 04:18:40 BRT, Cornelius Suermann ***@***.***> escreveu:  
 
 


Hello @andrecamper,

You might find that you can resolve the issue by removing any duplicate devices (marked with a gray background) from the table in the vsh-connection details. If this doesn't resolve the issue, please share your ThingID with me so I can investigate further.

**Comment by csuermann** [comment]
Hi @andrecamper,

The logs you shared look normal and do not indicate that the installation failed. Is the functionality of VSH impaired in any way?

Best
Cornelius

**Comment by andrecamper** [comment]
Hi Cornelius,
wha do you mean by "impaired"?
Best regards,
André
    Em quinta-feira, 15 de maio de 2025 às 15:30:19 BRT, Cornelius Suermann ***@***.***> escreveu:  
 
 csuermann left a comment (csuermann/node-red-contrib-virtual-smart-home#248)
Hi @andrecamper,

The logs you shared look normal and do not indicate that the installation failed. Is the functionality of VSH impaired in any way?

Best
Cornelius

**Comment by andrecamper** [comment]
Hello Cornelius,
i have been able to properly reinstall the node...
Now i'm having a hard time to link my account. Even thought i folow the steps bellow it always lose the conection bring me back to the screen below every time i implement th echanges.



what should i do differently?
best regards,
    Em quinta-feira, 15 de maio de 2025 às 15:30:19 BRT, Cornelius Suermann ***@***.***> escreveu:  
 
 csuermann left a comment (csuermann/node-red-contrib-virtual-smart-home#248)
Hi @andrecamper,

The logs you shared look normal and do not indicate that the installation failed. Is the functionality of VSH impaired in any way?

Best
Cornelius

**Comment by csuermann** [comment]
Hi @andrecamper,

GitHub removes attachments when you reply via email, hence I cannot see the screenshot you're referring to. Could you please upload it via the GitHub website?

**Comment by andrecamper** [comment]
Hi Cornelius,
That solved my problem. Had to redo all of them but jow it is working.
Thank you for the support.
Br
Andre


Enviado do Yahoo Mail para iPhone


Em sábado, maio 17, 2025, 07:20, Cornelius Suermann ***@***.***> escreveu:

csuermann left a comment (csuermann/node-red-contrib-virtual-smart-home#248)
Hi @andrecamper,

GitHub removes attachments when you reply via email, hence I cannot see the screenshot you're referring to. Could you please upload it via the GitHub website?
