### ISSUE TITLE
Add Fan Speed to Thermostat Device

### ISSUE THREAD

**Issue by MrCO0OL** [csuermann/node-red-contrib-virtual-smart-home#249]
### Problem Statement

Almost all real life thermostat devices have Fan speed settings ... usually Low, Medium, High, and Auto.
we are facing major deficiency in virtual smart home - Thermostat device due the lack of Fan settings which is requested by all of our customers. Due to this issue, we are forced to find other nodes that supports such settings

### Ideal Solution

Add Fan Speed settings to Thermostat Device with the following settings: AUTO, LOW, MEDIUM, HIGH

### Alternatives

could not find alternative solution for Thermostat fan speed setting  within Virtual Smart Home node

**Comment by csuermann** [comment]
Hi @MrCO0OL,

Thank you for getting in touch. From what I've gathered, it seems that Alexa Smart Home skills currently do not facilitate the adjustment of fan speeds for thermostat devices. While there is an [HVAC component](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-thermostatcontroller-hvac-components.html) available for monitoring energy consumption, it doesn't provide the functionality to control fan speed.

It's worth noting that VSH already offers a dedicated FAN device that supports speed settings.

**Comment by KSumwalt** [comment]
Is it possible to do at least an On/Auto fan mode setting?  I do not see anything being returned for that and my Thermostat in Alexa shows "Waiting for virtual smart home..." when I open the thermostat item to see details.

**Comment by csuermann** [comment]
@KSumwalt, are you on the PRO plan and is the retrievable option enabled for your virtual thermostat device?

**Comment by KSumwalt** [comment]
> @KSumwalt, are you on the PRO plan and is the retrievable option enabled for your virtual thermostat device?

Not on the Pro plan.  That would be why I am unable to retrieve the information.  (I am testing for someone else as I do not use Alexa myself)  Is the Fan On/Auto capability available with the Pro plan or is that an enhancement?

**Comment by KSumwalt** [comment]
Understood.  Thank you.

Is the Pro plan also needed to change the Fan between On and Auto?  I have always had forced air systems and any thermostat I have ever had has this option.  I use it especially when we have a large gathering to circulate air from cooler parts of the house

**Comment by csuermann** [comment]
If you send me your ThingID, I can give you temporary access to the PRO plan to trial it.

**Comment by KSumwalt** [comment]
Here is the ID:
vsht-c376ac14-bbab-48a7-8908-905be750c4dd

Thank you!  HomeSeer has gone to a subscription plan for voice and using your contrib for the Alexa side would be less than half the cost they are asking.  As a result, I am assisting some users in exploring Node-RED and your contrib.  I personally use Google else I would gladly pay the Pro plan as it seems very reasonable to me.

**Comment by csuermann** [comment]
Just upgraded your account to PRO. Let me know how it goes.

**Comment by KSumwalt** [comment]
I am able to retrieve now.  Thank you.

I still do not see a way to set a Fan Mode.  Looking at the API it appears this is accessed via [ThermostatController.HVAC.Components](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-thermostatcontroller-hvac-components.html) and this would also be where the OP's requested settings are made.

I also do not see a High and Low Set Temperature ability.  I see the API allows for lowerSetpoint and upperSetpoint on a [dual-setpoint thermostat](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-thermostatcontroller.html#thermostat-setpoint-types)

Would it be possible to implement these or am I just missing something?

**Comment by csuermann** [comment]
ThermostatController doesn't seem to support fan speed settings (see my previous [comment](https://github.com/csuermann/node-red-contrib-virtual-smart-home/issues/249#issuecomment-2001955769)).

VSH's current thermostat implementation makes use of only one setpoint, but adding another dual-setpoint thermostat would be quite feasible. If there's demand, I'm willing to look into it.

**Comment by KSumwalt** [comment]
Okay. I looked into the Fan device and see it does allow for an Auto setting, so a Thermostat where we wish to control the Fan as well will be 2 devices.

On my thermostat and at least one user I am assisting, we have a temperature setting for when the A/C is on and a second for when the Heat is on.  I can see the current setting (Heat/Cool) and work from there, but yes, there are many programmable thermostats which have high and low set points for the Auto Mode and also use these for the respective Heat and Cool modes.  It also will not work on an Eco(nomy) mode.  So I do believe High and Low set points would be desirable to many.

**Comment by csuermann** [comment]
Okay, while perusing the [documentation](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-thermostatcontroller.html), I came across this noteworthy point:

> **Important**: Users have the ability to set a single temperature via voice command, and one or two temperatures through the Alexa app.

Considering this constraint regarding setting a dual setpoint thermostat via voice, I can't help but ponder the significance of an extended VSH thermostat. Thoughts?

P.S.
@KSumwalt, just to let you know: Your temporary PRO access should have expired by now.

**Comment by KSumwalt** [comment]
Understood on the Temporary Access.  Thank you very much for that!

The persons I am working with are primarily focused on Voice control and state that UI control will be handled in other ways.  That said, they are also short sighted and I expect that they will later make comment that they need to use the Alexa UI /App.  I suspect most/many Node-RED users will likely have some sort of interface created outside the Alexa App but expect at least some will plan on using the app for said interface. The Devil's Advocate in me suggests that you may desire the implementation of all possible capabilities.  The realist in me says focus on other things, especially life, and wait for others to make the request.

**Comment by csuermann** [comment]
FYI, I've just released [VSH v4.3.0](https://www.npmjs.com/package/node-red-contrib-virtual-smart-home), which adds support for dual-setpoint thermostats.

**Comment by KSumwalt** [comment]
Updated and tested the new device type.  Appears to be working.  Thank you!!!
