### ISSUE TITLE
Feature Request: Thermostat Temperature

### ISSUE THREAD

**Issue by Raibeart-Bruis** [csuermann/node-red-contrib-virtual-smart-home#25]
1) Thermostat Temperature Increment 0.5:
Currently when asking “Alexa, make it warmer in here” or “Alexa, make it cooler in here”, the response is to increase|decrease the targetTemperature by 1 degree.  I have found that all of my smart thermostats increase|decrease the temperature by 0.5 degree rather than 1 degree.

Would it be possible to change the increment|decrement value to 0.5 or somehow be able to select the increment|decrement value?

2) Response to Setting Thermostat Target Temperature:
When asking Alexa to “Set Loft Thermostat to 21.5” the response is “Auto set to 21.5”.  It is possible for the response from Alexa to use the name of the thermostat  as in this scenario “Loft Thermostat”  instead of “Auto” for a  more positive confirmation of the thermostat set?

Also, when first exploring the Thermostat, I thought Alexa also responded with “Auto set to 21.5” followed by “Current Temperature is 21”.  Was I just engaging in wishful thinking or if not how do I invoke this response?

Thanks Again!

**Comment by csuermann** [comment]
Hi @Raibeart-Bruis,

The increment value appears to be hard-coded by Alexa and can unfortunately not be adjusted.

See: https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-thermostatcontroller.html#adjusttargettemperature-directive

**Comment by Raibeart-Bruis** [comment]
Thank you very much for your super quick responses.  Much appreciated!
