### ISSUE TITLE
Setting High or Low Setpoint on Dual Thermostat

### ISSUE THREAD

**Issue by KSumwalt** [csuermann/node-red-contrib-virtual-smart-home#250]
### Bug Description

I am using the new Dual Setpoint thermostat.  When I say "Alexa, set the lower setpoint on master thermostat to 67 degrees" I get a reply of "Sorry, master thermostat isn't responding.  This is also happening with the upper setpoint or if I just say "Alexa, set the master thermostat to 67 degrees."  Note that I have tried different values as well.  Master Thermostat is the device name.  I have also tried other ways to have Alexa change this, such as saying "high temperature" and other possible wording. Setting to Cool, Heat, and other items via voice works fine.  Setting msg.payload.upperSetpoint and msg.payload.lowerSetpoint via Node-RED works.  

### To Reproduce

say "Alexa, set the lower setpoint on master thermostat to 67 degrees" or any other value.

### Expected behavior

Expect Alexa to respond that the upper or lower setpoint has been set and to have output from the associated node in Node-RED.

### Virtual-Smart-Home Version

4.30

### Node-RED Version

3.0.2

### Plan

FREE

### Thing-ID

vshd-ec192310979d5

**Comment by csuermann** [comment]
Hi @KSumwalt,
As noted [here](https://github.com/csuermann/node-red-contrib-virtual-smart-home/issues/249#issuecomment-2022897667), Alexa provides only limited support for voice commands with dual-setpoint thermostats. Furthermore, it appears that enabling the "retrievable" setting is necessary for Alexa to respond to specific voice prompts.
