### ISSUE TITLE
Disconected Reconnecting

### ISSUE THREAD

**Issue by rlust** [csuermann/node-red-contrib-virtual-smart-home#251]
### Bug Description

Looks like no node is logged in, is working in another system running NR.

### To Reproduce

load all nodes in flow

### Expected behavior

Login and active

### Virtual-Smart-Home Version

4.3.0

### Node-RED Version

3.1.7

### Node.js Version

16

### Plan

PRO

### Thing-ID

vsht-d6750d3b-da3b-4cfd-a4d7-82f8cdf78991

**Comment by rlust** [comment]
I found that the thing ID is different on my system that is working.  How do you change the thing ID?

**Comment by csuermann** [comment]
Hi @rlust,
I cannot find your ThingID in the database. Perhaps it got auto-deleted after being inactive for too long?! In any case, please try creating a new vsh-connection and going through the account linking process once more.

**Comment by rlust** [comment]
How do I create a new connection?
