### ISSUE TITLE
Cannot add new nodes even as Pro user

### ISSUE THREAD

**Issue by brunialti** [csuermann/node-red-contrib-virtual-smart-home#252]
### Bug Description

I cannot add a new virtual device., that is I add it but the red triangle in NR mark it as uncorrectly configured.
![image](https://github.com/csuermann/node-red-contrib-virtual-smart-home/assets/1572972/3d40d6ef-3192-4d3f-8053-bc1554ff6933)

It appears in the list of device ad in the picture.
It does'nt appear in the Alexa app

### To Reproduce

create a new node and deploy

### Expected behavior

the device should appera in alexa app. The device node shoud'nt show an error red triangle

### Virtual-Smart-Home Version

latest

### Node-RED Version

latest

### Node.js Version

latest

### Plan

PRO

**Comment by csuermann** [comment]
Hi @brunialti,
The red triangle indicates an incomplete / invalid configuration of a node. My hunch is that something is wrong with the `Metadata` field. Could you please post a screenshot of the edit screen for that vsh-device node?

**Comment by juanjodcv** [comment]
I have same problem, nodes works fine. If I doble clic on a node previusly created that works fine without red triangle, open config and clic done without changing anything, deploy and shows error and red triangle, but still works fine.
all my nodes have metadata section with red square around.

**Comment by csuermann** [comment]
Thanks for providing these additional details!

Could you please try to put `{}` into the metadata field?

**Comment by csuermann** [comment]
Thanks for reporting back.
