### ISSUE TITLE
Add Device Name of Alexa device acting on request

### ISSUE THREAD

**Issue by KSumwalt** [csuermann/node-red-contrib-virtual-smart-home#253]
### Problem Statement

When a voice command is issued it would be helpful to know which Alexa Device hears and acted on the command which triggered the flow in Node-RED.  I have seen past requests for this with the suggestion that it is not available in the API.  The [node-red-contrib-alexa-remote2-applestrudel](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel) contrib provides this in msg.payload.name, which is the Name of the Alexa device such as an Echo as shown in my Alexa app.  I do not know if that uses the official API or is pulling the information some other way.  If this has been added to the API, can it be included here now?

### Ideal Solution

Provide a value in the msg object defining the Name of the Alexa Device which heard/acted on a voice command.

**Comment by csuermann** [comment]
VSH is constructed atop Alexa's smart home API, which, regrettably, lacks information regarding the specific Alexa device that receives a request. Primarily, assigning virtual devices and Alexa devices to rooms serves as an effective workaround. This enables you to issue instructions such as "Alexa, turn off the light" and receive varying results depending on the Alexa device you addressed.

**Comment by KSumwalt** [comment]
Understood.  I was hopeful that it was available since it is coming in from a different contrib the API was updated.  Hopefully it is added at some point and you can include the capability.

Unfortunately the work arounds will not work for my needs as the room hearing the control may not be the room the device(s) are in.  Such as turning a light on in a different room.
