### ISSUE TITLE
Connect to Enabled Skill "failed to fetch"

### ISSUE THREAD

**Issue by ronsegal** [csuermann/node-red-contrib-virtual-smart-home#259]
### Bug Description

Latest virtual-smart-home.  All device connections to VSH were deleted (trash icon) from an Ubuntu host that was shut down, then  node-red was configured on a new Ubuntu host. VHS nodes installed and a new node created.  However when the connection node name is input (edit connection node) there is an error: "ERROR failed to fetch".  
Have tried reinstalling VHS, restarting etc but no luck. Can't get VHS to connect. Plan on the virtual device node indicates UNKNOWN.  Have checked the Alexa skill is enabled and am using the correct e-mail address for that account as the connection name.
Could be me being stupid about something but am currently stuck.
Can you please assist. Happy to upgrade to pro once this is working. Thanks.

### To Reproduce

Create new virtual device node.
Go to "connection"
Enter name of existing smart home alexa account e-mail address.  Skill is enabled and connected.

### Expected behavior

Expected to be able to deploy the virtual device node without error.

### Virtual-Smart-Home Version

4.4.1

### Node-RED Version

3.1.10

### Node.js Version

20.14.0

### Plan

FREE

### Thing-ID

vshd-23646d942010ff8b

**Comment by csuermann** [comment]
Hi @ronsegal!

I cannot reproduce this issue and would guess that it is some sort of network / connectivity issue on your end, perhaps a misconfigured Proxy...

For further troubleshooting, could you please provide a screenshot of the error and your browser's dev tool network tab?
