### ISSUE TITLE
Different behavior between old and new "blinds" device

### ISSUE THREAD

**Issue by MartinJura** [csuermann/node-red-contrib-virtual-smart-home#262]
### Bug Description

I have an old device of type "blinds" called "Jalousie Erdgeschoss". If I ask Alexa "Jalousie Erdgeschoss auf" I receive msg.payload.mode = "Position.Up" / msg.payload.percentage = 100. (Device was created approx. 2 years ago).

Recently I added a new device of type "blinds" called "Beschattung Küche". If I ask Alexa "Beschattung Küche auf" I receive msg.payload.mode = "Position.Down" / msg.payload.percentage = 0. 

When asking Alexa "Beschattung Küche öffnen" I receive msg.payload.mode = "Position.Up" / msg.payload.percentage = 100.
![CleanShot 2024-08-26 at 20 41 14@2x](https://github.com/user-attachments/assets/7dc2bddb-a0dc-433f-9508-d7302fbeb878)

### To Reproduce

Reproducable in my environment and with my devices. Don't know how to reproduce in a fresh environment.

### Expected behavior

When using the keyword "auf" on "Beschattung Küche" I expected to receive "Position.Up" / 100, i.e. identical behavior to "Jalousie Erdgeschoss" 

### Virtual-Smart-Home Version

4.4.2

### Node-RED Version

4.0.2

### Node.js Version

20.17.0

### Plan

PRO

### Thing-ID

vshd-1f2137e87e202f52

**Comment by csuermann** [comment]
Hi @MartinJura,

Thanks for reaching out!

It looks like Alexa is sending different directives to the VSH backend depending which voice command you issue. That's bizarre but nothing that can be fixed in VSH. You might want to file a bug report for the Alexa team.

It might be that Alexa just misunderstands you. After all, the German commands "aus" and "auf" sound quite similar. Have you tried "Alexa, öffne / schließe Beschattung Küche"?

**Comment by MartinJura** [comment]
I did some more tests. Indeed it's not an issue of VSH. It seems that Alexa is "interpreting" the name of the device. If I name the device "Jalousie Küche", "Rollo Küche" or even "Ding Küche" then I receive "Position.Up".
If I name the device "Beschattung" I receive "Position.Down".
Thanks for your support. Issue closed. I try to file a bug report for the Alexa team.

**Comment by csuermann** [comment]
Thanks for reporting back!
