### ISSUE TITLE
Circular dependancy linking account

### ISSUE THREAD

**Issue by brianmcentire** [csuermann/node-red-contrib-virtual-smart-home#264]
### Bug Description

Hello, this looks like exactly what I need to create a Home Assistant automation to control some existing Alexa Routines. 

The problem I'm running in appears to be a circular dependancy. I need cannot install the Alexa Virtual Smart Home Skill because it doesn't detect any vsh-virtual-devices. I can't deploy a vsh-virtual-device because when doing the account linking (to Alexa/Amazon) on the node inside Node Red, after a few seconds it comes back and says "Error provisioning failed! Try (re)-enabling the VSH skill in the Alexa app!"

More details here if needed - 
https://www.reddit.com/r/homeassistant/comments/1ft9g5t/circular_dependency_connecting_virtual_smart_home/

### To Reproduce

Start without the Virtual Smart Home Skill enabled on Alexa. Try to deploy a vsh-virtual-device in Node Red. Try to setup the connection, it will fail and say to enable the Alexa Skill. On iPhone, in Alexa, try to enable the Virtual Smart Home Skill, it will fail because no devices are detected.

### Expected behavior

Either the Alexa Skill should allow installing it (and any account linking needed within Alexa) before vsh-virtual-devices have been deployed on Node Red in HA VM, or virtual devices should be possible to deploy in some capacity that allows them to be detected by an Echo device/Alexa so that the Alexa Skill can be enabled and account linking can occur successfully in a new environment where neither existed before.

### Virtual-Smart-Home Version

4.2.2

### Node-RED Version

4.0.2

### Plan

FREE

**Comment by csuermann** [comment]
Hi @brianmcentire,

Thanks for reaching out!

Enabling the VSH skill in the Alexa app should not require any already configured virtual devices. Could you please provide screenshots that illustrate the issue?
