### ISSUE TITLE
Alexa integration not automatically reconnected after the public network is established

### ISSUE THREAD

**Issue by devdems** [csuermann/node-red-contrib-virtual-smart-home#265]
### Bug Description

I have Alexa integration (node-red-contrib-virtual-smart-home) configured in Node-RED which was started when network was not established with ISP. When the network was established later on Alexa integration did not reconnect but it stayed offline. I had to restart Node-RED and then Alexa integration established a connection to Amazon.

### To Reproduce

Start Node-RED, that has Alexa integration, without public network connectivity.
Establish public network connectivity.
Check if integration started to work.

### Expected behavior

I would expect that integrations in Node-RED will automatically try to reestablish connections so that users would not need to restart the Node-RED to get this working.

### Virtual-Smart-Home Version

4.4.2

### Node-RED Version

4.0.5

### Plan

FREE

**Comment by devdems** [comment]
@csuermann thank you for the quick solution. Is it possible to also use the latest axios as we are getting this error:

`axios  1.3.2 - 1.7.3
Severity: high
Server-Side Request Forgery in axios - https://github.com/advisories/GHSA-8hc4-vh64-cxmj
fix available via `npm audit fix --force`
Will install node-red-contrib-virtual-smart-home@4.1.11, which is a breaking change
node_modules/node-red-contrib-virtual-smart-home/node_modules/axios
  node-red-contrib-virtual-smart-home  >=4.1.12
  Depends on vulnerable versions of axios
  node_modules/node-red-contrib-virtual-smart-home`

**Comment by csuermann** [comment]
Hi @devdems. This should be addressed in the just released VSH version 4.4.4.
