### ISSUE TITLE
Issue with grouping rooms

### ISSUE THREAD

**Issue by maru-sama** [csuermann/node-red-contrib-virtual-smart-home#266]
### Bug Description

I have trouble grouping rooms together. I have two Alexa enabled sonos speakers. I created two separate rooms and assigned each alexa device to one room. Regardless of which room I am in if I say "alexa turn the lights off" This turns off all light and not just the lights in this room. Since this is working for others, could this be a sonos related issue?

### To Reproduce

Create a room and assign an Sonos alexa to it

### Expected behavior

when saying turn the lights off, only the lights in this specific room should be triggered.

### Virtual-Smart-Home Version

4.4.4

### Node-RED Version

4.0.5

### Node.js Version

18.20.4

### Plan

FREE

### Thing-ID

vsht-3dd07b5f-cc3c-4e9c-80a9-9aee68adaa9e

**Comment by maru-sama** [comment]
Ok, I found the issue.

I only had one virtual light defined and so apparently on or off just triggered this light. I created a dummy entry for a second light and assigned it to the second room and it works as expected now.

**Comment by csuermann** [comment]
Thanks for reporting back, @maru-sama!
