### ISSUE TITLE
Updating server - how to transfer to a new server

### ISSUE THREAD

**Issue by Paul-Reed** [csuermann/node-red-contrib-virtual-smart-home#267]
### Bug Description

I need to transfer my flow to a new server, and not sure how this would work...
Would I need to run through the account linking process again, or can it be transferred via flow export/import, or some other means? thing ID?

### To Reproduce

Export the flow to a new server

### Expected behavior

Your advice would be appreciated!

### Virtual-Smart-Home Version

4.4.4

### Node-RED Version

3.1.4

### Node.js Version

18.17.1

### Plan

FREE

### Thing-ID

vsht-b87a8db0-3d8b-4b98-8b56-0086eb2c8657

**Comment by csuermann** [comment]
Hi @Paul-Reed,

You should be able to restore your entire Node-RED flows, including credentials, from a full backup.

Alternatively, you can copy the flows over manually, create a new VSH connection, and go through the account linking process again. Once that’s done, you’ll need to update all your VSH device nodes to use the new connection. Alexa should then discover all devices as new, hence this will require you to adjust room assignments and other settings.

Afterward, you can delete the old devices from the VSH connection screen. They should appear with a shaded background, indicating they belong to another (a.k.a. your old) connection.

**Comment by Paul-Reed** [comment]
Hi Cornelius, thanks for replying so quickly!
I copied over `flows_cred.json` to the new server (and used the same Credential Secret), and yes, it was quickly authenticated, and works OK.
