### ISSUE TITLE
Configuration Node is Empty

### ISSUE THREAD

**Issue by niklasfink** [csuermann/node-red-contrib-virtual-smart-home#27]
Hi, I'm having an issue on a new Node Red instance, where the configuration node for VSH just stays empty. There is a name input but nothing else shown in the panel:

![image](https://user-images.githubusercontent.com/1809301/105608010-b142e080-5da1-11eb-812b-4c1e16555874.png)

On another system, which already had VSH successfully integrated, I cannot retrieve my list of registered devices.

`Registered Devices
...loading...`

I'm not sure if this is a local issue or caused by some server outage. In any case, how would you analyze the issue? I cannot see any relevant logs in Node Red and the Chrome Network tab is also not showing anything.

In any case: The configuration node should show some backup/debug information in order to point the user in the right direction what's happening.

**Comment by csuermann** [comment]
Hi @niklasfink,

For the sake of completeness, which VSH version are you running?

To me both symptoms seem to be related to JavaScript not working in your browser. The fact that you're not seeing any activity in the network tab underpins my hypothesis that it's not a backend related issue.

**Comment by niklasfink** [comment]
Hi @csuermann,

I'm running the latest VSH 1.19.2. With the Network Tab "not showing anything" I meant it wasn't showing helpful information. Indeed I would say Javascript is working as I get a successful `{isAllowedVersion: true, isLatestVersion: true, updateHint: ""}` when https://kfd5m4a21f.execute-api.eu-west-1.amazonaws.com/dev/check_version?version=1.19.2 is being called after opening the Configuration Node.

The PayPal Support Banner is also shown on the VSH node panel.

**Comment by csuermann** [comment]
Strange. I cannot reproduce the issue with the very same version.

What network activity do you see when you open the vsh-connection dialogue? Should look similar to this:

![image](https://user-images.githubusercontent.com/10939809/105610794-c45dac80-5db1-11eb-9805-c3e6a955ca09.png)

**Comment by csuermann** [comment]
It would also be interesting to know if there is anything logged to the Chrome dev tools console.

**Comment by niklasfink** [comment]
Hi @csuermann,

this is coming up on my fresh setup:
![image](https://user-images.githubusercontent.com/1809301/105626314-23add200-5e2f-11eb-9cf8-c251605cbf9a.png)
The highlighted request just responds with a `{}`.

DevTools Console is just showing violations, no errors:
![image](https://user-images.githubusercontent.com/1809301/105626376-7ab3a700-5e2f-11eb-9175-6b164314369d.png)

On my other setup where I already had VSH working, the config node also does a call to the credentials endpoint but instead of an empty object, it receives a filled object with `accessToken:` and more. However, no further calls are being made.

NodeRed Log does not show any errors/warnings in both cases. It only logs the requests to the resources and "credentials" endpoint.

**Comment by csuermann** [comment]
Looks like the Node-RED internal call to the credentials is not going through. Do you see the same problem with other nodes that make use of credentials, e.g. MQTT, I think?

**Comment by niklasfink** [comment]
Hi @csuermann, I tested the MQTT and Telegram Bot node. Both configuration nodes load, accept changes and work (receiving MQTT messages and sending a Telegram message). These configuration nodes are built differently/easier I think though, as they don't have dynamic content, just input fields.

Unfortunately,

**Comment by csuermann** [comment]
Hi @niklasfink,

Let's separate the two issues you're facing: Correct me if I misunderstood you:

1. On your fresh system, you cannot configure a new vsh-connection, because no code paring prompt (see below) appears. Instead you see just the name input field but nothing below, correct?
![image](https://user-images.githubusercontent.com/10939809/105634491-7baffd00-5e5e-11eb-993d-92831f170b7d.png)

The network activity of that screen should look something like the following:
![image](https://user-images.githubusercontent.com/10939809/105634588-faa53580-5e5e-11eb-89dc-40fae5779f50.png)
The "{}" response of credentials call is actually ok for a brand new vsh-connection, because credentials do not exist yet at this stage. Your browser doesn't show any request to the "codepair" and "token" endpoints, correct?

2. On your other system which already has a working VSH integration, the vsh-connection node only shows the "...loading..." hint, but no registered devices appear, correct? In contrast to below screenshot, your browser does not show any network activity after the call to the credentials endpoint (in my case shown as "684073d.0735f8c")
![image](https://user-images.githubusercontent.com/10939809/105634837-44425000-5e60-11eb-9ade-7a09abddcffa.png)

It looks like your browser is somehow blocking all requests to api.amazon.com, specifically
- https://api.amazon.com/auth/o2/create/codepair and
- https://api.amazon.com/auth/o2/token,
which prevents the subsequent steps in the process from being executed.

**Comment by niklasfink** [comment]
That is all correct. 

I don't see any evidence that these calls are being blocked in my browser though. I think my browser is not even receiving the command to execute these calls. I've tried another browser with no plugins installed and the same situation is happening.

I can successfully ping api.amazon.com and when browsing to the two linked endpoints, I get a 404 response from the server with "<UnknownOperationException/>" which is probably what is expected when calling these without any parameters.

**Comment by csuermann** [comment]
Hmm, it's a wild guess, but maybe it has to do with jQuery not being executed for whatever reason.

[This](https://github.com/csuermann/node-red-contrib-virtual-smart-home/blob/master/connection.html#L289) seems to be the line where everything stops.

Could you please try to execute the following command via the dev tools console after opening Node-RED?

```javascript
$.ajax({
    url: 'https://api.amazon.com/auth/o2/create/codepair',
    method: 'POST',
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
    },
    data: {
        response_type: 'device_code',
        client_id:
        'amzn1.application-oa2-client.3f1bb07133854b078261ad43f2484c18',
        scope: 'profile',
    },
}).done((d) => console.log(d)).fail((e) => console.log('ERROR', e));
```

What do you see as output?

**Comment by niklasfink** [comment]
Interesting idea. Since I'm running Node-RED via the Home Assistant integration (which so far didn't cause any problems), I wasn't able to invoke this command, as no jQuery is available on the HassOS frontend. However, since Node-RED is running in a container in an embedded iframe, I opened this iframe in order to reach the Node-RED GUI directly.

Here, I have jQuery 3.5.1 installed and can execute the command:

![image](https://user-images.githubusercontent.com/1809301/105639111-a017d380-5e76-11eb-8ceb-67af2beb0825.png)

However, it does not give me a response from the server. No further console log is printed and I don't see a call being made in the Network DevTools Tab.

For comparison, I tried the same command in the same browser on stackoverflow. Here, I got a proper response from Amazon.

I recently upgraded to the most recent Chrome Version 88.0.4324.104. Microsoft Edge gives the same results. Chrome Incognito with no plugins, same results.

**Comment by csuermann** [comment]
Hi @niklasfink,

I just released v1.19.3 that replaces `jQuery` with `fetch`, which I hope will fix the problem you encountered.

Looking forward to hearing back from you.

**Comment by niklasfink** [comment]
It does indeed work again, thanks!

![image](https://user-images.githubusercontent.com/1809301/105765202-5a333c00-5f58-11eb-8e4b-2f83a4664773.png)

I have no idea why ajax via jQuery suddenly didn't work anymore. I even tried downgrading HassOS to a previous version from November where it was surely working, without success.

Maybe more recent versions of Chromium (which also Microsoft Edge belongs to) somehow prevent the use of `XMLHttpRequest` to a different domain within an iframe?

**Comment by csuermann** [comment]
Glad to hear it's working again! Thanks for your help during troubleshooting!
