### ISSUE TITLE
Temperature sensor is not working...

### ISSUE THREAD

**Issue by alexbn71** [csuermann/node-red-contrib-virtual-smart-home#270]
### Bug Description

I'm trying the "pizza oven" example with no success. Alexa's answer is "I don't know what problem occurred". Could you help me?

### To Reproduce

Use temperature-sensor.json from examples

### Expected behavior

The temperature of my virtual sensor

### Virtual-Smart-Home Version

4.4.4

### Node-RED Version

4.0.8

### Plan

PRO

### Thing-ID

vsht-ac6ee867-190a-4303-b6cb-c7ff6b8f97da

**Comment by csuermann** [comment]
Hi @alexbn71!

Please make sure to enable the "retrievable" option in your virtual device node.

**Comment by alexbn71** [comment]
Thank you

**Comment by alexbn71** [comment]
Solved
