### ISSUE TITLE
Add support for PT - BR

### ISSUE THREAD

**Issue by thiagoprati** [csuermann/node-red-contrib-virtual-smart-home#28]
Is it possible to release it to BR locale?
Is any translation is necessary, I can provide it.
Thanks

**Comment by JulioC** [comment]
@csuermann I can also help with this if necessary

**Comment by csuermann** [comment]
Hi @thiagoprati, @JulioC,

Thanks for offering your help! In fact, Amazon tends to reject skills that do not follow their [guidelines](https://developer.amazon.com/en-US/docs/alexa/custom-skills/functional-testing-for-a-custom-skill.html#cert-skill-description) in the descriptions. Therefore I'd really appreciate if you could check the translation below and make sure it complies.

Here is what I have prepared so far, with the help of Google Translate:

**One Sentence Description:**
Controle dispositivos virtuais ou físicos em Node-RED com Alexa

**Detailed Description:**
NOTA: Esta skill requer uma instância de Node-RED com o pacote 'virtual-smart-home' correspondente instalado.

Se você usa o Node-RED para automatizar coisas em sua casa, essa habilidade é para você! Ele permite que você configure nós de 'dispositivo virtual' que podem ser invocados por meio do Alexa.

Por exemplo, você pode configurar um switch virtual, que aciona uma ação quando você diz "Alexa, ligue meu switch virtual". Quando chamado, o nó emitirá um objeto de mensagem que você pode rotear para qualquer outro nó em seu projeto, por exemplo, para ligar um dispositivo real, ou postar um tweet no Twitter, ou fazer o que quiser ...

A skill suporta os seguintes tipos de dispositivos virtuais pré-configurados:

- Interruptor
- Plugue
- Lâmpada regulável
- Lâmpada de mudança de cor
- Interruptor
- Cortinas

Para poder usar esta skill, você precisa de uma instalação do Node-RED incluindo o pacote 'virtual-smart-home' que pode ser encontrado e instalado através do 'Palette Manager'. Depois, você pode selecionar o nó 'dispositivo virtual' da paleta e usá-lo em seu projeto.

Mais detalhes podem ser encontrados nos documentos que estão incorporados na seção de ajuda do Node-RED.

**Example phrases:**

- Alexa, desligue meu dispositivo virtual
- Alexa, diminua minha luz inexistente para 50 por cento

**Comment by JulioC** [comment]
@csuermann that's awesome! Your translation is pretty good. I've just added a few suggestions below to make the text sound a bit more natural:

> **One Sentence Description:**
> Controle dispositivos virtuais ou físicos em Node-RED com Alexa
> 
> **Detailed Description:**
> NOTA: Esta skill requer uma instância de Node-RED com o pacote 'virtual-smart-home' correspondente instalado.
> 
> Se você usa o Node-RED para automatizar coisas em sua casa, essa habilidade é para você! Ele permite que você configure nós de 'dispositivo virtual' que podem ser invocados por meio do Alexa.

Change "habilidade" to "skill" here. Amazon uses the untranslated word for skills. Also, change "por meio do Alexa" to "pela Alexa"

> Por exemplo, você pode configurar um switch virtual, que aciona uma ação quando você diz "Alexa, ligue meu switch virtual". Quando chamado, o nó emitirá um objeto de mensagem que você pode rotear para qualquer outro nó em seu projeto, por exemplo, para ligar um dispositivo real, ou postar um tweet no Twitter, ou fazer o que quiser ...

Change "switch" to "interruptor".

> 
> A skill suporta os seguintes tipos de dispositivos virtuais pré-configurados:
> 
>     * Interruptor
>     * Plugue
>     * Lâmpada regulável
>     * Lâmpada de mudança de cor
>     * Interruptor
>     * Cortinas
>  
> Para poder usar esta skill, você precisa de uma instalação do Node-RED incluindo o pacote 'virtual-smart-home' que pode ser encontrado e instalado através do 'Palette Manager'. Depois, você pode selecionar o nó 'dispositivo virtual' da paleta e usá-lo em seu projeto.
> 
> Mais detalhes podem ser encontrados nos documentos que estão incorporados na seção de ajuda do Node-RED.
> 
> **Example phrases:**
> 
>     * Alexa, desligue meu dispositivo virtual
> 
>     * Alexa, diminua minha luz inexistente para 50 por cento

**Comment by csuermann** [comment]
@JulioC, Thank you so much! I'm going to trigger the publish process soon and will keep you posted on the status here.

**Comment by csuermann** [comment]
Good news: Amazon just certified the new version of the VSH skill, which includes the PT locale. The update should get rolled out today.

**Comment by csuermann** [comment]
Hi @JulioC, @thiagoprati,

I was wondering if you could confirm that the skill has indeed landed in the Brazilian skill store and is functioning as expected?!

Thank you!

**Comment by JulioC** [comment]
It appears to be working perfectly! Thanks a lot @csuermann !
