### ISSUE TITLE
Inform Alexa of new Blinds state seems not to be working correctly

### ISSUE THREAD

**Issue by sven-cpu** [csuermann/node-red-contrib-virtual-smart-home#29]
When inputting the following payload to a virtual device of type Blinds, Alexa shows the device as up.

`{"mode":"Position.Down","percentage":0}`

Passthrough output looks like this

`{"mode":"Position.Up","instance":"Blinds.Position","percentage":0,"source":"device","position":"Position.Down","directive":"OverrideLocalState","name":"Rolladen im Schlafzimmer","type":"BLINDS"}`

Property position is changed correctly, but property mode obviously not.

Another question: Is changing the position (e.g. to 30%) not supported by the alexa app? I can only choose fully open or fully closed.

Thank you,
great work btw.!

**Comment by csuermann** [comment]
Hi @sven-cpu,

Thanks for reporting this issue. I think I know where it comes from and will look into fixing it shortly.

**Comment by sven-cpu** [comment]
Thanks, i really appreciate your effort. Beer is on it's way to you.

**Comment by csuermann** [comment]
Should be fixed now. You might have to ask Alexa to (re)discover your devices. Please note that the `mode` attribute got removed, as `percentage` is actually all one needs to figure out in which state the blinds are / should be.
