### ISSUE TITLE
No VSH Config

### ISSUE THREAD

**Issue by MaxRei-dev** [csuermann/node-red-contrib-virtual-smart-home#3]
Node red:
ERROR
provisioning failed

on amazon side:
Erfolg!
Ihr Registrierung ist hiermit abgeschlossen.

**Comment by csuermann** [comment]
Hi @MaxRei-dev 
Thanks for reporting this bug, which I believe is an edge case and fixed now. Would you mind trying again and updating the ticket here? Thank you!
C.

**Comment by MaxRei-dev** [comment]
Hi,
It is working now. Thank you
