### ISSUE TITLE
Remove devices from lost configuration node

### ISSUE THREAD

**Issue by niklasfink** [csuermann/node-red-contrib-virtual-smart-home#32]
Hi, is there a way to remove devices from an account connection which is not active anymore?

Basically, what is there to do, if the hint to reuse an established connection to an Alexa account has been ignored? 😀 

There could be the case that a previous connection is not retrievable anymore and a new configuration node to the same account needs to be created. Where do you find the old devices to delete them?

**Comment by csuermann** [comment]
Hi @niklasfink,

You can see a list of all devices linked to your _Amazon account_ in the vsh-connection dialogue. The ones belonging to a different connection appear with a shaded background. You can delete them from there and they should also disappear from Alexa.

**Comment by niklasfink** [comment]
Very clever, that worked. Will read the FAQ next time.

**Comment by maverick62** [comment]
Hello,

My alexa device keeps showing older devices i created with red node.
I have understood that i have to delete them from "Open the connection page which lists all known devices " but i can't find it! Where i must go? "Amazon account in the vsh-connection dialogue" => where is it? On amazon where i buy stuff? on alexa.amazon.com ? I can't find.

Please can you tell me in few words where to go.

Thanks
Regards

**Comment by csuermann** [comment]
![image](https://user-images.githubusercontent.com/10939809/202854114-02b4d1ae-a565-49b6-83ee-45e50c61c0c2.png)
![image](https://user-images.githubusercontent.com/10939809/202854201-2a67e878-cee0-45a3-ab7f-3519c9cd6cfe.png)

**Comment by maverick62** [comment]
it got it !
thanks you very much for your time
