### ISSUE TITLE
Feature Request: Description-field of AlexaApp editable in node-red

### ISSUE THREAD

**Issue by ammawel** [csuermann/node-red-contrib-virtual-smart-home#33]
Please make the Description field in the alexa app editable in node-red. Currently, only the virtual device type is displayed there.
It would already help to add the node-red name to the description, as you can rename devices in the Alexa app and quickly lose the assignment.
Thank you, Achim

**Comment by csuermann** [comment]
Hi @ammawel,

Thanks for the feature request. Making the description editable involves significantly more efforts than just adding the name to the description, which I just did. You might have to re-discover your devices for this to take effect.
