### ISSUE TITLE
Idea: Input-payload, trigger if name matches

### ISSUE THREAD

**Issue by ammawel** [csuermann/node-red-contrib-virtual-smart-home#36]
For input payload.name is not evaluated. If you want to control multiple virtual devices, e.g. via MQTT, it would be helpful if the name was optionally evaluated and the device only triggers if the name matches. (possibly regex?)
If no name is specified in the input-payload, the device switches as before.
What do you think?
Achim

**Comment by csuermann** [comment]
Thank you for suggesting this feature, @ammawel!

Happy to inform you that I just released it as part of v.1.20.0 .🎉
