### ISSUE TITLE
[Feature request] Support for color xyY 

### ISSUE THREAD

**Issue by steff75** [csuermann/node-red-contrib-virtual-smart-home#37]
Hi. I am using your very useful node to control some devices by voice with deCONZ. For color-changing-light-bulbs I had taken the HUE values from the output of your node and converted them for deCONZ in the right range.

Now I bought last week the LED band from Lidl/Silvercrest. This apparently does not accept color changes via HUE values, but XY works.
_Example: {"on":true, "xy":[0.4193, 0.5053],"bri":200}_

I found this thread in the forum how I can calculate these values with a function from RGB to use them with deCONZ.
[https://discourse.nodered.org/t/use-dashboard-color-picker-for-deconz-conbee2-rgbw-stripe/37207](https://discourse.nodered.org/t/use-dashboard-color-picker-for-deconz-conbee2-rgbw-stripe/37207)

Now I thought, since besides [deconz-rest-api](https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/#parameters_2) also the [API of Philips Hue](http://www.burgestrand.se/hue-api/api/lights/#changing-light-color-and-turning-them-onoff) has a use of the XY values for colors, that you could possibly consider these also with the output of your node.

Best regards and thank you!

**Comment by csuermann** [comment]
Hi @steff75,

I didn't have time yet to familiarize myself with all those different color encodings, but XY sounds somewhat similiar to XYZ, which VSH already outputs. Can you try to convert XYZ to XY using this formular:

```
float x = X / (X + Y + Z);
float y = Y / (X + Y + Z);
```

Let me know if this produces the desired results so I can add it as additional color output for the color changing lightbulb node.

**Comment by steff75** [comment]
Thanks for the answer. With the formula I have a different result than the one from the forum. The colors are not so rich and strong.

This is the formula from the function node that I use.
 
`function rgb_to_cie(red, green, blue)
{
	//Apply a gamma correction to the RGB values, which makes the color more vivid and more the like the color displayed on the screen of your device
	var red 	= (red > 0.04045) ? Math.pow((red + 0.055) / (1.0 + 0.055), 2.4) : (red / 12.92);
	var green 	= (green > 0.04045) ? Math.pow((green + 0.055) / (1.0 + 0.055), 2.4) : (green / 12.92);
	var blue 	= (blue > 0.04045) ? Math.pow((blue + 0.055) / (1.0 + 0.055), 2.4) : (blue / 12.92); 

	//RGB values to XYZ using the Wide RGB D65 conversion formula
	var X 		= red * 0.664511 + green * 0.154324 + blue * 0.162028;
	var Y 		= red * 0.283881 + green * 0.668433 + blue * 0.047685;
	var Z 		= red * 0.000088 + green * 0.072310 + blue * 0.986039;

	//Calculate the xy values from the XYZ values
	var x 		= (X / (X + Y + Z));
	var y 		= (Y / (X + Y + Z));
	
	//var z = Z;

	if (isNaN(x))
		x = 0;
	if (isNaN(y))
		y = 0;	 
	//return [x, y, z];
	return [x, y];
}
msg.payload.on = true;
msg.payload.xy = rgb_to_cie(msg.alexa.color_rgb[0], msg.alexa.color_rgb[1], msg.alexa.color_rgb[2]);
console.log(msg.payload);
return msg;`


In the video, you can see the difference in the two results when I let Alexa set the kitchen lamp to green.
https://user-images.githubusercontent.com/19283026/107120190-6db1a180-688c-11eb-8815-e1283ebd5eba.mp4

**Comment by csuermann** [comment]
Thank you, @steff75 for your code snipped, which I included in v1.21.0. Let me know if this now produces the desired output as `msg.payload.color_xy`.

**Comment by steff75** [comment]
Hello Cornelius!
Works great :)
