### ISSUE TITLE
Update Device State in Alexa App

### ISSUE THREAD

**Issue by Jan-Odin** [csuermann/node-red-contrib-virtual-smart-home#39]
Hello Cornelius,
I use the virtual device node to control my own light with wemos MCU. When i switch the color in the Alexa app to any color, it switches back to "warm white" after some seconds. I tried to send the VirtDev message back into the same node and changed the source to "device" before - as you mentioned here: https://discourse.nodered.org/t/announce-node-red-contrib-virtual-smart-home-for-alexa/34353. 
It still does not work. The Passthrough function is disabled. Otherwise I create an infinite loop - which still does not work. I tried ^^
Is there something I do wrong? Or am I too early, beacause this function isn't released yet? I attached some images ;)

Kind regards
Jan

![2021-02-07 01_35_54-Window](https://user-images.githubusercontent.com/50456204/107133057-daf12100-68e4-11eb-8bd8-557b614649e3.png)

![2021-02-07 01_36_18-Window](https://user-images.githubusercontent.com/50456204/107133064-e6dce300-68e4-11eb-8e59-73eaf8b8fac2.png)

![2021-02-07 01_36_56-Window](https://user-images.githubusercontent.com/50456204/107133078-fe1bd080-68e4-11eb-8209-2221ac38eb8a.png)

**Comment by csuermann** [comment]
Hi @Jan-Odin,

The `payload.source` attribute is read-only and just indicates the origin that triggered the vsh-node to emit a msg-object. It can either take the value 'alexa' when invoked via Alexa or 'device' in case of an inbound message.

You should generally only use inbound messages if you want local device changes (e.g. you switched a lamp on manually, or set the color of a light via the hue-app etc.) to be reflected in the Alexa app. There should never be the need to create a loop in your flow.

The symptom of the color switching back to the previous value in the Alexa app could indicate that the access-token used to sync the device state back to Alexa is no longer valid. In this case it might help to disable and re-enable the "virtual smart home" skill via the Alexa app. Also check whether a list of registered devices shows up on the edit dialogue of the vsh-connection in Node-RED.

Best Regards
Cornelius

**Comment by Nachtfalke49** [comment]
Hello,

I have that the same problem. The color always jumps back to a Kelvin value. Warm white or warm white etc. I have disabled and re-enabled the "virtual smart home" skill via the Alexa app. But it didn't help.

Regards,

Andi

**Comment by Jan-Odin** [comment]
Hey @csuermann ,

yep. I have the same problem as @Nachtfalke49 . Reenable the Skill didnt work.

Regards,

Jan

**Comment by csuermann** [comment]
Thanks for reporting this issue! I was able to partly reproduce it, but I need to investigate further. Will keep you posted.

**Comment by csuermann** [comment]
Could you kindly confirm that this issue no longer exist (since v2.x.x)? Thank you!

**Comment by Jan-Odin** [comment]
Hey Cornelius,

I just update to version 2.8.0.
Created a new VSH Connection and set my devices via discover in the Alexa
App.

Unfortunately the devices are not responding.

Kind regards
Jan

**Comment by csuermann** [comment]
Hi @Jan-Odin,

I'm sorry to hear you are still having issues with VSH (but at least different ones, as it seems 🙃).

> Unfortunately the devices are not responding.

Do you mean they don't react to directives or they don't show up in Alexa at all? Could you please enable Debug mode in the VSH connection node and observe stdout to see what gets sent over the wire when you restart your flow? Thanks for your help!

**Comment by Jan-Odin** [comment]
Hi,

The devices show up in the app, but don't react to directives -> "device is
not responding".

Now for the debug part:
I'm not quite sure if I did this correctly.
First I got the pid from node-red.

Then I used the following command: *readlink -f /proc/PID/fd/1 /tmp/file*

After I restarted the flows, the temp directory contains following
directories:

[image: image.png]

I don't think this is helpful, so please let me know what to do exactly.
Kind regards




Am Mi., 23. Juni 2021 um 06:26 Uhr schrieb Cornelius Suermann <
***@***.***>:

**Comment by csuermann** [comment]
Could you please paste the screenshot directly into GitHub? I think GitHub strips attachments when you reply via email.

**Comment by Jan-Odin** [comment]
Sure :)
![image](https://user-images.githubusercontent.com/50456204/123092422-bbd5d480-d42a-11eb-9ca8-3914f8bfac6b.png)

**Comment by csuermann** [comment]
Thanks!

To grep the logs of a running Node-RED instance, I had success using this command:

```bash
strace -p`pidof node-red` -s9999 -e write |& grep "vsh-connection"
```

It might however be easier to just start Node-RED manually by issuing `node-red` and observing the terminal.

**Comment by Jan-Odin** [comment]
Nice! The command worked.
Thats what I get when I restart the flow. I felt free to change my email and vsh id / token :)

> `write(1, "23 Jun 14:18:47 - [info] [vsh-connection:email] MQTT disconnecting\n", 82) = 82
> write(1, "23 Jun 14:18:47 - [info] [vsh-connection:email] MQTT publish to topic $aws/things/vsht-vsh-id/shadow/update: {\"state\":{\"reported\":{\"connected\":false}}}\n", 197) = 197
> write(1, "23 Jun 14:18:47 - [info] [vsh-connection:email] MQTT disconnected\n", 81) = 81
> write(1, "23 Jun 14:18:47 - [info] [vsh-connection:email] Attempting MQTT connection: a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883 (clientId: vsht-vsh-id)\n", 197) = 197
> write(1, "23 Jun 14:18:47 - [info] [vsh-connection:email] MQTT subscribe to topics: [\"$aws/things/vsht-vsh-id/shadow/get/accepted\",\"vsh/vsht-vsh-id/+/directive\",\"vsh/service\",\"vsh/version/2.8.0/+\",\"vsh/vsht-vsh-id/service\"]\n", 319) = 319
> write(1, "23 Jun 14:18:48 - [info] [vsh-connection:email] MQTT connecting to a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883\n", 134) = 134
> write(1, "23 Jun 14:18:48 - [info] [vsh-connection:email] MQTT publish to topic $aws/things/vsht-vsh-id/shadow/update: {\"state\":{\"reported\":{\"connected\":true,\"vsh_version\":\"2.8.0\",\"nr_version\":\"1.3.5\"}}}\n", 239) = 239
> write(1, "23 Jun 14:18:50 - [info] [vsh-connection:email] MQTT publish to topic vsh/vsht-vsh-id/requestConfig: {\"vshVersion\":\"2.8.0\"}\n", 169) = 169
> write(1, "23 Jun 14:18:50 - [info] [vsh-connection:email] MQTT message received on topic vsh/vsht-vsh-id/service: {\"operation\":\"overrideConfig\",\"userIdToken\":\"amzn1.account.token\",\"allowedDeviceCount\":100,\"rateLimiter\":[{\"period\":60000,\"limit\":12,\"penalty\":0,\"repeat\":10},{\"period\":600000,\"limit\":5,\"penalty\":1}]}\n", 413) = 413
> write(1, "23 Jun 14:18:50 - [info] [vsh-connection:email] MQTT publish to topic $aws/things/vsht-vsh-id/shadow/get: {}\n", 154) = 154
> write(1, "23 Jun 14:18:50 - [info] [vsh-connection:email] RateLimiter.overrideConfig: [\n  {\n    \"period\": 60000,\n    \"limit\": 12,\n    \"penalty\": 0,\n    \"repeat\": 10\n  },\n  {\n    \"period\": 600000,\n    \"limit\": 5,\n    \"penalty\": 1\n  }\n]\n", 240) = 240
> write(1, "23 Jun 14:18:50 - [info] [vsh-connection:email] MQTT message received on topic $aws/things/vsht-vsh-id/shadow/get/accepted: {\"state\":{\"reported\":{\"connected\":true,\"vsh_version\":\"2.8.0\",\"nr_version\":\"1.3.5\",\"devices\":{\"vshd-c9dee99acc2ac8\":{\"friendlyName\":\"PC Backlight\",\"template\":\"COLOR_CHANGING_LIGHT_BULB\"}}}},\"metadata\":{\"reported\":{\"connected\":{\"timestamp\":1624450728},\"vsh_version\":{\"timestamp\":1624450728},\"nr_version\":{\"timestamp\":1624450728},\"devices\":{\"vshd-c9dee99acc2ac8\":{\"friendlyName\":{\"timestamp\":1623794799},\"template\":{\"timestamp\":1623794799}}}}},\"version\":38,\"timestamp\":1624450730}\n", 647) = 647

`

**Comment by csuermann** [comment]
Great! That looks alright! What do you see in the logs when you instruct Alexa to "switch on PC Backlight"?

**Comment by Jan-Odin** [comment]
Thats what I get, when I open the device in the app. (Loading Screen with "Waiting for VSH")

```
write(1, "23 Jun 14:26:04 - [info] [vsh-connection:email] MQTT message received on topic vsh/vsht-id/vshd-id2/directive: {\"directive\":{\"header\":{\"namespace\":\"Alexa\",\"name\":\"ReportState\",\"correlationToken\":\"token1/tVd\"},\"endpoint\":{\"endpointId\":\"vshd-id2\"},\"payload\":{}}}\n", 1042) = 1042
write(1, "23 Jun 14:26:04 - [info] [vsh-connection:email] MQTT publish to topic vsh/vsht-id/changeReport: {\"endpointId\":\"vshd-id2\",\"properties\":[{\"namespace\":\"Alexa.BrightnessController\",\"name\":\"brightness\",\"value\":100,\"changed\":false},{\"namespace\":\"Alexa.ColorTemperatureController\",\"name\":\"colorTemperatureInKelvin\",\"value\":2200,\"changed\":false},{\"namespace\":\"Alexa.PowerController\",\"name\":\"powerState\",\"value\":\"OFF\",\"changed\":false}],\"correlationToken\":\"token1/tVd\",\"causeType\":\"STATE_REPORT\",\"vshVersion\":\"2.8.0\",\"userIdToken\":\"amzn1.account.amaznToken\"}\n", 1378) = 1378
write(1, "23 Jun 14:26:33 - [info] [vsh-connection:email] MQTT message received on topic vsh/vsht-id/vshd-id2/directive: {\"directive\":{\"header\":{\"namespace\":\"Alexa\",\"name\":\"ReportState\",\"correlationToken\":\"token2"},\"endpoint\":{\"endpointId\":\"vshd-id2\"},\"payload\":{}}}\n", 1042) = 1042
write(1, "23 Jun 14:26:33 - [info] [vsh-connection:email] MQTT publish to topic vsh/vsht-id/changeReport: {\"endpointId\":\"vshd-id2\",\"properties\":[{\"namespace\":\"Alexa.BrightnessController\",\"name\":\"brightness\",\"value\":100,\"changed\":false},{\"namespace\":\"Alexa.ColorTemperatureController\",\"name\":\"colorTemperatureInKelvin\",\"value\":2200,\"changed\":false},{\"namespace\":\"Alexa.PowerController\",\"name\":\"powerState\",\"value\":\"OFF\",\"changed\":false}],\"correlationToken\":\"token2",\"causeType\":\"STATE_REPORT\",\"vshVersion\":\"2.8.0\",\"userIdToken\":\"amzn1.account.amaznToken\"}\n", 1378) = 1378

```

**Comment by Jan-Odin** [comment]
And this, when I click "Power On" in the Alexa App:
```

write(1, "23 Jun 14:32:05 - [info] [vsh-connection:email] MQTT message received on topic vsh/vsht-id/vshd-id2/directive: {\"directive\":{\"header\":{\"namespace\":\"Alexa.PowerController\",\"name\":\"TurnOn\",\"correlationToken\":\"token"},\"endpoint\":{\"endpointId\":\"vshd-id2\"},\"payload\":{}}}\n", 1053) = 1053
write(1, "23 Jun 14:32:05 - [info] [vsh-connection:email] MQTT publish to topic vsh/vsht-id/changeReport: {\"endpointId\":\"vshd-id2\",\"properties\":[{\"namespace\":\"Alexa.BrightnessController\",\"name\":\"brightness\",\"value\":100,\"changed\":false},{\"namespace\":\"Alexa.ColorTemperatureController\",\"name\":\"colorTemperatureInKelvin\",\"value\":2200,\"changed\":false},{\"namespace\":\"Alexa.PowerController\",\"name\":\"powerState\",\"value\":\"ON\",\"changed\":true}],\"correlationToken\":\"token",\"causeType\":\"VOICE_INTERACTION\",\"vshVersion\":\"2.8.0\",\"userIdToken\":\"amzn1.account.amaznToken"}\n", 1381) = 1381

```

**Comment by csuermann** [comment]
Thank you! It looks like your accessToken stored in the VSH backend is not valid for whatever reason. Could you please try disabling and re-enabling the VSH skill?

**Comment by Jan-Odin** [comment]
Haha, thats the simplest solution ever.
Next time I'll try this first. Thanks a lot!

The reason might be the update from a lower version?

**Comment by csuermann** [comment]
So did this do the trick?

I'm not yet quite sure where this problem lies. It shouldn't be related to the version update, though.

**Comment by Jan-Odin** [comment]
Yes, it's working fine now :)
