### ISSUE TITLE
Your node seems to cause me a UI issue in NR itself

### ISSUE THREAD

**Issue by cymplecy** [csuermann/node-red-contrib-virtual-smart-home#4]
See https://discourse.nodered.org/t/tab-links-are-underlined-on-one-nr-instance/33981

**Comment by knolleary** [comment]
The root cause is the CSS selectors used by this node are too generic.

https://github.com/csuermann/node-red-contrib-virtual-smart-home/blob/master/connection.html#L359

They should all use some node-specific prefix in their names to ensure they don't clash with existing styles.

**Comment by csuermann** [comment]
Thank you for reporting this nasty glitch. Sorry for the inconvenience! It's fixed and releases in v1.6.3 just now.

@knolleary, any plans to isolate nodes better from each other? I believe at least a best-practice mentioned in the docs would be helpful. But there were other instances where I ran into a similar problem, e.g. naming conflicts between nodes, which could be avoided by some sort of namespace mechanism, I guess...

Cornelius

**Comment by knolleary** [comment]
Given the way nodes are loaded, there is no way we can dynamically namespace css for you - we have no idea how you are using the css classes, so we can't simply rewrite them. We may be able to do something in the Flow Library when we index nodes to flag up potential issues.
