### ISSUE TITLE
Temperature-sensor: Error in AlexaApp at value 0

### ISSUE THREAD

**Issue by ammawel** [csuermann/node-red-contrib-virtual-smart-home#40]
When I set the value in the temperature-sensor to exactly 0 or 0.0, the AlexaApp reports "A problem has occurred / Ein Problem ist aufgetreten" and shows no value. Emit state shows no error.
As a workaround, I am currently adding 0.001.
Thanks!
Achim

**Comment by csuermann** [comment]
Hi @ammawel,

Thanks for reporting this issue, which should be fixed now.

Best Regards
Cornelius
