### ISSUE TITLE
input to Alexa

### ISSUE THREAD

**Issue by marcobrianza** [csuermann/node-red-contrib-virtual-smart-home#41]
Hi, first of all congratulations for this integration.I could make it work in 5 minutes.
From what I see Alexa is always woking as input device. I ask something and a message arrives in node-red.
Is there a way to trigger something in Alexa, for example a routine or a scene with a message from Node-Red?

**Comment by csuermann** [comment]
Hi @marcobrianza,

Thanks for reaching out and your donation!

It is currently not possible to trigger Alexa routines from Node-RED using the virtual-smart-home package.

**Comment by marcobrianza** [comment]
Hi, is this a limit of Alexa itself or of your current implementation? 
I would use this feature to trigger devices directly controlled by Alexa and not present in node-red

**Comment by csuermann** [comment]
As far as I know Alexa supports triggering routines only from a few selected smart sensors, not generally from any smart home device.
