### ISSUE TITLE
quota exhausted

### ISSUE THREAD

**Issue by taberner** [csuermann/node-red-contrib-virtual-smart-home#42]
I have a flow with a virtual switch connected to a debug node, nothing else. After a short period of running it goes offline and says connection quota exhausted... what am I doing wrong?
![Screen Shot 2021-02-15 at 16 32 30](https://user-images.githubusercontent.com/79103825/107973212-de536f00-6fac-11eb-9e1b-1b60439cbe1b.png)

**Comment by csuermann** [comment]
Hi @taberner,

I assume before the "connection quota exhausted" message appears, the device state toggles between "online" and "offline" a few times? If that's the case, there might be another zombie-connection trying to connect to the MQTT backend with the same credentials, which causes the first connection to be dropped. Try restarting your Node-RED instance or even your entire system.

Hope that helps!
Cornelius

**Comment by taberner** [comment]
HI Cornelius,

Thanks for the ideas. Yes, the node does toggle on and offline a couple of times before the final failure.

So far I’ve got to the following:

Restart node-red - node starts online but fails again after a few minutes
Uninstalled and reinstalled node-red using nom = problem persists
Uninstalled Alexa skill and node red, re-installed both and created new connection to amazon to link the skill and node red = same symptoms

Any other suggestions? - I wondered if it is a resource issue on the node red system - it’s running under termux on an old android phone, but the phone was top end about 4 years ago, so I would have thought it would be OK. I have also installed the smart things nodes and these continue to run so I guess not.

Thanks,

Tim

**Comment by csuermann** [comment]
Hi Tim,

Thanks for providing these information!

How much time passes between the disconnects? Do the disconnects happen relatively randomly or in a periodic fashion?

Just to eliminate another potential root-cause: The vsh-connection parameters are only used by your one and only Node-RED installation, correct? E.g. you have not backed it up and running elsewhere?

For further debugging you could try to study the MQTT logs which get dumped to stdout if you set this environment variable before starting Node-RED:

`export DEBUG='mqttjs*'`

**Comment by taberner** [comment]
Hi Cornelius,

It’s pretty consistent - see below timings from the node red debug screen on 4 consecutive restarts:

Stage	run 1	run 2	run 3	run 4
Node-red full deploy	13:26:01	delta	13:44:21	delta	13:51:51	delta	14:03:27	delta
offline	13:28:28	00:02:27	13:46:52	00:02:31	13:54:11	00:02:20	14:05:51	00:02:24
online	13:28:53	00:00:25	13:47:24	00:00:32	13:54:41	00:00:30	14:06:07	00:00:16
offline	13:31:09	00:02:16	13:49:39	00:02:15	13:56:57	00:02:16	14:08:23	00:02:16
online	13:31:24	00:00:15	13:49:54	00:00:15	13:57:41	00:00:44	14:08:33	00:00:10
offline	13:31:24	00:00:00	13:49:54	00:00:00	13:57:41	00:00:00	14:08:33	00:00:00
Quota exhausted	13:31:42	00:00:18	13:50:31	00:00:37	not seen after 5 minutes	14:08:37	00:00:04
but appeared immediately 		
node red log deleted		

Will have a go at dumping the MQTT logs, but may be stretching my Linux skills a bit ;-)

Thanks

Tim

**Comment by taberner** [comment]
Hmm, moved the phone to be  able see the logs, and it hasn’t crashed since, so something to do with connections not clearing properly when broken I think.

Do you use the MQTT clean session flag when creating the connections?

Cheers,

Tim

**Comment by csuermann** [comment]
Hi Tim,

Yes, I believe `clean` is the default. Why do you think this might be related to the connection drops?

It looks like your connection does not drop due to a conflicting connection but rather because of general connectivity issues. If this happens too often you run into this quota message. Maybe the MQTT logs will point us into the right direction.

**Comment by csuermann** [comment]
Hi @taberner,

Have you been able to analyse this further?

Best Regard
C.

**Comment by taberner** [comment]
Hi Cornelius,

Sorry, no - I ended up achieving what I wanted to do using Smartthings, so lost the impetus to investigate further.

Regards,

Tim
