### ISSUE TITLE
Device cannot be deleted

### ISSUE THREAD

**Issue by salviador** [csuermann/node-red-contrib-virtual-smart-home#43]
Error in the account, I can't delete the old devices registered previously, it gives me "ERROR"

![Immagine](https://user-images.githubusercontent.com/8354325/108236205-e9da9d80-7146-11eb-85d1-23f975359f51.png)

**Comment by csuermann** [comment]
Hi @salviador,

Thanks for reaching out!

This error message should only appear when the deletion failed, typically because the device was already deleted. Does the device still appear when you close and reopen the vsh-connection node details?

**Comment by salviador** [comment]
the device is no longer visible in node-red "vsh-connection", but the problem is that the alexa app keeps finding previously added devices

**Comment by csuermann** [comment]
Hmm, that's strange. Alexa can only (re)discover devices that are still stored in the vsh backend. And those should be listed in the vsh-connection screen as long as they were indeed linked to the same amazon account. You could try to re-enable the virtual smart home skill.

**Comment by csuermann** [comment]
Hi @salviador,

Have you been able to resolve this issue on your side?

**Comment by salviador** [comment]
yes, the problem I think was logging in with two different accounts and I messed up

**Comment by csuermann** [comment]
Thanks for reporting back on this! Glad to hear you were able to resolve this.
