### ISSUE TITLE
Alexa skill

### ISSUE THREAD

**Issue by socramone** [csuermann/node-red-contrib-virtual-smart-home#45]
Hi csuermann!
First of all I need to say thank you for sharing this amazing tool for the guys that we love to domotize our homes. I really appreciate people like you.

I have open this “issue” because I would like to learn about creating my personal Alexa skill to communicate with your node red contrib so I wanted to ask you if you will share this info with us? 

Thank you in advance :)

**Comment by csuermann** [comment]
Hi @socramone,

Thanks for your kind words!

I'm afraid linking a custom-built Alexa skill to the VSH Node-RED contribution is not possible, as the package is tightly coupled to my backend implementation.

However, you can of course [build your own personal Alexa skill](https://developer.amazon.com/en-US/docs/alexa/smarthome/steps-to-build-a-smart-home-skill.html) and use the open sourced VSH Node-RED package as a source for inspiration.

Let me know if you have any concrete questions to get you started on this journey.

Best Regards
C.
