### ISSUE TITLE
[Feature Request] Arbitrary state device

### ISSUE THREAD

**Issue by DieKatzchen** [csuermann/node-red-contrib-virtual-smart-home#46]
Unsure if this is even possible, but a device sort of like the "color change bulb" only I can either just say "Alexa, set MyThing to ArbitraryWord" or that I can preset various states for. My use case is to be able to control TV inputs. I can currently set them from node-red, the problem is that I now have to expose a switch for every input option and then give a clunky command like "Alexa, turn on DownstairsTV_input3" instead of just "Alexa, set DownstairsTV to Input3". Bonus if it can use Alexa's area functionality so I can name them all TV and it'll determine based on room like it does for "turn on the lights" Even better if it can be done as a switch so that it doesn't try to turn on the TV when I turn on the lights (although easily enough worked around by having a separate virtual switch for turning on and ignoring the power signal from the multistate)

**Comment by csuermann** [comment]
Hi @DieKatzchen,

Thanks for submitting this feature request.

The current implementation of VSH is based on Amazon's pre-build smart-home skillset, which provides a best in class experience for controlling smart home devices. On the other hand this is somewhat limiting the functionality VSH can provide.

For your concrete use case, an "Entertainment Device" seems to do the trick, though:

https://developer.amazon.com/en-US/docs/alexa/smarthome/get-started-with-device-templates.html#entertainment-device

Let me know if you believe this would solve your problem so I can consider adding a virtual entertainment device to the package.

Best Regards
C.

**Comment by DieKatzchen** [comment]
This looks like exactly what I need! Way better than my idea. Especially if the inputs can be named in Alexa. I can see from the spec that there are is a very limited number of valid input names in the skill (Why PlayStation and Xbox, but no Nintendo brand inputs? seems biased). I've never used an Alexa supported "entertainment device", though so I don't know if they can. Seems reasonable, though, right?

**Comment by DieKatzchen** [comment]
Actually, looking into it, it seems that people with real "entertainment device" hardware can name the inputs things that aren't on that list and the only issue is that badly named inputs give bad results. So perhaps the spec does allow for arbitrary names, and they just didn't document it.
