### ISSUE TITLE
Alexa App isn't showing actual state

### ISSUE THREAD

**Issue by nicedevil007** [csuermann/node-red-contrib-virtual-smart-home#47]
hey Cornelius,

found a new problem maybe it is only the part sitting right in front of the screen :D 

I'm deploying smarthome at my friends environment from scratch right now.
For now he is using alexa app to touch the buttons on the app to control his devices. So if we change the state of a switch inside node-red from any other source the state on the alexa app should be updated as well.

Here an example what we sent to your virtual device node's input to get this to work (but it is not right now):

```
{
  "name":"Kellerraum",
  "powerState":"ON",
  "directive":"TurnOn"
}
```

Do we only need the `powerState` for the input? We already tested this but didn't work as well. But that was written in the help part of your node.

Ty you in advance again!

**Comment by csuermann** [comment]
Hi @nicedevil007,

For which VSH version did you observe this behaviour?

To update the state in the alexa app your inbound `msg` only needs to contain the attributes to update as _payload_ , e.g. 

```javascript
{
  "payload": {
    "powerState": "ON"
  }
}
```
Any other attributes will simply be ignored.

Note that VSH is rate-limiting synchronizing local state changes to Alexa to 1 message per device per 10 minutes. For the first 3 minutes after starting up your flow, you'll get a quota of 12 requests per minute, though, which should be enough for testing.

I will shortly add a debugging toggle to enable you to see respective log messages for troubleshooting.

**Comment by nicedevil007** [comment]
ah ok, so the problem was then the 1 message per device in 10 min....
Friend wanted to use the Alexa Dashboard instead of anything else so maybe I have to tell him that he has to switch :P

Is latest build of your VSH plugin. Was just installed yesterday.

**Comment by csuermann** [comment]
Thanks for your quick response! Yeah, this rate-limiter bothers me, too. It's a sledge-hammer approach for protecting my AWS costs to explode as some users (mis)configured their setup to send just way too many messages.
