### ISSUE TITLE
Use the Virtual Device to make announcements on Alexa device?

### ISSUE THREAD

**Issue by emlarsen1** [csuermann/node-red-contrib-virtual-smart-home#50]
Is there any way we could create a virtual device that we could pass text to Alexa echo or show and have it announced?

**Comment by csuermann** [comment]
Hi @emlarsen1,

No, that's unfortunately not possible. The scope of VSH is limited to the official smart home skill capabilities provided by Amazon.

Have you checked out this node, which I believe can do what you want? https://flows.nodered.org/node/node-red-contrib-alexa-remote2

Best
C.
