### ISSUE TITLE
Abnormal network activity

### ISSUE THREAD

**Issue by fmarzocca** [csuermann/node-red-contrib-virtual-smart-home#51]
Hi,

do you have any data on network activity of your module? I have deployed around 20 virtual devices, and my Raspberry has become extremely slow on network operations.
Could it be that I have deployed too many devices?

**Comment by csuermann** [comment]
Hi @fmarzocca,

I am not aware of any heavy network impact coming from VSH. In fact all virtual devices share the same MQTT connection and don't add any network activity at all unless messages are being transmitted (e.g. originating from Alexa directives).

Which version are you using?
How many vsh-connection nodes (not to mistake for devices) do you have configured?
Have you tried to switch on the 'Debug' option to analyze the messages going over the wire?

Best regards
C.

**Comment by fmarzocca** [comment]
Hi Cornelius, thanks for answering.
I have 46 devices and 46 nodes using the configuration node.
Version is 1.22.0

Maybe is not your module generating all this network activity. I have also another one installed (alexa-remote2-cakebaked) and I need to further investigate.

Thank you.
Fabio

**Comment by csuermann** [comment]
Thanks for reporting back, @fmarzocca! Feel free to re-open this ticket if your investigation indeed surfaces a problem with VSH.
