### ISSUE TITLE
Name of the Alexa Echo device

### ISSUE THREAD

**Issue by Evil-Nemo** [csuermann/node-red-contrib-virtual-smart-home#53]
Hello, 
Is it possible to pass in the msg.payload object also the name of the Alexa Echo device that has received my command? 
So a control like 'light on / off' would be possible without defining an own name for the room. 

Hallo,
Besteht die Möglichkeit in das msg.payload Objekt auch den Namen der Alexa zu übergeben, diese meinen Befehl empfangen hat? 
Damit wäre eine Steuerung wie ‚Licht an / aus‘ ohne einen eigene Namen für den Raum zu definieren möglich.

**Comment by csuermann** [comment]
Hi @Evil-Nemo,

Unfortunately Alexa's smart home skill (which VSH is based on) does not expose the name of the Alexa device.

However, you can still accomplish what you want by grouping your virtual devices and the respective Alexa device into one room. (see [FAQ #2](https://flows.nodered.org/node/node-red-contrib-virtual-smart-home))

Q: How can I control devices in a specific room?

A: You can create rooms in the Alexa app and assign your devices to them. Create a room which groups together an Alexa device (e.g. Echo) and some virtual lights. You can then control all those lights simply by speaking "Alexa, switch off the light" into the Alexa device.
