### ISSUE TITLE
I miss the stop option on blinds

### ISSUE THREAD

**Issue by Evil-Nemo** [csuermann/node-red-contrib-virtual-smart-home#54]
Hello, as I read in your documentation, the blinds can only be set up, down and to position. What I miss is the 'stop'. 
If I read that correctly on Smart Home Skill APIs, that's not supported there either. Do you have any ideas?
Thank you and keep it up 
Mike

**Comment by csuermann** [comment]
Hi @Evil-Nemo,

You're right. That's unfortunately not supported by Alexa.

Best Regards
C.
