### ISSUE TITLE
Nodes changing behavior

### ISSUE THREAD

**Issue by fmarzocca** [csuermann/node-red-contrib-virtual-smart-home#55]
Occasionally, my vsh nodes changes behaviour and don't understand vocal commands. 
i.e.: a device set as a switch is answering like a blind that doesn't understand the command or the other way round.

Maybe I am missing something? Should I send something in the input of the node? I have just configured the node as a "switch", triggering a flow on my vocal "turn on2 or "turn off". It works for several days, and then it stops working answering that she doesn't understand how to "set" the device (assuming it is a blind).

Thanks for clarifying.

**Comment by csuermann** [comment]
Hi @fmarzocca,

Do your devices show up with the correct type in Node-RED as well as in the Alexa-App?

If you have devices with similar names, Alexa might also mistake them. In those cases it might help to say "switch off the light foo" instead of just "switch off foo".

**Comment by fmarzocca** [comment]
Yes, they show up with the correct device, and they work fine if I "restart all flows". But after few days they start to become "confused" and I have to restart again all flows.

**Comment by fmarzocca** [comment]
currently in Alexa-app there are all shown as virth.smart-home object (no light, switch, blind..)

**Comment by csuermann** [comment]
Well, that's strange! Devices are only discovered once by Alexa when you deploy them as part of your flows. They are then kept in Amazon's database. When you interact with Alexa, this database in consulted to figure out how to interpret your command.

Could you please post a screenshot of your Alexa app showing what you describe?

**Comment by fmarzocca** [comment]
![photo_2021-03-18 16 30 21](https://user-images.githubusercontent.com/8530030/111652371-53fa6700-8807-11eb-8471-c45b6054df61.jpeg)
![photo_2021-03-18 16 30 29](https://user-images.githubusercontent.com/8530030/111652391-565cc100-8807-11eb-8f3b-15a6671f936f.jpeg)
![photo_2021-03-18 16 30 48](https://user-images.githubusercontent.com/8530030/111652429-5a88de80-8807-11eb-92f0-651464dae5b9.jpeg)

**Comment by csuermann** [comment]
ah, that's a screenshot of the browser based Alexa app, right? I think they don't include much device information there. Do you happen to have the iOS / Android Alexa app installed as well? There you should see more information, e.g. corresponding icons:

![image](https://user-images.githubusercontent.com/10939809/111661922-c2432780-880f-11eb-8a39-b8ffec2d3ab6.png)

**Comment by fmarzocca** [comment]
![photo_2021-03-18 17 40 47](https://user-images.githubusercontent.com/8530030/111663457-1dc1e500-8811-11eb-921e-c04da69fefea.jpeg)

**Comment by csuermann** [comment]
Thanks, that looks right to me. Lights are lights and blinds are blinds. Or am I missing something?

**Comment by fmarzocca** [comment]
No, you are correct. But after a while the lights (switches) stop responding as lights and don't understand the "turn on" or "turn off", but respond to "raise" "down"

**Comment by csuermann** [comment]
Strange. Have you checked the Alexa log of what she understood?

**Comment by fmarzocca** [comment]
Yes. I'm italian, so I have checked that she understood "Turn On". But she answered as if it was a blind. Restarting all the flows, it works again. Isn't there a way to "reset" vsh?

**Comment by csuermann** [comment]
Hmm, I'm starting to run out of ideas. Are there any abnormalities in the Node-RED console output (with the VSH-connection Debug option switched on)?

**Comment by fmarzocca** [comment]
![Screenshot_20210318-195242_Amazon Alexa](https://user-images.githubusercontent.com/8530030/111681549-a8134480-8823-11eb-83a2-abad583034d6.jpg)

Every time I speak to Alexa for a virtual device, I see in the log a message saying "It was not possibile to understand the audio". Is it normal?

**Comment by fmarzocca** [comment]
I have set "Debug" in the configuration node, but I don't see any change in the debug messages exiting from  the vsh node.

**Comment by fmarzocca** [comment]
Cornelius,
as an example. I have a curtain that I have set as a Blind and when it works it correctly respond to command "Open" and "Close", sending percentage 0 or 100.
Now, if I say "Open" Alexa answers that the device has no "Open" ability. If I say "Turn Off" to the blind, it correctly responds with this message:
`{"topic":"living/blinds","payload":{"percentage":0,"source":"alexa","mode":"Position.Down","directive":"SetRangeValue","name":"Tenda Pranzo","type":"BLINDS"},"_msgid":"3e9b0fb5.4a0bf"}`

But I cannot say Turn On to a curtain!

**Comment by fmarzocca** [comment]
I am not using the topic. Is it important for some reason?

**Comment by fmarzocca** [comment]
I have realized that I left topic = /living/blinds for all of the devices. Is that important? How does the msg.topic act for your devices?

**Comment by csuermann** [comment]
Hi @fmarzocca,

Between 19:50:00 and 19:50:59 I see 3 `Blind.Lift` directives in my server logs:

```JSON
{
    "directive": {
        "header": {
            "namespace": "Alexa.RangeController",
            "name": "SetRangeValue",
            "payloadVersion": "3",
            "instance": "Blind.Lift",
            "messageId": "fbb0fe77-0b48-447d-ae7c-xxxxxxxxx",
            "correlationToken": "AAAAAAAAAxxx"
        },
        "endpoint": {
            "scope": {
                "type": "BearerToken",
                "token": "Atza|IwEBIFxxx"
            },
            "endpointId": "vshd-64d2e5d6xxxxxx",
            "cookie": {
                "template": "BLINDS",
                "thingId": "vsht-c7cb523c-00fe-449b-9ffc-xxxxxxxx"
            }
        },
        "payload": {
            "rangeValue": 100
        }
    }
}
```

So at least the command is hitting my backend.

The topic field should not be relevant here at all. It's just an additional attribute that vsh nodes emit as part of their outbound msg objects.

**Comment by fmarzocca** [comment]
Yes, the command is hitting your backend, but I had to say "Turn Blind ON" and "Turn blind OFF". That's not normal. If I reset flows, I can correctly say "Raise blind UP" and "lower blind down" (in italian)

**Comment by csuermann** [comment]
Are you using VSH devices on subflows, by any chance?

**Comment by fmarzocca** [comment]
No, not at all.

**Comment by csuermann** [comment]
You are the first person describing this kind of strange behaviour. And I'm out of advise :-(

Could you please share a JSON export of your flows?

**Comment by fmarzocca** [comment]
> And maybe you could let me know a few examples:
> 
> * the exact time you told Alexa which command
> * what she did
> * the vsh debug output you observe

You can take your last 3 hits in your server: as I said I had to interact with Blinds as if they were switches. Now I will export the flows for you

**Comment by fmarzocca** [comment]
https://gist.github.com/fmarzocca/e70435315e433786aff319ac0898d3cf

**Comment by fmarzocca** [comment]
I think I will try creating a brand new Alexa account and restarting from scratch.
Thank you for your time

**Comment by fmarzocca** [comment]
Cornelius,
with the help of the node alexa-remote2 I have gathered some interesting point.

This is a curtain, that I named "Tenda studio" and that I have set as Blind type:

```
{
      "id":"fff69aca-8fa4-40a1-a7ae-bb60397f0168",
      "displayName":"Tenda Studio Gioia",
      "description":"virtual blinds: Tenda Studio Gioia",
      "supportedProperties":[
         "setRangeValue@fff69aca-8fa4-40a1-a7ae-bb60397f0168_Blind.Lift"
      ],
      "supportedTriggers":[
         
      ],
      "supportedOperations":[
         "setRangeValue@fff69aca-8fa4-40a1-a7ae-bb60397f0168_Blind.Lift"
      ],
      "availability":"AVAILABLE",
      "icon":{
         "value":"INTERIOR_BLIND"
      },
      "providerData":{
         "enabled":true,
         "relationships":[
            
         ],
         "categoryType":"APPLIANCE",
         "deviceType":"INTERIOR_BLIND"
      }
   },
```

Now, I have just tell it to open (Apri tenda studio), but Alexa answered "_I don't know how to adjust the Tenda Studio device to that setting_". And this is for all Blind types. They work correctly only if a restart NodeRed (but for few hours).

```
{
   "data":{
      "recordKey":"A3URVYJ5I6FJ46#1616420754305#A32DOYMUN6DTXA#G090U610911613DD",
      "recordType":"VOICE_HISTORY",
      "timestamp":1616420754305,
      "customerId":"A3URVYJ5I6FJ46",
      "device":{
         "deviceName":"Echo dot Studio",
         "deviceEntityId":null
      },
      "isBinaryFeedbackProvided":false,
      "isFeedbackPositive":false,
      "utteranceType":"GENERAL",
      "domain":"HomeAutomation",
      "intent":"SetValueIntent",
      "skillName":"",
      "voiceHistoryRecordItems":[
         {
            "recordItemKey":"1616420754305#A32DOYMUN6DTXA#G090U610911613DD#1616420752748-0",
            "recordItemType":"CUSTOMER_TRANSCRIPT",
            "utteranceId":"A32DOYMUN6DTXA:1.0/2021/03/22/13/G090U610911613DD/45:51::TNIH_2V.c6942dd8-9697-4b9a-b626-31613fc8e35cLPM/1",
            "timestamp":1616420752748,
            "transcriptText":"chiudi tenda studio"
         },
         {
            "recordItemKey":"1616420754305#A32DOYMUN6DTXA#G090U610911613DD#1616420754307-2",
            "recordItemType":"ALEXA_RESPONSE",
            "utteranceId":"A32DOYMUN6DTXA:1.0/2021/03/22/13/G090U610911613DD/45:51::TNIH_2V.c6942dd8-9697-4b9a-b626-31613fc8e35cLPM/1",
            "timestamp":1616420754307,
            "transcriptText":"Non so come regolare il dispositivo Tenda Studio su quell’impostazione."
         }
      ]
   },
   "conversionDetails":{
      "CUSTOMER_TRANSCRIPT":[
         {
            "recordItemKey":"1616420754305#A32DOYMUN6DTXA#G090U610911613DD#1616420752748-0",
            "recordItemType":"CUSTOMER_TRANSCRIPT",
            "utteranceId":"A32DOYMUN6DTXA:1.0/2021/03/22/13/G090U610911613DD/45:51::TNIH_2V.c6942dd8-9697-4b9a-b626-31613fc8e35cLPM/1",
            "timestamp":1616420752748,
            "transcriptText":"chiudi tenda studio"
         }
      ],
      "ALEXA_RESPONSE":[
         {
            "recordItemKey":"1616420754305#A32DOYMUN6DTXA#G090U610911613DD#1616420754307-2",
            "recordItemType":"ALEXA_RESPONSE",
            "utteranceId":"A32DOYMUN6DTXA:1.0/2021/03/22/13/G090U610911613DD/45:51::TNIH_2V.c6942dd8-9697-4b9a-b626-31613fc8e35cLPM/1",
            "timestamp":1616420754307,
            "transcriptText":"Non so come regolare il dispositivo Tenda Studio su quell’impostazione."
         }
      ]
   },
   "deviceType":"A32DOYMUN6DTXA",
   "creationTimestamp":1616420754305,
   "deviceSerialNumber":"G090U610911613DD",
   "name":"Echo dot Studio",
   "description":{
      "summary":"chiudi tenda studio"
   },
   "alexaResponse":"Non so come regolare il dispositivo Tenda Studio su quell’impostazione.",
   "destinationUserId":"A3URVYJ5I6FJ46"
}
```

**Comment by csuermann** [comment]
Do you observe any difference in the alexa-remote2 logs when it _does work_ compared to when Alexa _does not understand_ your command?

**Comment by fmarzocca** [comment]
Not at all. When it works, it correctly understands "Open"/"Close" and the output is not including that response.

**Comment by fmarzocca** [comment]
The weird thing is that after a full restart of NodeRed, it works for awhile. Isn't there a way to restart the module?

Do you think that opening a completely new Alexa account  could be an option?

**Comment by csuermann** [comment]
I don't get how restarting the flows fixes the problem. After all, the Node-RED client does nothing but waiting for messages from the backend, which gets invoked by Alexa. It doesn't do anything that should change any configuration of Alexa (e.g. misconfiguring the device type or so). The only moment VSH sends device config to Alexa is when you deploy a new virtual device (discovery).

To debug this further, you could switch on the "Debug" option in the vsh-connection node and observe the MQTT messages being exchanged with the backend over the course of a few hours. Maybe you come across anything peculiar that hints us to the root of this nasty issue. 🤞

**Comment by fmarzocca** [comment]
I am attaching here the log file, with the Debug enabled. It doesn't help too much. The "Blind" devices are always failing to understand the correct command, but they react only to command as if they were Switches. (i.e.: "turn on kitchen blind").


[syslog.log](https://github.com/csuermann/node-red-contrib-virtual-smart-home/files/6202536/syslog.log)

**Comment by csuermann** [comment]
Thank you for providing the logs. You mentioned that initially everything works and after a few hours devices start to misbehave. Can you point me to the position in your logs where the problem began to occur?

**Comment by fmarzocca** [comment]
The logs have been taken when the problem was already occurring. As the
whole project is in production, I cannot restart NodeRed too often.

**Comment by fmarzocca** [comment]
I made an interesting test. While the system is correctly working (few minutes), the "Blind" devices accept either the command "Open" and the command "Turn On"! That should not be. An as soon as it stops working, the Blind devices only accept "Turn On".
Do you have other users with italian language?

**Comment by csuermann** [comment]
It would be really good to have logs covering the period when the skill transitions from working to not working properly. After all, there must be _something_ going on on the client side, otherwise restarting the flows wouldn't help.

I cannot tell how many Italian users I have (I don't analyze this), but I'm quite sure you are by far not the only one ;-)

**Comment by fmarzocca** [comment]
To give you more informations:
In this environment there are 6 echo devices (all connected to the same account). Yesterday we made a test: we removed all devices, factory reset all of them, reinstalled one and made a discovery. It worked. Then we reinstalled another one, but at the third one it stopped working. 
Log is attached.
[syslog.log](https://github.com/csuermann/node-red-contrib-virtual-smart-home/files/6210027/syslog.log)

**Comment by csuermann** [comment]
I don't see anything suspicious in the logs. How does Alexa behave if you leave your Node-RED completely switched off? Does she still complain not being able to execute certain commands?

**Comment by fmarzocca** [comment]
This is hard to say as I need to block the full home automation (which is large). Will see if we can make a fast test.

**Comment by fmarzocca** [comment]
Cornelius,

it seems we have found a workaround, I'll try to explain. The blinds were registered with 2 names: "Tapparelle Cucina" (kitchen blinds) but when we said "Apri Tapparelle Cucina" (Open Kitchen Binds) it was failing. We had to change the names of all the blind devices with one single name: "Tapparellecucina" (kitchenblinds). Now it works. We will monitor to see how long it works! 
It is weird, but every blind device respond either to the command "Open" and to the command "Turn On".

**Comment by csuermann** [comment]
Interesting finding! This seems to help with Alexa understanding which device you meant. I still don't get how restarting your Node-RED flows could have had any impact on this behaviour, though.

**Comment by csuermann** [comment]
Hi @fmarzocca, has your workaround proved to be stable?

**Comment by fmarzocca** [comment]
Yes, as of today it is still working!
