### ISSUE TITLE
Use in node-red docker container running in a docker network as opposed to host network

### ISSUE THREAD

**Issue by cornydesouza** [csuermann/node-red-contrib-virtual-smart-home#56]
Hello,

I would like to use the virtual devices in a node-red docker container running in a docker network as opposed to host network.

Is this possible and which ports would I need to forward from the host network to the docker container network in order for this to work?

Thanks

**Comment by csuermann** [comment]
Hi @cornydesouza,

VSH uses MQTT port 8883, but I don't think you need to expose that since the connection is established from inside Node-RED.

**Comment by cornydesouza** [comment]
Hallo,

indeed, works great, no port forwarding required.

Thanks
