### ISSUE TITLE
DIscriminate Echo device

### ISSUE THREAD

**Issue by fmarzocca** [csuermann/node-red-contrib-virtual-smart-home#58]
Is it possible to discriminate which Echo device has got the speech request? Or set a request for a specific Echo device?

**Comment by csuermann** [comment]
Hi @fmarzocca,

Unfortunately the Alexa Smart Home API doesn't expose the echo device commands were directed at.

But perhaps [FAQ #2](https://github.com/csuermann/node-red-contrib-virtual-smart-home#faq) is still helpful for you:

> Q: How can I control devices in a specific room?
> 
> A: You can create rooms in the Alexa app and assign your devices to them. Create a room which groups together an Alexa device (e.g. Echo) and some virtual lights. You can then control all those lights simply by speaking "Alexa, switch off the light" into the Alexa device.

**Comment by fmarzocca** [comment]
Thanks!
