### ISSUE TITLE
adding extra devices

### ISSUE THREAD

**Issue by E1cid** [csuermann/node-red-contrib-virtual-smart-home#6]
Hi 
when asking alexa to discover new devices for other things, alexa also rediscovers the smart home device, adding multiple devices with same name.

**Comment by csuermann** [comment]
Hi,
Can you please share your "Thing ID" that can be found in the settings of the vsh-connection node in Node-in RED? Also, please validate that the "registered devices" section does not contain any duplicates.

**Comment by E1cid** [comment]
Thing ID sent in pm on node-red forum

**Comment by E1cid** [comment]
The registered devices did contain 3 extra devices, i delete  devices there and in alexa app. then re deployed flow. all is good as of now.. Just thought i would raise the issue.

**Comment by csuermann** [comment]
I could not debug the problem since the duplicate devices were already deleted. But since virtual devices are uniquely identified by their node ID (assigned by Node-RED), I'm guessing that there must have been duplicated vsh nodes at one point. The fact that those devices also showed up in the "registered devices" section underpins this assumption.

**Comment by E1cid** [comment]
I will keep an eye on this, as i deleted the duplicates alexa and registered devices 5 days ago. Then yesterday when adding other devices (not virtual smart). Alexa added 3 devices and the  3 registered reappeared. I will report back any other issues and if devices reappear i will not delete then till you have had a chance to look into it. I did create one identical device 5 days ago, but deleted  the first with in minutes, confused as to why 3 registered devices would appear.
cheers

**Comment by csuermann** [comment]
Where did you delete the devices? From the "registered devices" section in the vsh-connection editor or using the Alexa app?

**Comment by E1cid** [comment]
Both

**Comment by csuermann** [comment]
When you delete devices via the registered devices section, they should automatically get deleted from Alexa, too.
