### ISSUE TITLE
[FeatureRequest] India?

### ISSUE THREAD

**Issue by timaseth** [csuermann/node-red-contrib-virtual-smart-home#60]
Any plans for alexa.amazon.in?
We are eagerly waiting :-)

**Comment by csuermann** [comment]
Hi @timaseth,

Apologies for the delay in getting back to you!

Good news: Amazon just certified the new version of the VSH skill, which includes the India (EN) locale. The update should get rolled out today.

**Comment by csuermann** [comment]
Hi @timaseth,

I was wondering if you could confirm that the skill has indeed landed in the Indian skill store and is functioning as expected?!

Thank you!

**Comment by timaseth** [comment]
Hallo @csuermann,

A BIG YES!!
I am gald to confirm that the skill was indeed available within a few hours of you stating so!
And..it works flawlessely!

I sincerely appreciete your efforts in making a remarkabkle application as well as your care for making it available to more users - Vielen Dank!

**Comment by csuermann** [comment]
Cool! Thanks for confirming!
