### ISSUE TITLE
VSH - Steuerung Ikea Tradfri

### ISSUE THREAD

**Issue by sunnyecki1** [csuermann/node-red-contrib-virtual-smart-home#61]
Hallo,
ich habe heute Ihren Alexa Skill installiert un das Node Red Paket. Die EInrichtung lief super einfach und auch die Geräteerkennung funktioniert super. 
Probleme habe ich allerdinngs mit meinen Ikea Tradfri Leuchten. Diese kann ich einschalten und dimmen, allerdings nicht ausschalten. Die Leuchten reagieren nicht auf "powerState": off, sondern benötigen wohl zwingend "state": off oder "brightness": 0
So funktioniert es zumindest in meinen flows ohnen Probleme.
Gibt es irgendeinen Weg das einzustellen oder stehe ich hier auf dem Schlauch? Ich habe versucht es mit einer Change Node zu lösen, war aber nicht erfolgreich.
Vielleicht haben Sie ja ein Lösung.
Vielen Dank
Jörg Böttger
Bremen

**Comment by csuermann** [comment]
Hallo Jörg,

Freut mich zu hören, dass die Einrichtung einfach verlief.

Grundsätzlich bist Du mit einem Change Node oder Function Node schon auf dem richtigen Weg. Wenn Du mir einen Export Deiner Flows schickst, guck ich gerne mal, wo das Problem liegt.

Viele Grüße nach Bremen
Cornelius

**Comment by sunnyecki1** [comment]
Hallo Cornelius,

vielen Dank für deine Antwort.
Im Anhang sende ich dir meinen Flow. Ich bin zur Zeit noch ziemlicher
Anfänger in Node Red und stehe ziemlich auf dem Schlauch.
Im Flow siehst du oben einen Dashboard Switch der meine Lampe schaltet. Im
Converter siehst du die Befehle für meine Lampe. Ich schalte die Lampe mit
"brightness".

Genau hier liegt meine Problem mit VSH. Beim ausschalten über Alexa wird
"brightness" nicht auf 0% gesetzt, sondern bleibt bei 1%. Meine Lampe ist
damit noch ziemlich hell. "Powerstate" scheint mein Device nicht zu
akzeptieren. Statt mit "brightness" könnte ich die Lampe noch mit "state":
on  / "state: off schalten.

Ich habe hinter der VSH Node einen debug und sehe was raus kommt, komme
aber mit einer change nicht klar. Ich könnte zwar mit der change einfach
"powerstate" auf "on" oder "off" schalten, könnte dann aber (weil es ja
statisch wäre) nicht mehr die Helligkeit steuern.

Ich hoffe auf einen kleinen Denkanstoss von dir.

Vielen Dank
Jörg

Am Mo., 26. Apr. 2021 um 17:11 Uhr schrieb Cornelius Suermann <
***@***.***>:

**Comment by sunnyecki1** [comment]
Hallo Cornelius,

entschuldige bitte nochmal die Störung.
Im Anhang jetzt ein Flow der halbwegs funktioniert, aber sehr umständlich
zu sein scheint.
Ich kann die Lampe ein/aus schalten musste aber diverse Anweisungen im
payload mit der change node löschen.
Vielleicht fällt dir ja eine einfachere Lösung ein. Das nächste Problem ist
dann die Änderung der Lichtfarbe. Da weiß ich garnicht, wie ich das über
eine change node realisieren soll.

Danke und einen schönen Abend.
Jörg


Am Mo., 26. Apr. 2021 um 17:55 Uhr schrieb Böttger ***@***.***>:

**Comment by csuermann** [comment]
Hi Jörg,

könntest Du den Export Deines Flows bitte direkt hier in GitHub einfügen? Per Email gesendete Anhänge scheint GitHub nicht zu übernehmen.

Danke und viele Grüße
Cornelius
