### ISSUE TITLE
Configure a new vsh-connection

### ISSUE THREAD

**Issue by alexpelli** [csuermann/node-red-contrib-virtual-smart-home#62]
Hi.. I have a problem to configure a new vsh-connection. 
I have just add the node vsh and followed the instruction but when i click the "pen" icon to set the vsh-connection the page is almost empty.. it asks just the name and nothing else.
Could you please help me?
Thanks
Regards

**Comment by csuermann** [comment]
Hi @alexpelli,
The vsh-connection dialog should indeed load more elements than just the name field. It should look something like that:
![image](https://user-images.githubusercontent.com/10939809/116277636-f7835380-a785-11eb-9e6d-ae02bf4ed7ca.png)

The account linking box is added dynamically via JavaScript. To debug, you could check the WebDeveloper Console and Network tab.

**Comment by csuermann** [comment]
Glad to hear. Thanks for reporting back.
