### ISSUE TITLE
passthrough-mode

### ISSUE THREAD

**Issue by ammawel** [csuermann/node-red-contrib-virtual-smart-home#63]
In passthrough-mode, the entire msg should be forwarded, not just the fields of the current local state; the current loacal state should be added to the original msg.
Thanks
Achim

**Comment by ammawel** [comment]
I would like to be able to differentiate input sources after processing by VSH. My approach was to specify an source-ID in the msg. Is there another way?

**Comment by csuermann** [comment]
Would overriding the `topic` suffice (if if was supported)?

I'm a bit hesitant to output a different `payload` because an inbound msg is just supposed to trigger the exact same output as if the directive was coming from Alexa.

**Comment by ammawel** [comment]
yes of course, overwriting the topic (or payload.source?) would be sufficient.
Thanks a lot!
