### ISSUE TITLE
Account Linking Issue

### ISSUE THREAD

**Issue by Nimasch** [csuermann/node-red-contrib-virtual-smart-home#64]
Hi,

After linking my account information in the properties I receive the following error message:

ERROR
installedVshVersion is not defined

The code verification with my amazon account was succesfull. 

Any idea what the isssue could be?

Nimasch

**Comment by csuermann** [comment]
Hi @Nimasch,

I'm sorry to hear you're having issues with VSH. I just deployed a new version which hopefully fixes the problem. Could you kindly confirm? Thanks!

**Comment by Nimasch** [comment]
Hi @csuermann 

This was a really fast response and fix. Thank you very much! It is working perfectly and much more comfortable than with the Amazon Echo Hub. Really great work, was really spending a long time to integrate Alexa smoothly into Loxone. I will definetly promote this project.

Cheers,
Nimasch

**Comment by csuermann** [comment]
That's music in my ears :-) Thank you so much, @Nimasch!
