### ISSUE TITLE
Error message "ERROR Could not connect to backend!" in vsh-connection node

### ISSUE THREAD

**Issue by ArminMertes** [csuermann/node-red-contrib-virtual-smart-home#66]
**Describe the bug**
Creatin a new connections show the message "ERROR Could not connect to backend!" in a red frame. No other information

**To Reproduce**
Existing and well working node red installation
Adding node-red-contrib-virtual-smart-home version 1.24.1
Placing Virtual device node on canvas
Creating a new connection -> shows error message

**Expected behavior**
creating a connection. It was working a few weeks before with a previous version.

**Screenshots**
![image](https://user-images.githubusercontent.com/66441573/117544042-bf9acc80-b01f-11eb-9fb0-b22904507d6d.png)

**Environment (please complete the following information):**
 - virtual-smart-home version: 1.24.1
 - Node-RED version: 1.3.4

**Additional context**
I can succesful start and execute alexa.amazon.de skills on the node red server

**Comment by csuermann** [comment]
Hi @ArminMertes,

I'm sorry to hear you're having issues with VSH.

It looks like a call to the backend is failing. Could you please report what's going on at the network tab of your browser's web devloper tools?

Best Regards
Cornelius

**Comment by csuermann** [comment]
Thanks for your quick response! I'm glad you got it working :-)
