### ISSUE TITLE
virtual garage door opener not sending any payload

### ISSUE THREAD

**Issue by tt2g89** [csuermann/node-red-contrib-virtual-smart-home#67]
Hi @csuermann,
First of all many thanks for developing this multi-purpose solution for the community which isn't only emulating hue lights, but brings the ability to add blinds as blinds and garage doors as garage doors :)

Unfortunately I've seen, that I can only say "Alexa, Garage an" and it opens, "Garage aus" isn't supported and the normal ones "öffnen/open" and "schließen/close" are accepted by Alexa, but do not send anything from the node at the moment (checked with debug-node).
Any idea or is this feature still in progress?

Many thanks in advance and best regards.

**Comment by csuermann** [comment]
Hi,

As far as I know Alexa's Garage Door capability is currently limited to en_US locale for whatever reason. This might be the reason Alexa is behaving so strangely here.

https://forums.developer.amazon.com/questions/220919/modecontroller-interface-example-garagedoor-not-wo-1.html
