### ISSUE TITLE
capturing voice from a specific echo device

### ISSUE THREAD

**Issue by fwollen** [csuermann/node-red-contrib-virtual-smart-home#68]
Hi. I'm using VSH and I found it very useful. I own 7 different echo, one for each room/area. Invoking commands for a specific room could be very powerful, especially for guests who don't know the right names of the devices (eg. I'm in the guest room, want just simply say switch-on the lights). Is there any chance you add this function in a future release of the package?  It should be possibile to trigger from which echo the voice has been captured so that in NR, the lights are turned on/off in that specific room; something like what is possible in cake-backed.
I'm available to support your costs for having it. 
Think of it!
Thank you again for your work

**Comment by fwollen** [comment]
Unfortunately this is not what I'm looking for. Yes, the feature is ready to use in Alexa, but my business case is a bit more complicated: don't need to control only light for each room, but also Air Conditioning or sound level. Thus, re lights, not all the lights (even if are in NR) are registered in Alexa, so the group cannot be managed by Alexa otherwise not all the light will turn on. And so on with Air Conditioning and sound.
In the new feature I'm suggesting, package should ask where the would expect to specify where the trigger has been pronunciated. 
Let's make an example:

- define a VSH devices (ed. AirCond) 
- after deploy, AirCond is a VSH device
- in NR the node the trigger should be
         1. when` Alexa listen AirCond from Echo_living_room," then switch on AC living room
         2. when` Alexa listen AirCond from Echo_living_kitchen," then switch on AC living room
         3. and so on
         4. 
 this would make the interaction with system more "natural". Wherever I am, the commands I tell to Alexa, are related only to that specific echo device, so that room. But automations must be performed by NR, not by Alexa groups/routines
Hope this clarify

**Comment by csuermann** [comment]
Hi @fwollen,

VSH is based on Amazon's smart home API which unfortunately does not expose the Alexa device that received a voice command. Hence the grouping feature @WarNeedle mentioned is the only way to accomplish something close to what you want.

**Comment by MattL0** [comment]
With the Homeseer alexa skill  (which need alexa tell homeseer ..) It is possible to get the echo id . 
But now with the Homeseer native skill which does not need the ‘’tell homeseer’’ part.

So i guess your skill use the same api ad the homeseer skill.
