### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by elchanly** [csuermann/node-red-contrib-virtual-smart-home#7]
While installing:
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ""~"0.1.10": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-02T16_35_43_609Z-debug.log

:(

**Comment by csuermann** [comment]
Sorry to hear you're having trouble installing VSH.

The error message is not very descriptive. Could you please share the contents of /root/.npm/_logs/2020-11-02T16_35_43_609Z-debug.log?

Also, which VSH and Node-RED versions are you running?

Thanks!

**Comment by csuermann** [comment]
Ahh, saw your response too late. Never mind.
