### ISSUE TITLE
[Feature Request] Device Name

### ISSUE THREAD

**Issue by expertsonline** [csuermann/node-red-contrib-virtual-smart-home#70]
First of all - really liking this node! well done.....
I have been trying to have dimable lights in seprate rooms controlled with the same name. I tried setting groups which works for turn on and turn off, but when we go to setting brightness, alexa complains there are multiple devices with the same name.

I believe in the event from alexa, the device name is shared. Other extensions do publish this information to node-red and it is useful for us to trigger the appropriate automation. I wanted to check if you could consider doing something similar?
Here is the JSON I get from the remote2 extension and I am looking to get the deviceName along with the existing messages published by your node:

`{"device": { "deviceName": "xxxxx", "deviceEntityId": null },
"utteranceType": "GENERAL",
"domain": "HomeAutomation",
"intent": "SetValueIntent"}`

Thanks,
Deep

**Comment by csuermann** [comment]
Hi @expertsonline,

Unfortunately Alexa's Smart Home Skill API does not expose the name of the Alexa device a command was spoken to. But I just tested dimming my kitchen light, which is grouped together with the Echo in the kitchen by saying "Alexa, dim light to 50 percent" and it worked.

Can you share more details about your setup, e.g. the light names and groups you've configured?

**Comment by expertsonline** [comment]
Yeah - it only works if you control all lights in the room together, but it does not work if you want to control an individual device in that room.

My setup: Two devices in each room:
left light
right light
add an echo to each room

if you say "Alexa, dim lights to 30 percent" then it will work as expected.
If you say "Alexa, dim left light to 30 percent" then it will say "I found more than 1 device with the name left light. Please give them unique names, then run discovery again. Or, create a group if you want to control them simultaneously."

It is odd that I can see the device name in the remote2 extension, but not in this one. I guess I will need to do something where I combine both extensions and merge the output in someway to enrich the missing information for now.

**Comment by csuermann** [comment]
Ok, I see what you mean. I fixed that by giving my lights unique names.

**Comment by expertsonline** [comment]
To anyone else having this problem I am working around the issue using both the remote2 extension along with VSH.

The remote2 extension gives the device name which I save to a flow variable. This then triggers the processing node.
VSH gives the actual action needed to be performed which I also save in a flow variable. This then triggers a processing node.

The processing node checks that both extensions have updated recently (in the last 5 seconds) and then depending on the device name from remote2 saved flow variable, it triggers the action in the respective room.
