### ISSUE TITLE
Setting Alexa device status when HomeAssistant changes 

### ISSUE THREAD

**Issue by oziee** [csuermann/node-red-contrib-virtual-smart-home#71]
So I have worked out all the mqtt output to change HA when the vsh device output is received

but when I click the light switch manually or via the HA ui the Alexa app does not reflect the change

can this be done?

**Comment by oziee** [comment]
thanks @WarNeedle 

I tried to pass into the Alexa node from mqtt.. but found mqtt got stuck in a loop as in out was the same:)

can I ask how you formatted the payload for Alexa and prevented it from passing to the output towards the mqtt publish again

**Comment by oziee** [comment]
ahh I tried with just one item and it worked with some changes to my output..
I think my problem is that I put all my lights into a simple mqtt call.. so trying to get the mqtt back in and set the name field to allow the right item to work is my next step
<img width="774" alt="Screen Shot 2021-05-20 at 6 28 01 pm" src="https://user-images.githubusercontent.com/1471841/118945876-38434680-b999-11eb-8bb7-5a787123ebaf.png">

**Comment by WarNeedle** [comment]
Hi,
I used a switch node to only pass the message when it's not from the device.
e.g.

![image](https://user-images.githubusercontent.com/70839440/118945614-8599c680-b94d-11eb-8efc-9f4871c2213d.png)

You could also untick this box in the VSH node.
![image](https://user-images.githubusercontent.com/70839440/118945711-9cd8b400-b94d-11eb-907c-9d01bbefc671.png)

My format payload looks like this.
![image](https://user-images.githubusercontent.com/70839440/118946123-0062e180-b94e-11eb-9ad3-a6f3b1f550c7.png)

**Comment by oziee** [comment]
ahh thanks
I think I am doing the same thing (but the switch is built in code to the function
<img width="643" alt="Screen Shot 2021-05-20 at 6 43 32 pm" src="https://user-images.githubusercontent.com/1471841/118948191-645fc700-b99b-11eb-9a79-ec1f7d63671b.png">

pity the node only filters if the 'name' matches as no mqtt returns the name only the topic.. matching 'topic' would be nice and easy

**Comment by oziee** [comment]
perfect.. I have it all working now.. just have to finish adding all the lights in the house etc
<img width="856" alt="Screen Shot 2021-05-20 at 8 07 51 pm" src="https://user-images.githubusercontent.com/1471841/118960940-210b5580-b9a7-11eb-98dc-bbba6e422234.png">

**Comment by WarNeedle** [comment]
Excellent, Hope I was helpful :-)

**Comment by csuermann** [comment]
Hi there, I just wanted to drop that I'm thrilled to see the VSH community helping each other without always requiring input from me! You rock!
