### ISSUE TITLE
[BUG] No events being fired?

### ISSUE THREAD

**Issue by expertsonline** [csuermann/node-red-contrib-virtual-smart-home#73]
**Describe the bug**
Is the back-end down? Suddenly stopped receiving events from this integration. Tried recreating another connection, and still get no events fired. Other Alexa remote2 integration is working, so does not seem to be an issue on Amazon end or my end.

**To Reproduce**
1. Create a device on a new connection
2. Try to trigger a device through Alexa
3. Alexa responds 'device_name' is not responding.

**Expected behavior**
The device to be triggered and an event to be fired from the node.

**Environment (please complete the following information):**
 - virtual-smart-home version: 0.4.67
 - Node-RED version: 1.2.9

**Comment by expertsonline** [comment]
Update: It is back, events are being fired as expected.

**Comment by csuermann** [comment]
Hi @expertsonline,

Apologies for the glitch! I'm in the process of rolling out v2.0.0 which turned out more tricky than expected. You will probably experience VSH to not function again (around next week) which will be fixed by updating the Node-RED VSH contribution.

Best Regards
C.
