### ISSUE TITLE
!!!!! VSH STOPPED WORKING ???? Here is why and how to fix it!

### ISSUE THREAD

**Issue by csuermann** [csuermann/node-red-contrib-virtual-smart-home#74]
Dear VSH users,

I'm in the process of releasing a new version of the VSH backend, which unfortunately will not be backwards compatible with the old VSH Node-RED client.

To get your VSH working again, simply update to v2 of [Node-RED-contrib-virtual-smart-home](https://flows.nodered.org/node/node-red-contrib-virtual-smart-home). After the update your devices should work better than before, e.g. now Alexa will let you know in case your Node-RED is offline.

If the v2 update is not yet available, please check again a bit later.

**Comment by expertsonline** [comment]
> If the v2 update is not yet available, please check again a bit later.

Any thoughts on how long it would take for v2 to be published? Depending on that I can see if I create a separate workaround.
Thanks for your efforts in building and maintaining this!

**Comment by niklasfink** [comment]
Hi @csuermann, what are the changes on the backend side? The backend repository seems unchanged: https://github.com/csuermann/virtual-smart-home/

I guess you're right in the upgrade process now and VSH is not working anymore until v2 is released and the local instance is updated.

**Comment by csuermann** [comment]
Exactly. The upgrade is a bit tricky. I'm in the process of cleaning things up and will push to GitHub as soon as I'm done.

**Comment by fmarzocca** [comment]
How long the update should take to be detected by NodeRed (npm)?

**Comment by expertsonline** [comment]
Just an update: I saw the v2 update available in node-red and have updated it. Devices show online on node-red but events from Alexa are not firing.

**Comment by csuermann** [comment]
I'm investigating what's going on. Apologies for the inconvenience!

**Comment by mdte123** [comment]
Thanks for letting us know about this. I was wondering why my house wasn't working this morning!

**Comment by mdte123** [comment]
All seems to be up and running again for me now.

Just in case it helps someone: In some flows I used the nodes in combination with node-red-contrib-alexa-remote2-v2 device nodes set to report the power state. These node-red-contrib-alexa-remote2-v2 nodes required me to switch the VSH smart home device on and off in the app before they stopped erroring.

**Comment by steff75** [comment]
Yes, it works for me again too. Thank you!
But with a configuration of the **type: scene** Alexa gives an error message as answer "XYZ reagiert gerade nicht (XYZ is not responding right now)". In Node-Red, however, is triggered regardless of the error.

**Comment by mdte123** [comment]
@steff75 : Yes I get that too. I also get a device not responding error in the app if I attempt to switch on (or off) the device twice.

**Comment by csuermann** [comment]
The update to v2 should be completely rolled out by now. Scene support should also be back to normal. Again, apologies for any inconvenience caused. I hope this kind of enforced update will not have to happen anytime soon!

**Comment by drvirtue** [comment]
The communication between Alexa and Node Red appears to be working correctly.  However, virtual devices displayed in the Alexa app do not display their current state.  I have several virtual switches that I can turn ON and OFF through the Alexa app, and although the underlying virtual switch seems to retain the selected value, the Alexa app only briefly displays the selected value before changing back to an un-chosen state.  Again, although the underlying virtual device state appears to be correctly set, the Alexa app is not displaying the current state.

**Comment by csuermann** [comment]
@drvirtue, although VSH is reporting any state change back to Alexa ('proactivelyReported'), the Alexa app seems to require the state to be 'retrievable' in order to display the current setting. For technical reasons I needed to disable support for retrievable. I might bring it back shortly.

**Comment by hazymat** [comment]
I have updated to 2.0.1. However all devices are not responding. Family are very confused as lights and oven don't turn on! (We have a backup option, it's okay....) All my devices show with status "Offline" in Node-RED and Alexa responds "Sorry [devicename] has outdated firmware. Please visit the device manufacturer's app to update the firmware".

Any clues?

**Comment by pbek** [comment]
I can also confirm that after switching the VSH connection to `Debug` and redeploying the nodes the connection was online again and the switches did what they should do (I then turned off `Debug` again). Thank you, @csuermann!

**Comment by Clabs1** [comment]
@csuermann I've updated and got the devices to appear online in the node-red interface. If I issue a command (by voice or in Alexa app) the device does what I've asked (on/off/dim...) but Alexa responds that the device is not responding. Any ideas?

**Comment by csuermann** [comment]
Hi @Clabs1, You could try to switch on the debug mode in the vsh-connection node and observe what is being sent over the wire. Alexa waits for 5 seconds to receive confirmation from your device that the command was executed successfully. So pay attention to the timestamps in the log output.

**Comment by Clabs1** [comment]
@csuermann Thanks for the update. FYI I had an issue where the device was doing what I requested but Alexa was then responding "sorry ... light is not responding". Unlinking and re-linking the skill fixed this.

**Comment by Clabs1** [comment]
> Hi @Clabs1, You could try to switch on the debug mode in the vsh-connection node and observe what is being sent over the wire. Alexa waits for 5 seconds to receive confirmation from your device that the command was executed successfully. So pay attention to the timestamps in the log output.

Just fixed this and was replying as you typed! Unlinking and relinking the skill in the alexa app has solved it. Thank you!

**Comment by electrontube** [comment]
Same here, everything appeared to be working fine, but I always got the response: _"device is not responding"_
Unlinking and relinking the skill in Alexa App solved that problem.

@Clabs1 thanks for the hint!

**@csuermann 
Thanks for the great software and all your effort!**

**Comment by Domi920** [comment]
Hello,
 use your software on my IOBroker with NodeRed integration.
 Unfortunately, since the update to V2.x, I have always had the problem that after 1 day Alexa cannot control the devices.
 The devices are displayed as online in the NodeRed.
 It only works again when I restart NodeRed.
 But only for 1 day.

 node-red-contrib-virtual-smart-home
 2.7.0
 Installed

 What can I do now?

 Greetings Dominik

**Comment by csuermann** [comment]
Hi @Domi920,
Could you please enable the debug option for the vsh-connection and observe the console output to see what gets sent over the wire before and after Alexa stops working for you? Thanks!

**Comment by Domi920** [comment]
Thank you for the fast reaction.
 I activated the debug mode.
 As soon as I have the error again, I'll get in touch here.

**Comment by csuermann** [comment]
Debug messages are written to stdout.

**Comment by Domi920** [comment]
@csuermann Sorry, but unfortunately I don't know my way around at all. On the Internet I could read that I should somehow enter something with a console. But no idea where and how.
Node Red runs on the Raspberry Pi 4 on the IOBroker system as an integrated instance.
I've already set up debug there, but unfortunately I don't get any messages.
I'm sorry for the inconvenience but I don't know how to do it.

Greetings Dominik

**Comment by csuermann** [comment]
@Domi920, I don't know how to access Node-RED logs when using IOBroker either. Is this thread helpful? 

https://discourse.nodered.org/t/where-can-i-read-node-red-logs/7698/6

**Comment by Domi920** [comment]
@csuermann I've already come across this thread, unfortunately without success.
I know the IP address & the port on which Node Red is running.
Can't you somehow access the log via the Node Red interface?
Or is it possible to install a pallet that enables this?
Or do you know how to access the Node Red system via the console of the Raspberry Pi 4?

Is this link any use?
https://github.com/ioBroker/ioBroker.node-red

Thank you for the fast reaction!

**Comment by csuermann** [comment]
If you have access to the raspberry terminal you could try

```strace -p`pidof node-red` -s9999 -e write |& grep "vsh-connection"```

This should print any vsh related debug information as they occur (not retrospectively).

If this doesn't work, seeking advice from the IOBroker community might be more fruitful.

**Comment by Domi920** [comment]
The command via the Raspberry Terminal works.
 However, you need admin rights.
 That's why I wrote `sudo` before:
 `sudo strace -p`pidof node-red` -s9999 -e write | & grep" vsh-connection "`

 Unfortunately, I haven't had the error for 2 days.
 I leave the console open so that I am immediately informed of the next error and can pass this on!

**Comment by csuermann** [comment]
> Unfortunately, I haven't had the error for 2 days.

Haha 🤣

**Comment by Domi920** [comment]
I haven't had any more failures since opening the live log in the console.
The only thing that stands out:

`
write(1, "25 Jun 04:07:52 - [info] [vsh-connection:E-MAIL-ADRESSE] MQTT disconnected\n", 89) = 89
write(1, "25 Jun 04:07:52 - [info] [vsh-connection:E-MAIL-ADRESSE] MQTT disconnected\n", 89) = 89
write(1, "25 Jun 04:07:58 - [info] [vsh-connection:E-MAIL-ADRESSE] MQTT connecting to a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883\n", 142) = 142
write(1, "25 Jun 04:07:58 - [info] [vsh-connection:E-MAIL-ADRESSE] MQTT publish to topic $aws/things/vsht-cce26974-a8ac-46a7-bb59-d0840982ee68/shadow/update: {\"state\":{\"reported\":{\"connected\":true,\"vsh_version\":\"2.7.0\",\"nr_version\":\"1.3.4\"}}}\n", 247) = 247
`

But think that this is caused by the standard reconnection through the router.
Will close the console.
If the error occurs again, I will notify you here again!

Thank you so far for the speedy support!
