### ISSUE TITLE
[FEATURE REQUEST] A way to send announcement or set alexa device properties

### ISSUE THREAD

**Issue by AleksCee** [csuermann/node-red-contrib-virtual-smart-home#75]
Hi,

first of all - GREAT WORK - which way do you prefer for donation paypal or github? I changed today completely to the node because of the third break the service of node-red-contrib-alexa-remote2 and no longer support.

I use your skill and node parallel for some functions but now I must change completely. So now the request - is there a way to use voice output on single devices or announcement and also device settings like "play music" or "set volume to x" at the alexa device itself. 

Thanks and greetings from Hannover, Alex

**Comment by csuermann** [comment]
Hi @AleksCee, thanks for your nice feedback! Unfortunately your request is technically not possible as VSH implements Amazon's official smart home skill API, which does not support that.

**Comment by AleksCee** [comment]
Ok - and the other question? which way do you prefer for donation paypal or github? :-)

**Comment by csuermann** [comment]
Hi @AleksCee, Your support is greatly appreciated regardless of the channel, but I guess I like GitHub a bit more as your sponsorship will be more visible to others.
