### ISSUE TITLE
Temperature Sensor Not Working[BUG]

### ISSUE THREAD

**Issue by pshellguruwannabe** [csuermann/node-red-contrib-virtual-smart-home#77]
**Describe the bug**
When asking "Alexa, what's the temperature of the pizza oven", it returns "i'm not quite sure what went wrong."

I imported the examples as well, and i get the same response from Alexa each time.

**Comment by csuermann** [comment]
Thanks for reporting this!

I was able to reproduce the problem. However, the VSH backend API does not even seem to get invoked by Alexa, hence I cannot really debug this further and assume it is an Alexa problem of some sort.

I'll try to dig some more.

**Comment by csuermann** [comment]
This should be fixed in v2.2.0. You might have to ask Alexa to discover your devices for the fix to take effect.

**Comment by PaulNotNull** [comment]
Confirming that the issue is fixed for me.  I did not have to take any other actions.  Just the install of the new version fixed the issue.  Thank You!!
