### ISSUE TITLE
[BUG] Firmware upgrade required (in Alexa)

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [csuermann/node-red-contrib-virtual-smart-home#79]
![image](https://user-images.githubusercontent.com/2195190/121660681-d46af400-cae6-11eb-9c3e-d7bb1460eebe.png)

The Alexa App is showing "Firmware update required" and there is no response on the Alexa side when sending parameters from Node-Red. I tried it with your Example files as well and getting same result.

Thanks for your help

**Environment (please complete the following information):**
 - virtual-smart-home version: 2.2.0
 - Node-RED version: 1.3.5 (Docker0

**Comment by csuermann** [comment]
For me to debug this, could you please share the value displayed as "Thing ID" in the connection details?

**Comment by dthiessen2** [comment]
Hi, i experienced the same issue this morning.
It affected each device and went away after a full deploy in node red.
This might be the same issue i reported some days ago.
After the deploy the log shows
Node-RED[2651]: 12 Jun 07:31:24 - [warn] [vsh-connection:(my email address)] You are using an outdated version of VSH!
I could not find anything out of the ordinary in the logs before this (or so i believe) 
In case my Thing id would be helpful as well: its vsht-e5e16478-da10-4b9e-90b2-ae422d94340c

**Comment by csuermann** [comment]
Hi @dthiessen2, looks like you're still running VSH v2.0.2. The note in the logs is just hinting at a newer version being available. I'll change the wording in the next release to make it sound less like a problem.

**Comment by dthiessen2** [comment]
i did not realize that a new version was available since the 2.02 version was only a few days old. Expectation bias i guess ;)

**Comment by xX-Nexus-Xx** [comment]
Thanks a lot ... latest version + Full deploy did the trick !!

Klasse Node !!
