### ISSUE TITLE
stop command or percentage for blinds?

### ISSUE THREAD

**Issue by hansj10** [csuermann/node-red-contrib-virtual-smart-home#8]
Hi Cornelius,

Imagine the following use case:
you want to close/open your blinds but want them to stop at a certain position.
One way would be to implement a percentage like "Alexa, open blinds livingroom 50%"
Or just "open blinds livingroom" and then your convenient moment "Alexa, stop blinds livingroom".

Or the blinds are closing automatically as you programmed, but you party outside and want it to stop?

Same applies for a garage or similar IoT device..

Thanks for considering,
Hans-Jörg

**Comment by csuermann** [comment]
Hi Hans-Jörg,

I'm planning to add support for controlling blinds with %-commands. As a workaround you could (mis)use a dimmable light node instead, but then you lose the ability to say "open / close the blinds".

Stopping the blinds at a certain position while they're still in motion would indeed be a nice feature. However, I'm afraid Alexa's smart home skillset does not support that.

Cornelius

**Comment by hansj10** [comment]
Hi Cornelius,

somehow a stop command is used when listening to any streams like radio or music, you would just say stop Alexa.
But you are right, I haven't had a look at the home skillset of AWS..

Anyway great work so far ;)
Hans-Jörg
