### ISSUE TITLE
Problems when using second amazon account at the same time

### ISSUE THREAD

**Issue by vdi-cloud** [csuermann/node-red-contrib-virtual-smart-home#81]
I have installed the newest package and it is working fine so far when all the devices are assigned to same amazon account. Once I assign one of the devices to another amazon account (skill was installed also there), the connection name gets reddish in the node setup dialog and this connection for this device will not work where the others - assigned to the other account - would.
What could be the reason for this?

**Comment by csuermann** [comment]
Hi @vdi-cloud,
Could you please post a screenshot showing what you mean?

**Comment by vdi-cloud** [comment]
![Bild 19 06 21 um 18 55](https://user-images.githubusercontent.com/62176233/122649878-5cc54680-d130-11eb-939e-005d5bd984ff.jpg)
![Bild 19 06 21 um 18 54](https://user-images.githubusercontent.com/62176233/122649911-6f3f8000-d130-11eb-8606-fbadd871b08e.jpg)
![Bild 19 06 21 um 18 53](https://user-images.githubusercontent.com/62176233/122649917-7b2b4200-d130-11eb-9b8f-bf2ba55b7035.jpg)

**Comment by csuermann** [comment]
Hi @vdi-cloud,

Thanks for sharing the screenshots! 

I tried to reproduce this but failed. Unfortunately it is not yet apparent what went wrong in your case. Could you please add the following property to the end of your Node-RED's settings.js file (right before the last `}`, restart Node-RED and check the connection edit dialog again?

```javascript
  , vshConnectionShowSettings: true
```

Also, please switch on Debug mode for both vsh-connections and observe the stdout output.

**Comment by vdi-cloud** [comment]
I tried it ou and edited settings.js and restarted the whole thing but I get the same behaviour
![vshConnectionShowSettings true](https://user-images.githubusercontent.com/62176233/122677418-6effbd00-d1e2-11eb-87d8-6b9592947a0d.png)

**Comment by csuermann** [comment]
Once `vshConnectionShowSettings` is set to `true` in your settings.js, you should see more fields in the vsh-connection edit dialog. Can you confirm? Is anything displayed reddish there?

**Comment by vdi-cloud** [comment]
hmm, for me it looks the same as before (refer to above). there is no additional dialog field appearing. 
btw node red is V1.3.4 and node-red-contrib-virtual-smart-home is 2.7.1.

**Comment by csuermann** [comment]
Could you please double check that you edited the right settings.js file? When Node-RED starts up, it should print the path to the settings.js file it uses as one of the first lines.

**Comment by vdi-cloud** [comment]
so now i have edited /opt/iobroker/iobroker-data/node-red/settings.js but it gets overriden once I restarted red-node may be it is replaced by default as I made a mistake while editing???
... 
 },

    // Customising the editor
    editorTheme: {
        projects: {
            // To enable the Projects feature, set this value to true
            enabled: false
        }
    },
    externalModules: {
        palette: {
            allowInstall: true
        }
    }**,
vshConnectionShowSettings: true**
};

**Comment by csuermann** [comment]
I stumbled upon this link: https://forum.iobroker.net/topic/17294/node-red-persistence-funktion-einschalten/2

**Comment by vdi-cloud** [comment]
I found this link too but it does not work for me i.e. the changes are getting overwritten, there is no context folder created.

**Comment by csuermann** [comment]
Sorry, I cannot help you with sorting out that IOBroker issue. Did the Debug log reveal anything?

**Comment by vdi-cloud** [comment]
no, not really. I think the main issue is to understand why the settings.js is overridden. I am still investigating.

**Comment by csuermann** [comment]
Hi @vdi-cloud,

In case you're still struggling with making the settings.js file work, there is an alternative way to display all the connection settings:

1. open the edit dialog of the vsh-connection node
2. open your browser's developer console (e.g. F12 in Chrome)
3. issue `$('.hidden').show()` on the "Console" tab

This should reveal all the connection settings and hopefully help identify why your connection property is not passing validation.

**Comment by vdi-cloud** [comment]
sorry for my late reply - I have update my i-broker system with 
NODE.JS: V14.17.4
NPM: 7.20.5

Now it is working fine. Issue can be closed.
