### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dgthomson** [csuermann/node-red-contrib-virtual-smart-home#82]
**Describe the bug**
The Alexa speech feedback from a thermostat virtual device is faulty.

The output has changed a few times between versions anyway, but now she says "it's off" inappropriately.

**To Reproduce and Expected Behaviour**

**"Alexa, change _\<thermostat\>_ to 75."**

Expected response: 💬 _Autoset to 75_ or 💬 _Changed to 75._

Actual response: 💬 _It's off._

**Screenshots**
n/a

**Environment (please complete the following information):**
 - virtual-smart-home version: 2.7.1
 - Node-RED version: 1.3.4

[I have been using the thermostat device to link to a TV channel-controlling node. It has been working well as Alexa allows a temperature in Kelvin, so I can say "Alexa, change the telly to 107" and the TV will change to BBC News...] 🙂

**Comment by csuermann** [comment]
Hi @dgthomson,

Thanks for reporting this inconsistency. As you can see it should be fixed in v2.8.0. Can you confirm?

In a recent update I introduced virtual 'entertainment devices', which might be a better solution for your TV than using a Thermostat as a workaround as it has native support for channel switching etc.

**Comment by dgthomson** [comment]
Thank you for the quick response-- confirm she's saying 💬 _Autoset to 107_ now on NR 1.3.5 with VSH 2.8.0.

**Comment by dgthomson** [comment]
This has reverted to the old behaviour, unfortunately.

**Comment by csuermann** [comment]
Hi @dgthomson,

Sorry for the inconvenience! This was probably an unnoticed side effect of #85.

While I could add some logic to set the mode to AUTO if a new target temperature gets set and the current mode is OFF, this wouldn't be accurate for users to whom the AUTO mode doesn't make sense.

As the virtual thermostat supports multiple modes (e.g. HEAT, COOL, and AUTO), it's not possible to guess the right mode when a target temperature gets set. I'd therefore suggest that you treat the dials independently, e.g. first set the mode and then the temperature. Once you set the mode to AUTO you should get exactly the response you expected when you then set a new temperature.

I hope that makes sense.

Best Regards
Cornelius
