### ISSUE TITLE
[BUG] Injecting "ECO" mode for thermostat

### ISSUE THREAD

**Issue by santoal** [csuermann/node-red-contrib-virtual-smart-home#83]
njecting thermosstatMode to "ECO" seems to have no effect in Alexa.

set msg.payload.thermostatMode="ECO"
Expected behavior
Thermostat mode in Alexa changes to ECO

Environment (please complete the following information):

virtual-smart-home version: 2.7.1
Node-RED version: 1.3.4

**Comment by santoal** [comment]
Hi - this update doesn't seem to come through on the palette in Node -Red?

**Comment by csuermann** [comment]
Apologies! I forgot to trigger the refresh at the Node-RED library. Should be there now.
