### ISSUE TITLE
[BUG] Devices won't react since Update to Version 2+

### ISSUE THREAD

**Issue by nicedevil007** [csuermann/node-red-contrib-virtual-smart-home#84]
**Describe the bug**
I updated to Version 2 in the past and kept the plugin up2date since.
From time to time I get alexa saying "Gerät XYZ antwortet nicht, überprüfe die Internetverbindung".
I guess in english it will "Device XYZ doesn't react, check your internet connection".
After a restart of the node-red adapter inside my ioBroker everything works again as expected.

**To Reproduce**
I guess all is said in the description?

**Expected behavior**
It won't fail with the connection like it was with a version prior to version 2.

**Environment (please complete the following information):**
 - virtual-smart-home version: e.g. 2.8
 - Node-RED version: 1.3.5

**Comment by csuermann** [comment]
Hi @nicedevil007,

This seems to be related to https://github.com/csuermann/node-red-contrib-virtual-smart-home/issues/74#issuecomment-861255586

When the MQTT connection to the VSH backend drops for whatever reason (e.g. internet provider disconnect), your virtual devices get marked as 'offline' in the backend database. Alexa responds with '... device does not respond' when the device is marked as offline. Usually the status should get updated again to 'online' once the device reconnects. I'm not yet sure why this doesn't seem to happen in some cases.

As advised in the other [thread](https://github.com/csuermann/node-red-contrib-virtual-smart-home/issues/74#issuecomment-861255586), you could help by enabling Debug mode and providing the logs.

**Comment by nicedevil007** [comment]
Ok will wait until the next error appears (in last weeks it appears more than once a week) and will report back

**Comment by Domi920** [comment]
Habe den Fehler nun wieder:
![VSH 2 x Fehler](https://user-images.githubusercontent.com/68474558/124065269-b4b85300-da36-11eb-8ddc-3bda3a3fe660.jpg)

Da ich nicht wusste ob manche Daten sensibel sind, habe ich diese mal "entfernt".

In NodeRed sind alle Geräte auf Status online.
Im Log Protokoll kommen keine neuen Einträge dazu, wenn man Alexa einen Befehl gibt.

Wenn du noch mehr Inhalt brauchst gib mir bitte bescheid!


Danke für die Hilfe! :-))

**Comment by csuermann** [comment]
Thank you! What's weird is the double disconnect at 03:52:43 without a connect in between. Do you have multiple vsh-connections or just one?

Also, could you please update to the latest VSH version? This might not fix the issue but it's still a good idea to always use the latest version.

**Comment by Domi920** [comment]
No, I only have one connection:
![20210702_004429](https://user-images.githubusercontent.com/68474558/124197506-f85e9b80-dace-11eb-8d96-b34806bdc18f.jpg)

On another day there were also two separations again.
However, the times in the log do not match the sequence.
I left a post above and below visible:
![20210702_003809](https://user-images.githubusercontent.com/68474558/124197642-4ecbda00-dacf-11eb-831a-5ea8da6d0aed.jpg)

I install the new version after reconnecting the internet at home.
It may then work again and the log would still help.

Is there already an approach to the solution?

**Comment by csuermann** [comment]
It might be some sort of race condition between the backend realizing your connection dropped, which leads to marking your device as offline in the database, and your Node-RED reestablishing the connection, which leads to the device being marked as online again in the database.

I've just released v2.8.4 which introduces a 7 second delay for marking the device as online. If the issue is really race-condition related, this fix should probably fix it. Let me know!

**Comment by nicedevil007** [comment]
> No, I only have one connection:
> ![20210702_004429](https://user-images.githubusercontent.com/68474558/124197506-f85e9b80-dace-11eb-8d96-b34806bdc18f.jpg)
> 
> On another day there were also two separations again:
> ![20210702_003809](https://user-images.githubusercontent.com/68474558/124197642-4ecbda00-dacf-11eb-831a-5ea8da6d0aed.jpg)
> 
> I install the new version after reconnecting the internet at home.
> It may then work again and the log would still help.
> 
> Is there already an approach to the solution?

Where did you find the logfile for your debug? I tryed to find it inside the iobroker and inside the docker logs where I'm running ioBroker (and inside node-red) but couldn't find it right now.

Will install your newest release and will report back if it happen again. (right now it did without newest version)

**Comment by csuermann** [comment]
Hi @nicedevil007,

First you need to enable `Debug` mode in the vsh-connection node. This will send a more verbose log output to stdout.

If you're running ioBroker, the following command should get you the logs:

```bash
strace -p`pidof node-red` -s9999 -e write |& grep "vsh-connection"
```

Hope that helps.

**Comment by csuermann** [comment]
Hi @nicedevil007,

Has the issue occurred again with the latest version?

**Comment by nicedevil007** [comment]
Nope, I was still waiting, wanted to report on monday that everything seems fine now :) If you ask me wen can close this issue for now. I can open a new one if it occurs again.

**Comment by csuermann** [comment]
Excellent! Glad to hear that. Thanks for the quick feedback!

**Comment by nicedevil007** [comment]
sry missed to say THANK YOU again!

**Comment by Domi920** [comment]
@csuermann I don't have any more problems either!
 Thank you for your help!
