### ISSUE TITLE
[FEATURE REQUEST] Consider adding doorbell type

### ISSUE THREAD

**Issue by Paul-Reed** [csuermann/node-red-contrib-virtual-smart-home#87]
**Is your feature request related to a problem? Please describe.**
The latest range of Ring Doorbells no longer work with;
1. IFTTT
2. node-red-contrib-ringdoorbell no longer works with the new api, and is unmaintained
3. there is no official Ring api to use.

This means that opportunities to use 'ring' and 'motion' alerts from the doorbell in node-RED are now very restricted.

**Describe the solution you'd like**
Having spent an hour on the phone to Ring tech support... it appears that the only interaction available for the new range of Ring doorbells is using the 'ring' trait in Alexa (Ring is now owned by Amazon!!), and a virtual trait, both in a routine, to pass the alerts back to node-RED.
Currently, `node-red-contrib-virtual-smart-home` does not have a doorbell type, that is able to handle 'ring' alerts & 'motion' alerts (although I am using a workaround as follows below)

**Describe alternatives you've considered**
I'm currently using the 'switch' type in node-red-contrib-virtual-smart-home, and have it set as;
`ring event = "ON"`
`motion event = "OFF"`
So, every time the doorbell is pressed, I get "ON" from your node, and every time motion is detected I get "OFF". In the flow I then have a switch node which routes the flow accordingly.

**Additional context**
As you can see, there is a workaround (which I am quite happy to continue using), but you may wish to consider adding a doorbell type, so that is would be more intuitive for other users.

<img src="https://user-images.githubusercontent.com/973580/124396228-24149800-dd00-11eb-94ad-5394cc71a8df.png" width="250">

**Comment by csuermann** [comment]
Hi @Paul-Reed,

Thanks for your suggestion! I'm not quite sure I understood everything correctly yet, so let me try to recap:

1. You want to do something in Node-RED when your Ring™️ doorbell is pressed.
    * For that you have configured two routines in the Alexa app that get triggered when the doorbell is pressed / motion is detected and set your virtual switch to ON / OFF respectively.
    * Is there a specific reason for encoding _both_ signals into just _one_ virtual switch? Have you considered using two virtual `scene` devices instead?
    * I think the `scene` device type is probably a good fit as it can be used very versatilely. In the end all you want is a msg object coming out of your VSH node when the scene is activated, right?
1. Alexa's API has support for a [doorbell event source interface](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-doorbelleventsource.html), but that seems to fit the reverse case, e.g. something happens inside Node-RED and you want that to trigger something in Alexa (e.g. a notification, a routine etc.).
    * I am considering to add that as an additional virtual device type to VSH.

Looking forward to hearing your thoughts.

Best
Cornelius

**Comment by Paul-Reed** [comment]
Thanks @csuermann 

1. I am not familiar with Alexa, and did not know what the `scene` type did, but yes, `scene` is probably a better choice, and using two virtual `scene` devices make the flow clearer.
![virtual](https://user-images.githubusercontent.com/973580/124478115-bf5b4b00-dd9c-11eb-8602-8326e843d5f8.JPG)

2. I had seen the Alexa doorbell event, which prompted me raising the issue, but was not aware that it worked opposite to my user case.

I must write this up in the forum because many users will hit a brick wall when they buy a new ring device and realise that Amazon has blocked the IFTTT api, and they cannot then connect their doorbell to node-RED.

Thanks for your reply

Paul

**Comment by csuermann** [comment]
Hi Paul,

Glad to hear the `scene` does the trick for you!

> I must write this up in the forum because many users will hit a brick wall when they buy a new ring device and realise that Amazon has blocked the IFTTT api, and they cannot then connect their doorbell to node-RED.

Great idea! Feel free to add the link to your post here, too.

**Comment by Paul-Reed** [comment]
Here's the link -
https://discourse.nodered.org/t/tutorial-how-to-obtain-ring-doorbell-alerts-for-node-red-flows/48058
If you see something that I've missed, please let me know.

Paul

**Comment by csuermann** [comment]
Closing this issue as I believe it got resolved.

Also, VSH v2.11.0 introduces support for `virtual doorbell event source` devices which can for example be used to trigger Alexa routines from within Node-RED.
