### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rmcbc** [csuermann/node-red-contrib-virtual-smart-home#90]
**Describe the bug**
I'm getting this error on Node Red after updating to 2.12.0, debug window:

{"msg":"Error in HttpActions:reportState()","org_msg":"Error: EISDIR: illegal operation on a directory, read","data":{"postData":{"requestId":"47vdaPoUZI0pWsYC7dBJXb","agentUserId":"0","payload":{"devices":{"states":{"d1dc1f14.400b4":{"online":true,"on":true}}}}}}}

**To Reproduce**
1. It simply appears

**Environment (please complete the following information):**
 - virtual-smart-home version: 2.12.0
 - Node-RED version: Raspberry default version

**Comment by csuermann** [comment]
Hi @rmcbc,

1. When exactly does this error message appear? Upon starting Node-RED, upon adding a virtual device, upon injecting a message or upon asking Alexa to carry out a specific command?
2. Which node is the error message originating from?
3. Could you please share a screenshot?

Thank you!

**Comment by rmcbc** [comment]
@csuermann this error appears without issuing any voice command. Periodically you see a new entry in the debug log.

**Comment by csuermann** [comment]
I cannot reproduce. I actually doubt that this error originates from VSH.

> 2. Which node is the error message originating from?
> 3. Could you please share a screenshot?

Could you kindly provide answers to these questions, too?

**Comment by rmcbc** [comment]
You are right, sorry this error comes from "Smart Home Devices".
