### ISSUE TITLE
After NR upgrade to 2.0.3 provisioning failed! VSH Alexa skill enabled?

### ISSUE THREAD

**Issue by hansj10** [csuermann/node-red-contrib-virtual-smart-home#91]
Hi all,

after NR upgrade to 2.0.3 I get this error. Did work well before. 
First start after upgrade of NR the config node was disconnected complaining about failed provisioning.
debug output is:

26 Jul 16:21:48 - [info] [vsh-connection:3ca694a5.c58a8c] Attempting MQTT connection: a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883 (clientId: vsht-8a5fc497-76e7-46e9-b522-0c5486d8985e)
26 Jul 16:21:48 - [info] [vsh-connection:3ca694a5.c58a8c] MQTT subscribe to topics: ["$aws/things/vsht-8a5fc497-76e7-46e9-b522-0c5486d8985e/shadow/get/accepted","vsh/vsht-8a5fc497-76e7-46e9-b522-0c5486d8985e/+/directive","vsh/service","vsh/version/2.12.0/+","vsh/vsht-8a5fc497-76e7-46e9-b522-0c5486d8985e/service"]
26 Jul 16:21:48 - [info] [vsh-connection:3ca694a5.c58a8c] MQTT connecting to a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883
26 Jul 16:21:50 - [info] [vsh-connection:3ca694a5.c58a8c] MQTT publish to topic vsh/vsht-8a5fc497-76e7-46e9-b522-0c5486d8985e/requestConfig: {"vshVersion":"2.12.0"}
26 Jul 16:21:50 - [info] [vsh-connection:3ca694a5.c58a8c] MQTT message received on topic vsh/vsht-8a5fc497-76e7-46e9-b522-0c5486d8985e/service: {"operation":"kill","reason":"User not found! VSH Alexa skill enabled?"}
CONNECTION KILLED! Reason: User not found! VSH Alexa skill enabled?
26 Jul 16:21:50 - [info] [vsh-connection:3ca694a5.c58a8c] MQTT disconnecting
26 Jul 16:21:50 - [info] [vsh-connection:3ca694a5.c58a8c] MQTT publish to topic $aws/things/vsht-8a5fc497-76e7-46e9-b522-0c5486d8985e/shadow/update: {"state":{"reported":{"connected":false}}}
26 Jul 16:21:50 - [info] [vsh-connection:3ca694a5.c58a8c] MQTT disconnected
26 Jul 16:28:07 - [info] Stopping flows

I did try to re-register but the config node error remains the same.

Any ideas?

Thanks for your help,
Hans-Jörg

**Comment by csuermann** [comment]
Hi @hansj10,

Please make sure to re-enable the skill in the Alexa app and follow the account linking process with the very same email address as shown in the vsh-connection node in the "Account" field.

Hope that helps!

Best Regards
Cornelius

**Comment by hansj10** [comment]
Hi Cornelius,

sorry I thought that an enabled skill does not need re-enabling.. 
After deactivate and activate within the Alexa app, registering worked.

Thanks for your help!
Hans-Jörg

**Comment by csuermann** [comment]
Glad to hear it's working now. Thanks for reporting back!
