### ISSUE TITLE
After reboot flow not working until I redeploy 

### ISSUE THREAD

**Issue by jkoenig72** [csuermann/node-red-contrib-virtual-smart-home#93]
**Describe the bug*
Every time when I reboot, my node-red-contrib-virtual-smart-home is somehow not active. It shows not the green online text below each virtual device.

when I simply move one element within the flow and redeploy it works.

**To Reproduce**
1. Reboot pi
2. Check automation -> not working
3. Check node red, it shows the behavior described above
4. Do redeploy-> work like a charm

**Expected behavior**
Works after reboot without manual redeploy flow

**Screenshots**

**Environment (please complete the following information):**
 - Latest
 - Latest

**Additional context**

**Comment by csuermann** [comment]
Hi @jkoenig72,

Thanks for reporting this issue. I am actually a bit clueless here. Is there any hint in the Node-RED logs maybe?

**Comment by csuermann** [comment]
Hi @jkoenig72, did you find anything suspicious in the logs?

**Comment by jkoenig72** [comment]
Hi,

Thanks for coming back. So far I have not rebooted, will do next time.
Tomorrow.

**Comment by jkoenig72** [comment]
The effect is reproducible: after every reboot in my env., node red starts, the flow (there is only one) with the alexa automation starts, but the automation does not work. Under each virtual device node, there is no Green Online text. When I move a node so I can redeploy all nodes have that online/green text and all is working.

How to switch on the debug you want?

**Comment by csuermann** [comment]
Hi @jkoenig72,

You can enable debug mode in the edit dialog of the vsh-connection node:

![image](https://user-images.githubusercontent.com/10939809/129467246-e704be18-cefc-4bab-a1e3-f69cc4315c93.png)

This will enable verbose logging to `stdout`.

**Comment by Domi920** [comment]
Habe so ein Problem auch schon bemerkt.
Evtl. handelt es sich um das gleiche Problem.

Bei mir läuft NodeRed als Instanz auf dem IOBroker System und das wiederum auf einen Raspberry Pi 4.
Der Raspberry & der Router hängen an der gleichen Steckdosenleiste.
Sobald sich NodeRed gestartet hat sind die Geräte nicht erreichbar, weil der Router noch nicht mit dem Herstellen der Internetverbindung fertig war.
Leider hilft auch ein Warten nichts. 
In meinen Fall funktioniert alles wieder, sobald ich NodeRed neustarte (sobald die Internetverbindung verfügbar ist)

Kann man eine Art "Wiederverbindung" in VSH bzw. in NodeRed einbinden?


Gruß Dominik

**Comment by csuermann** [comment]
I'm still struggling to reproduce this. Could someone please share a screenshot of a VSH node whilst in this strange state? Thanks!

**Comment by jkoenig72** [comment]
I will do - its really not fair use your nice software and not provide a
little support. I still have this case but it's stable once I did it after
the restart. And I do not need to restart that often.  So you want a
restart and then a screenshot of the console when it's not working...

**Comment by jkoenig72** [comment]
![Untitled](https://user-images.githubusercontent.com/9740586/151659035-0d9234ba-b75d-46ea-9f8a-05a59433b015.png)

**Comment by jkoenig72** [comment]
When I then move one element, and redeploy they all say 1st initializing and then green icon: online and works like charm

**Comment by taillepierret** [comment]
Hi everyone, is there a solution for this issue ? Because I have the same problem :'(

**Comment by kosuodhmwa** [comment]
Maybe it's related with my issue on: https://github.com/csuermann/node-red-contrib-virtual-smart-home/issues/136#issuecomment-1114755181 ?

Thank you for your feedbacks... :-) 


Best regards from Switzerland,
Jan

**Comment by jayjupdhig** [comment]
**_'When I then move one element, and redeploy they all say 1st initializing and then green icon: online and works like charm'_**

We use the same method... ;-)

**Comment by jayjupdhig** [comment]
OK - so now i've found that debug mode check box and activated it.

So now, there can i see the debug logs? Will they be written to NodeRED "Debug notifications" section?

-> 

![image](https://user-images.githubusercontent.com/42765391/166233164-63285cc2-8099-49b3-a4f0-14d44219e3a5.png)


**And / or do i need to look somewhere else, e.g. on the file system?**

**Comment by jayjupdhig** [comment]
It's empty... EVEN after a restart - "service nodred restart"... i think at least after a service restart i should see some actions in the "Debug Notifications" on NodeRED...? (E.g. the MQTT connections [in background] from the VSH node ...)

Nothing, as you see here: 

![image](https://user-images.githubusercontent.com/42765391/166235994-569a29e7-32d7-4fc0-984a-0cc473c11470.png)

**Comment by jayjupdhig** [comment]
TITLE: "Where I can get the debug logs of node-red?"

QUESTION: "Is there any way to view/import/capture the logs via the Node Red web UI ?"

ANSWER: "No there isn't."

Source: https://discourse.nodered.org/t/where-i-can-get-the-debug-logs-of-node-red/15712/8

**But** i'm not really sure that this is 100 correctly...!?

**Comment by smcgann99** [comment]
Stop Node-RED in terminal
node-red-stop
then
node-red-start 
you will see the logs as it starts up

**Comment by jayjupdhig** [comment]
-> https://debianforum.de/forum/viewtopic.php?t=184108

**Comment by jayjupdhig** [comment]
OK problem solved, now it logs. Will send the logs to you ASAP.

**Comment by jayjupdhig** [comment]
Here is the log...

`3 May 09:06:04 - [info] 

Willkommen bei Node-RED!
===================

3 May 09:06:04 - [info] Node-RED Version: v1.3.5
3 May 09:06:04 - [info] Node.js  Version: v16.14.0
3 May 09:06:04 - [info] Linux 5.10.63-v7l+ arm LE
3 May 09:06:05 - [info] Paletten-Nodes werden geladen
3 May 09:06:07 - [info] Einstellungsdatei: /root/.node-red/settings.js
3 May 09:06:07 - [info] Kontextspeicher: default [module=memory]
3 May 09:06:07 - [info] Benutzerverzeichnis: /root/.node-red
3 May 09:06:07 - [warn] Projekte deaktiviert: editorTheme.projects.enabled=false
3 May 09:06:07 - [info] Flow-Datei: /root/.node-red/flows_xaxada-dca632d690e4.json
3 May 09:06:07 - [info] Server wird jetzt auf http://127.0.0.1:1880/ ausgeführt
3 May 09:06:07 - [warn] 
---------------------------------------------------------------------
Die Datei mit den Flow-Berechtigungen wird mit einem vom System
generierten Schlüssel verschlüsselt.
Wenn der vom System generierte Schlüssel aus irgendeinem Grund
verloren geht, kann die Datei mit den Berechtigungen nicht
wiederhergestellt werden. Sie muss dann gelöscht und die
Berechtigungen müssen erneut eingestellt werden.
Es sollte ein eigener Schlüssel mit Hilfe der Option
'credentialSecret' in der Einstellungsdatei vorgegeben werden.
Node-RED wird dann die Datei mit den Flow-Berechtigungen
bei der nächsten Übernahme (deploy) einer Änderung erneut
verschlüsseln.
---------------------------------------------------------------------
3 May 09:06:07 - [info] Flows werden gestartet
3 May 09:06:08 - [info] Flows sind gestartet
3 May 09:06:08 - [info] [mqtt-broker:Intro-master--mqtt] Verbindung zum Broker mqtt://192.168.178.4:1883 aufgebaut
3 May 09:06:08 - [info] [mqtt-broker:xaxada.uk.to] Verbindung zum Broker mqtt://81.169.200.216:1883 aufgebaut
3 May 09:06:08 - [info] [vsh-connection:intro.alexa@gmail.com] Attempting MQTT connection: a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883 (clientId: vsht-74daded9-f152-4ba3-8823-20053a810669)
3 May 09:06:08 - [info] [vsh-connection:intro.alexa@gmail.com] MQTT subscribe to topics: ["$aws/things/vsht-74daded9-f152-4ba3-8823-20053a810669/shadow/get/accepted","vsh/vsht-74daded9-f152-4ba3-8823-20053a810669/+/directive","vsh/service","vsh/version/2.13.1/+","vsh/vsht-74daded9-f152-4ba3-8823-20053a810669/service"]
3 May 09:06:08 - [info] [vsh-connection:intro.alexa@gmail.com] MQTT connecting to a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883
3 May 09:06:09 - [info] [vsh-connection:intro.alexa@gmail.com] MQTT publish to topic vsh/vsht-74daded9-f152-4ba3-8823-20053a810669/requestConfig: {"vshVersion":"2.13.1"}
3 May 09:06:10 - [info] [vsh-connection:intro.alexa@gmail.com] MQTT message received on topic vsh/vsht-74daded9-f152-4ba3-8823-20053a810669/service: {"operation":"overrideConfig","userIdToken":"amzn1.account.AG7H7XD24FEI5XPNRS64F6MFOPVQ#69daed52a73c9cbb79fab59fcca120b5b467a018","allowedDeviceCount":100,"msgRateLimiter":{"profiles":{"DEFAULT":{"maxConcurrent":1,"minTime":1000,"highWater":0,"strategy":"BLOCK","penalty":30000,"reservoir":60,"reservoirIncreaseInterval":60000,"reservoirIncreaseAmount":1,"reservoirIncreaseMaximum":60},"PHYSICAL_INTERACTION_DEFAULT":{"maxConcurrent":1,"minTime":2500,"highWater":1,"strategy":"LEAK","reservoir":30,"reservoirIncreaseInterval":900000,"reservoirIncreaseAmount":1,"reservoirIncreaseMaximum":15},"VOICE_INTERACTION_DEFAULT":{"maxConcurrent":1,"minTime":0,"highWater":0,"strategy":"OVERFLOW","reservoir":20,"reservoirIncreaseInterval":300000,"reservoirIncreaseAmount":2,"reservoirIncreaseMaximum":10},"STATE_REPORT_DEFAULT":{"maxConcurrent":1,"minTime":0,"highWater":0,"strategy":"BLOCK","penalty":60000,"reservoir":60,"reservoirIncreaseInterval":300000,"reservoirIncreaseAmount":15,"reservoirIncreaseMaximum":60}},"profileMapping":{"PHYSICAL_INTERACTION_DEFAULT":"PHYSICAL_INTERACTION_DEFAULT","VOICE_INTERACTION_DEFAULT":"VOICE_INTERACTION_DEFAULT","STATE_REPORT_DEFAULT":"STATE_REPORT_DEFAULT"}}}
3 May 09:06:10 - [info] [vsh-connection:intro.alexa@gmail.com] MQTT publish to topic $aws/things/vsht-74daded9-f152-4ba3-8823-20053a810669/shadow/get: {}
3 May 09:06:10 - [info] [vsh-connection:intro.alexa@gmail.com] MsgRateLimiter.overrideConfig: {
  "profiles": {
    "DEFAULT": {
      "maxConcurrent": 1,
      "minTime": 1000,
      "highWater": 0,
      "strategy": "BLOCK",
      "penalty": 30000,
      "reservoir": 60,
      "reservoirIncreaseInterval": 60000,
      "reservoirIncreaseAmount": 1,
      "reservoirIncreaseMaximum": 60
    },
    "PHYSICAL_INTERACTION_DEFAULT": {
      "maxConcurrent": 1,
      "minTime": 2500,
      "highWater": 1,
      "strategy": "LEAK",
      "reservoir": 30,
      "reservoirIncreaseInterval": 900000,
      "reservoirIncreaseAmount": 1,
      "reservoirIncreaseMaximum": 15
    },
    "VOICE_INTERACTION_DEFAULT": {
      "maxConcurrent": 1,
      "minTime": 0,
      "highWater": 0,
      "strategy": "OVERFLOW",
      "reservoir": 20,
      "reservoirIncreaseInterval": 300000,
      "reservoirIncreaseAmount": 2,
      "reservoirIncreaseMaximum": 10
    },
    "STATE_REPORT_DEFAULT": {
      "maxConcurrent": 1,
      "minTime": 0,
      "highWater": 0,
      "strategy": "BLOCK",
      "penalty": 60000,
      "reservoir": 60,
      "reservoirIncreaseInterval": 300000,
      "reservoirIncreaseAmount": 15,
      "reservoirIncreaseMaximum": 60
    }
  },
  "profileMapping": {
    "PHYSICAL_INTERACTION_DEFAULT": "PHYSICAL_INTERACTION_DEFAULT",
    "VOICE_INTERACTION_DEFAULT": "VOICE_INTERACTION_DEFAULT",
    "STATE_REPORT_DEFAULT": "STATE_REPORT_DEFAULT"
  }
}
3 May 09:06:10 - [info] [vsh-connection:intro.alexa@gmail.com] MQTT message received on topic $aws/things/vsht-74daded9-f152-4ba3-8823-20053a810669/shadow/get/accepted: {"state":{"reported":{"connected":false,"vsh_version":"2.13.1","nr_version":"1.3.5","devices":{"vshd-4732cb7f801488":{"friendlyName":"2","template":"SWITCH"},"vshd-e31034baf92d37":{"friendlyName":"eins","template":"SWITCH"},"vshd-a6c9b5d7f97e0e":{"friendlyName":"5","template":"SWITCH"},"vshd-6f09ffdca415a7":{"friendlyName":"6","template":"SWITCH"},"vshd-dc59ff65bb604f":{"friendlyName":"3","template":"SWITCH"},"vshd-574c2ac6ccc8bc":{"friendlyName":"4","template":"SWITCH"},"vshd-ecee403697baa5":{"friendlyName":"7","template":"SWITCH"},"vshd-79c31f3cec1f7e":{"friendlyName":"8","template":"SWITCH"},"vshd-6c5df90d7c1448":{"friendlyName":"spar","template":"SWITCH"},"vshd-2db69d78a6ed70":{"friendlyName":"treppe","template":"SWITCH"},"vshd-36cd0febb4129b":{"friendlyName":"eingang","template":"SWITCH"},"vshd-7d74e4d49bf405":{"friendlyName":"sitzung","template":"SWITCH"},"vshd-8adbdeb719c7a1":{"friendlyName":"sued","template":"SWITCH"},"vshd-8e3d794b55f700":{"friendlyName":"nord","template":"SWITCH"},"vshd-89a9e7ecafa0fe":{"friendlyName":"storen","template":"SWITCH"},"vshd-e6f283582af422":{"friendlyName":"sesam","template":"SWITCH"},"vshd-3c49f21a881ad7":{"friendlyName":"Zehn","template":"SWITCH"},"vshd-9ae7654c49d898":{"friendlyName":"Neun","template":"SWITCH"},"vshd-f56266b8648c30":{"friendlyName":"stoff","template":"SWITCH"},"vshd-17b3a873c8eca2":{"friendlyName":"Alarm auf Alexatest","template":"SWITCH"},"vshd-1555829a612c56":{"friendlyName":"schnipp","template":"SWITCH"},"vshd-a2ce2b1ebf6eb1":{"friendlyName":"Poweroff","template":"SWITCH"},"vshd-30a83f7f9748bf":{"friendlyName":"Sonne","template":"SWITCH"}}}},"metadata":{"reported":{"connected":{"timestamp":1651561563},"vsh_version":{"timestamp":1651560945},"nr_version":{"timestamp":1651560945},"devices":{"vshd-4732cb7f801488":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-e31034baf92d37":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-a6c9b5d7f97e0e":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-6f09ffdca415a7":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-dc59ff65bb604f":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-574c2ac6ccc8bc":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-ecee403697baa5":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-79c31f3cec1f7e":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-6c5df90d7c1448":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-2db69d78a6ed70":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-36cd0febb4129b":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-7d74e4d49bf405":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-8adbdeb719c7a1":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-8e3d794b55f700":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-89a9e7ecafa0fe":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-e6f283582af422":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-3c49f21a881ad7":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-9ae7654c49d898":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-f56266b8648c30":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-17b3a873c8eca2":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-1555829a612c56":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-a2ce2b1ebf6eb1":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}},"vshd-30a83f7f9748bf":{"friendlyName":{"timestamp":1651490111},"template":{"timestamp":1651490111}}}}},"version":233,"timestamp":1651561570}
3 May 09:06:15 - [info] [vsh-connection:intro.alexa@gmail.com] MQTT publish to topic $aws/things/vsht-74daded9-f152-4ba3-8823-20053a810669/shadow/update: {"state":{"reported":{"connected":true,"vsh_version":"2.13.1","nr_version":"1.3.5"}}}`

**Comment by jayjupdhig** [comment]
I think it's too dangerous to post the log here @csuermann 

(It contains some IPs, Domains, Tokens, E-Mail-Adresses ... )

Can i send it directly to you if the problem happens again.

**Comment by Jhonyboy72** [comment]
Is there any solution for this bug so far? Cuz i have the same Problem :-(

**Comment by m4rten** [comment]
same problem here :(

**Comment by csuermann** [comment]
Apologies for not following up on this thread for too long!

I have still not been able to reproduce this problem which only seems to occur for very few users.

You could help me debug this further by providing more information about your environment (which Node-RED and VSH version, OS and hardware are you using?)

I would also need your Node-RED CLI logs showing the output of Node-RED starting up until the problem kicks in.

Thanks for your help!

**Comment by Pabsilon** [comment]
Hi!
I also have this bug. I'm hosting node-red via docker, and I've noticed that this happens when I have power cuts - which means my internet takes a while to start after node-red.
That might be the key to reproducing this bug - node-red starting before having an internet connection available.

Anyhow, the way I solve it, is:
Configuration nodes -> vsh-connection -> update -> deploy.

It's the only part of my flows that have this problem.

**Comment by csuermann** [comment]
Thank you @Pabsilon for providing this insight, which finally allowed me to connect the dots and release a fix.
