### ISSUE TITLE
Transfer flows to new device

### ISSUE THREAD

**Issue by taberner** [csuermann/node-red-contrib-virtual-smart-home#95]
Hi, the device running my node-red flows has expired so I'm transferring the flows to a new device. I can't work out how to create the link to Amazon without also creating duplicate devices in Alexa, as I can't delete the old node red instances (because the machine has expired so I can't run node-red to delete them).

The VSH process suggests I will get the existing device ID back, but I don't believe this to be the case as I had a similar problem a few months ago. I can't see any way to register the old device IDs

hope this makes sense

**Comment by csuermann** [comment]
Hi @taberner,

Once you have set up a new vsh-connection node on your new machine, you will find all previously registered devices listed on the edit dialogue. From there you can remove them.

**Comment by taberner** [comment]
Perfect,

thanks
