### ISSUE TITLE
Can't get Status Update of Blinds in Alexa (APP) 

### ISSUE THREAD

**Issue by Dennis15015** [csuermann/node-red-contrib-virtual-smart-home#97]
Hi, 

I just tried to get the status of my Blinds in the Alexa App. 
I'm using Node red together with IoBroker.
For the Light Bulbs it works but I can't get it working with the blinds. 

I just tried already to change the percentage value to check in Alexa App. But nothing changed. 
Can anybody help me out with this issue?

Thanks in advance.

**Comment by csuermann** [comment]
Hi @Dennis15015,

Could you please share a bit information? What does the Alexa app show? What does your flow look like? Which VSH version are you running?

Thanks!

**Comment by Dennis15015** [comment]
Hi @csuermann 

I already fixed it. just get it. I didn't see that the percentage value I sent to Alexa was in a string. After converting it to number it shows the correct percentage in the App as well. 

Sorry for any inconvenience caused by this. 
This issue is solved :)

**Comment by csuermann** [comment]
Even better! Thanks for reporting back!
