### ISSUE TITLE
Set a range for devices

### ISSUE THREAD

**Issue by smcgann99** [csuermann/node-red-contrib-virtual-smart-home#98]
I'm just looking at your node to see what it can do.

I set up a fan it has 3 speeds, but the fan device allows 1 to 10, there is no way to stop users asking for eg speed 10.
With thermostat the same may apply - ie users could ask for 100 degrees ?

I know a range can be set for devices and alexa can reply with the range if users ask for a value outside this.

Is this something you could add to a future version ?

Thanks

**Comment by thmeger** [comment]
What about changing the value to what you want it to be in Node-RED before sending the command to your device?

**Comment by smcgann99** [comment]
Sure I am doing that by setting anything out of range to max value but its not ideal for end users. 
Just a thought ;-)

**Comment by nob0dy80** [comment]
@smcgann99 
i see it the same way you do.
for my smartmi standing fan its pretty useless. 
The fan has so many more options that i want to use like timers, speed from 1 to 100%.
