### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Purclewan** [csuermann/node-red-contrib-virtual-smart-home#99]
Node fails to initialise in Version 2.12.1.  Working fine before the Upgrade.

When trying to re-initialise after upgrading to Version 2.12.1 everything proceeds as previously until I am asked to confirm my Amazon account.  This appears to work but after a few seconds a message appears, 
ERROR
provisioning failed! VSH Alexa skill enabled?   

See the screen shot below.

 Needless to say I do have my Alexa skill enabled.  Nothing else has changed and all my flows worked fine before the upgrade.  I have tried this on both my Windows Machines (Win 10 running Node Red) and on my two Raspberry Pies (NR Version 1.2.9) all show the same result.  
Any ideas?

![Error](https://user-images.githubusercontent.com/12721449/131878395-2acd56f9-168c-41cb-91b1-1ff132ca50e3.JPG)

**Comment by csuermann** [comment]
Hi @Purclewan,

Could you please try to disable and re-enable the VSH Alexa skill?

Best,
Cornelius

**Comment by Purclewan** [comment]
Hi Cornelius,

That got me further, I know get a Thing ID but the box hangs at the Red update button.

Do I have to totally delete all old Devices.  I have an old backup flow which still has my original devices?

Kind regards,

Michael

**Comment by csuermann** [comment]
Are there any errors showing up in the Dev Tools Console?

**Comment by Purclewan** [comment]
> 
> 
> Are there any errors showing up in the Dev Tools Console?

Not that I can find.  However, I now have it working.  I deleted all my old flows and reset Node-Red.  The system then started working.  I have now brought my old flows back from my backup and strangly it work fine.  I bit baffled but obviously something from my Node-Red needed reseting.  

Anyway, thanks for your prompt help.  Still impressed with your Nodes and thank you very much for your work.
Kind regards
Purclewan

**Comment by csuermann** [comment]
Thanks for reporting back, @Purclewan! And for the kind words!
